coolsnowwolf/lede

- package/libs/libcryptopp/Makefile
- package/libs/wxbase/Makefile
- package/libs/wxbase/patches/wxGTK-2.8.12-abicheck.patch
git commit -a -m 解决amule编译通不过的bug
> 解决amule编译通不过的bug

- package/lean/luci-app-kcptun/po/zh-cn/kcptun.po
> 更新 kcptun.po 文件 增加中文注释 提升逼格

- package/lean/vlmcsd/Makefile
Compile tested: ramips, Newifi D1, OpenWrt trunk
Signed-off-by: Fushan Wen <qydwhotmail@gmail.com>
> vlmcsd: minor fix in Makefile

- package/lean/luci-app-wifidog-ng/Makefile
- package/lean/luci-app-wifidog-ng/luasrc/controller/wifidog-ng.lua
- package/lean/luci-app-wifidog-ng/luasrc/model/cbi/wifidog-ng.lua
- package/lean/luci-app-wifidog-ng/luasrc/view/wifidog-ng/client_list.htm
- package/lean/luci-app-wifidog-ng/luasrc/view/wifidog-ng/wifidog-ng_status.htm
- package/lean/luci-app-wifidog-ng/po/zh-cn/luci-app-wifidog-ng.po
- package/lean/luci-app-wifidog-ng/root/etc/config/wifidog-ng
- package/lean/luci-app-wifidog-ng/root/etc/init.d/wifidog-ng
- package/lean/luci-app-wifidog-ng/root/etc/uci-defaults/001_luci-app-wifidog-ng
- package/lean/luci-app-wifidog-ng/root/tmp/wifidog-ng.init
- package/lean/luci-app-wifidog-ng/root/tmp/wifidog-ng.procd
> add luci-app-wifidog-ng

- package/lean/luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
> Adjustment configuration

- package/lean/dnsforwarder/Makefile
- package/lean/dnsforwarder/files/etc/init.d/dnsforwarder
> fix dnsforwarder

- target/linux/ramips/dts/PBR-M1.dts
> PBR-M1固件大小变更

- package/boot/uboot-envtools/files/ramips
- target/linux/ramips/base-files/etc/board.d/01_leds
- target/linux/ramips/base-files/etc/board.d/02_network
- target/linux/ramips/base-files/lib/ramips.sh
- target/linux/ramips/base-files/lib/upgrade/platform.sh
- target/linux/ramips/dts/MIR4.dts
- target/linux/ramips/image/mt7621.mk
Hardware is the same as mir3g
except:
ram 256M ->  128M
switch  lan 2 3  wan 1 ->  lan 1 2 wan 4
> Add Xiaomi Router 4 support.

- target/linux/bcm53xx/base-files/etc/board.d/02_network
> Update 02_network for K3

- package/base-files/files/sbin/sysupgrade
Reference here: https://dev.archive.openwrt.org/ticket/20711.html
> fix wrong permissions after sysupgrade

- package/lean/qt5/Makefile
fix missing libicu*  files when packing qt5-core.
> add icu to depends

- package/lean/luci-app-ssr-plus/po/zh-cn/ssr-plus.po
- package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.sh
SIP002 URI scheme subscription without plugin
For more informal of SIP002 URI scheme: https://shadowsocks.org/en/spec/SIP002-URI-Scheme.html
> add SIP002 URI scheme subscription

- tools/libelf/Makefile
https://github.com/coolsnowwolf/lede/issues/1632
> libelf 的下载地址已失效

- target/linux/ipq40xx/base-files/lib/upgrade/platform.sh
> fixed r619ac update problem

- package/lean/qt5/Makefile
> delete“-no-qml-debug \”

- .github/workflows/openwrt-ci.yml
> CI: fix indent problems

- package/lean/luci-app-nps/root/etc/init.d/nps
> nps 断线自动重连

- package/lean/mt/luci-app-mtwifi/Makefile
- package/lean/mt/luci-app-mtwifi/root/lib/upgrade/keep.d/mtwifi
> luci-app-mtwifi: keep config on backup and upgrade

- package/lean/luci-app-verysync/Makefile
- package/lean/luci-app-verysync/luasrc/controller/verysync.lua
- package/lean/luci-app-verysync/luasrc/model/cbi/verysync.lua
- package/lean/luci-app-verysync/luasrc/view/verysync/verysync_status.htm
- package/lean/luci-app-verysync/po/zh-cn/verysync.po
- package/lean/luci-app-verysync/root/etc/config/verysync
- package/lean/luci-app-verysync/root/etc/init.d/verysync
- package/lean/luci-app-verysync/root/etc/uci-defaults/luci-verysync
看着微力同步也不顺眼, 一并重写了..
- 添加跳转至微力同步web的按钮
- 重写了页面和启动脚本
- 配置文件目录由`/root/.config/verysync/`改为`/etc/verysync`
- ...
效果图:
---
> luci-app-verysync: add button

- package/lean/pdnsd-alt/Makefile
> pdnsd-alt: fix building on macOS

- package/lean/luci-app-baidupcs-web/Makefile
- package/lean/luci-app-baidupcs-web/luasrc/view/baidupcs-web/baidupcs-web_status.htm
- package/lean/luci-app-baidupcs-web/root/etc/init.d/baidupcs-web
- 修复了只有把所有选项都填入数值配置才会生效的问题
- 修复了LuCI2下的兼容性问题
疏忽了不好意思
> luci-app-baidupcs-web: fix config load

- package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.sh
SSR Plus 订阅处理优化，丢弃无效的节点信息，例如：剩余流量xxx，以免影响节点排序。
> luci-app-ssr-plus: optimize subscription process

- package/lean/luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/advanced.lua
- package/lean/luci-app-ssr-plus/po/zh-cn/ssr-plus.po
- package/lean/luci-app-ssr-plus/root/etc/config/shadowsocksr
- package/lean/luci-app-ssr-plus/root/usr/bin/ssr-switch
有时候只不过是短暂性的无法访问, 多尝试一次就可以.
所以增加尝试次数, 默认每秒钟检查一次.
close #2704
> luci-app-ssr-plus: added try count

- target/linux/generic/pending-4.19/305-mips_module_reloc.patch
- target/linux/ipq40xx/patches-4.19/854-add-sdhci-reset-implementation.patch
1. fix issues #2702
2. 我的锅 Orz，忘记切到4.19编译试下了，函数名变了，别打我（
> target: fixed some patches

- package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua
有些 url 带一些需要转义的字符 忘记了 
加个双引号
顺便处理一下错误日志
> luci-app-ssr-plus: fixed exec escape

- package/lean/frpc/Makefile
Fix panic when proxy meta data is set.
> frpc bump to 0.31.1

- package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua
麻烦 @caicaicai21 测试一下 然后 @coolsnowwolf 再 merge
或者有其他SS机场的朋友测试一下
> luci-app-ssr-plus: support ss subscribe

- package/kernel/mac80211/patches/build/100-backports-pci-Include-linux-pci-aspm.h.patch
- package/kernel/mac80211/patches/build/101-backport-add-pci_disable_link_state-wrapper-with-ret.patch
- package/kernel/mac80211/patches/subsys/368-cfg80211-add-local-BSS-receive-time-to-survey-inform.patch
- package/kernel/mac80211/patches/subsys/522-mac80211_configure_antenna_gain.patch
- package/kernel/mt76/Makefile
> Update mt76 wireless driver.

- target/linux/mvebu/Makefile
> mvebu内核更新为4.19与OPENWRT官方同步

- package/lean/luci-app-ssr-plus/root/etc/init.d/shadowsocksr
> luci-app-ssr-plus: fix pdnsd

- package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua
luci-app-ssr-plus: subscribe.lua nil err (#2822)
```
163     elseif szType == "ss" then
164         local info = content:sub(1, content:find("#") - 1)
165         local alias = content:sub(content:find("#") + 1, #content)
```
> luci-app-ssr-plus: subscribe.lua nil err (#2822)

- package/lean/v2ray-core/Config.in
- package/lean/v2ray-core/Makefile
**Network ---> Project V ---> <*> v2ray-core
You can custom the features in "V2Ray Configuration" option.**
> v2ray-core:Add v2ray-core self compilation

- package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua
> luci-app-ssr-plus: optimize subscribe script and fix ssd subscribe

- package/lean/luci-app-kodexplorer/LICENSE
- package/lean/luci-app-kodexplorer/Makefile
- package/lean/luci-app-kodexplorer/luasrc/model/cbi/kodexplorer/api.lua
- package/lean/luci-app-kodexplorer/luasrc/model/cbi/kodexplorer/settings.lua
- package/lean/luci-app-kodexplorer/luasrc/view/kodexplorer/status.htm
- package/lean/luci-app-kodexplorer/po/zh-cn/kodexplorer.po
- package/lean/luci-app-kodexplorer/root/etc/init.d/kodexplorer
- package/lean/luci-app-kodexplorer/root/etc/uci-defaults/luci-app-kodexplorer
* supports ipv6
* optimize script
> kodexplorer : update

- package/lean/v2ray-plugin/Makefile
> v2ray-plgin: update Makefilew

- package/lean/v2ray-plugin/Makefile
> v2ray-plugin: fix compile on mipsle

- package/lean/shadowsocksr-libev/Makefile
> shadowsocksr-libev

- package/lean/default-settings/Makefile
> default-settings: fix po2lmo error

- package/lean/luci-app-adbyby-plus/root/usr/share/adbyby/admem.sh
- package/lean/luci-app-adbyby-plus/root/usr/share/adbyby/adupdate.sh
根据 https://github.com/coolsnowwolf/lede/issues/3095
业务不熟练，提交了几次
> 更换adbyby规则更新地址

- package/lean/luci-app-ssr-plus/luasrc/view/shadowsocksr/server_list.htm
- package/lean/luci-app-ssr-plus/luasrc/view/shadowsocksr/socket.htm
- package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua
> luci-app-ssr-plus: optimize calc hashkey, fix #3096

- package/firmware/ath10k-firmware/Makefile
- package/kernel/ath10k-ct/Makefile
- package/kernel/ath10k-ct/patches/161-ath10k-add-support-for-configuring-management-packet.patch
- package/kernel/ath10k-ct/patches/162-ath10k-fix-possible-out-of-bound-access-of-ath10k_ra.patch
- package/kernel/ath10k-ct/patches/163-ath10k-fix-incorrect-multicast-broadcast-rate-settin.patch
- package/kernel/ath10k-ct/patches/164-ath10k-commit-rates-from-mac80211.patch
- package/kernel/ath10k-ct/patches/201-ath10k-4.16_add-LED-and-GPIO-controlling-support-for-various-chipsets.patch
- package/kernel/ath10k-ct/patches/202-ath10k-4.16-use-tpt-trigger-by-default.patch
- package/kernel/ath10k-ct/patches/203-ath10k-Limit-available-channels-via-DT-ieee80211-fre.patch
> ath10k-ct: update to 2020-01-29

- package/lean/luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/server.lua
删除第七行local ipkg = require("luci.model.ipkg")
> 删除第七行local ipkg = require("luci.model.ipkg")

- package/lean/frpc/Makefile
Fix not release port when client start proxy error.
> frpc: bump version to v0.31.2

- package/lean/luci-app-dockerman/Makefile
> dockerman: fix dependencies select

- package/lean/ddns-scripts_aliyun/update_aliyun_com.sh
add TTL val
添加TTL值参数设置给购买了解析套餐的人
> add TTL val

- README
jian@ubuntu:~/lede$ ./scripts/feeds update -a
Updating feed 'packages' from 'https://github.com/coolsnowwolf/packages' ...
Already up-to-date.
Create index file './feeds/packages.index' 
Checking 'working-make'... ok.
Checking 'case-sensitive-fs'... ok.
Checking 'proper-umask'... ok.
Checking 'gcc'... ok.
Checking 'working-gcc'... ok.
Checking 'g++'... ok.
Checking 'working-g++'... ok.
Checking 'ncurses'... ok.
Checking 'perl-thread-queue'... ok.
Checking 'tar'... ok.
Checking 'find'... ok.
Checking 'bash'... ok.
Checking 'patch'... ok.
Checking 'diff'... ok.
Checking 'cp'... ok.
Checking 'seq'... ok.
Checking 'awk'... ok.
Checking 'grep'... ok.
Checking 'getopt'... ok.
Checking 'stat'... ok.
Checking 'unzip'... ok.
Checking 'bzip2'... ok.
Checking 'wget'... ok.
Checking 'perl'... ok. …
> 修改readme中的命令，避免编译过程的错误

- package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua
**luci-app-ssr-plus:Adjust invalid nodes**
> luci-app-ssr-plus:Adjust invalid nodes

- package/lean/luci-app-ssr-plus/po/zh-cn/ssr-plus.po
- package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua
- target/linux/ar71xx/image/tiny-tp-link.mk
支持Trojan订阅
支持16M Flash的tl-wr720n-v3
> 支持Trojan订阅；支持16M Flash的tl-wr720n-v3

- package/lean/luci-app-n2n_v2/luasrc/model/cbi/n2n_v2.lua
- package/lean/n2n_v2/files/n2n_v2.init
* Fix autostart error
* Add MTU configuration support
> n2n: Fix autostart error and add MTU configuration support

- package/lean/luci-app-adbyby-plus/po/zh-cn/adbyby.po
Add some translations to luci-app-adbyby-plus
> Add some translations to luci-app-adbyby-plus

- package/lean/luci-app-ssr-plus/Makefile
- package/lean/luci-app-ssr-plus/luasrc/view/shadowsocksr/ssrurl.htm
- package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/gentrojanconfig.lua
- package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua
> luci-app-ssr-plus: refine trojan subscribe and import

- package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua
> luci-app-ssr-plus: filter sb airport

- target/linux/ar71xx/image/generic-tp-link.mk
TL-WDR5800 v1
QCA9561 + QCA9887, based on wdr6500v2
> ar71xx: Add support for TL-WDR5800 v1

- target/linux/ar71xx/image/tiny-tp-link.mk
ar71xx: Add support for TL-WR702N
> ar71xx: Add support for TL-WR702N

- package/lean/luci-app-dockerman/Makefile
- package/lean/luci-app-dockerman/luasrc/model/cbi/dockerman/overview.lua
- package/lean/luci-app-dockerman/po/zh-cn/dockerman.po
- package/lean/luci-app-dockerman/root/etc/config/dockerman
- package/lean/luci-app-dockerman/root/etc/init.d/dockerd
> dockerman: add wan mode option

- package/lean/luci-app-v2ray-server/luasrc/model/cbi/v2ray_server/api/genv2rayconfig.lua
- package/lean/luci-app-v2ray-server/luasrc/model/cbi/v2ray_server/index.lua
- package/lean/luci-app-v2ray-server/po/zh-cn/v2ray_server.po
1.修复http协议时，用户名和密码问题
2.添加丢失的翻译文字
> luci-app-v2ray-server: fix bugs

- package/lean/luci-app-unblockneteasemusic-mini/Makefile
- package/lean/luci-app-unblockneteasemusic-mini/luasrc/model/cbi/unblockneteasemusic-mini.lua
- package/lean/luci-app-unblockneteasemusic-mini/root/etc/init.d/unblockneteasemusic-mini
- Remove support for golang version
- Add @Sunsky03's server
> luci-app-unblockneteasemusic-mini: refresh servers

- package/lean/luci-app-vlmcsd/po/zh-cn/vlmcsd.zh-cn.po
> luci-app-vlmcsd: Fix misspellings

- package/lean/luci-app-verysync/luasrc/model/cbi/verysync.lua
- package/lean/luci-app-verysync/po/zh-cn/verysync.po
- package/lean/luci-app-verysync/root/etc/init.d/verysync
> verysync add profiledir config

- package/lean/luci-app-ssr-plus/root/etc/init.d/shadowsocksr
> luci-app-ssr-plus:ssr-ad separate control use

- package/libs/elfutils/Makefile
- package/libs/elfutils/patches/003-libintl-compatibility.patch
- package/libs/elfutils/patches/100-musl-compat.patch
changes:
40de4c0 elfutils: bump to 0.176
4760541 elfutils: Fix compile with uClibc-ng
0851ce4 elfutils: bump to 0.177
f4da28c elfutils: Add host build
> elfutils: bump to 0.177

- package/lean/luci-app-frps/po/zh-cn/frps.po
> luci-app-frps: add translation for Chinese

- package/lean/luci-app-unblockmusic/root/etc/init.d/unblockmusic
> luci-app-unblockmusic: correct the rule for cloud unblocking

- package/lean/luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/servers.lua
- package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua
1: Sort by airport.
2: Select node optimize.
3: Full update, delete md5 hashkey.
真不容易 这大概是95%正确的lua写法 大家可以参考
另外只想说 openwrt的lua api 真够坑人的
ubus在18的luci中 call uci commit会自动restart 
cli调用参考
```shell
ubus call uci commit '{"config":"configname"}'
```
都快把ubus和uci的源码看完了
> luci-app-ssr-plus: optimize subscribe

- package/lean/luci-app-openvpn-server/luasrc/model/cbi/openvpn-server/openvpn-server.lua
修复这里https://github.com/coolsnowwolf/lede/issues/3657
> Update luci-app-openvpn support IPv6

- package/lean/luci-app-ssr-plus/luasrc/controller/shadowsocksr.lua
- package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/update.lua
**Repair update data does not take effect**
> luci-app-ssr-plus: Fix update script Bug

- package/lean/frp/Makefile
> Fix a typo

- package/lean/luci-app-zerotier/root/etc/zerotier.stop
zerotier handle multiple zt interfaces.
* [ x] 我知道
> zerotier.stop handle multiple interfaces

- package/lean/luci-app-ssr-plus/luasrc/view/shadowsocksr/ssrurl.htm
> luci-app-ssr-plus: fix bug that user can't import trojan url

- target/linux/generic/hack-4.9/952-net-conntrack-events-support-multiple-registrant.patch
- target/linux/generic/pending-4.9/680-NET-skip-GRO-for-foreign-MAC-addresses.patch
> generic-4.9: fix error patch

- package/lean/luci-app-nps/po/zh-cn/nps.po
> nps.po：add translation

- package/lean/luci-app-ssr-plus/root/etc/init.d/shadowsocksr
1. 当ss的插件不存在时输出警告信息到日志文件
2. 删除重复比较的代码
> luci-app-ssr-plus: improve the generation of shadowsocks configuration file

- package/lean/luci-app-ssr-plus/Makefile
- package/lean/luci-app-ssr-plus/luasrc/controller/shadowsocksr.lua
- package/lean/luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/status.lua
> luci-app-ssr-plus: fix Netflix IP bugs

- package/lean/luci-app-ssr-plus/luasrc/controller/shadowsocksr.lua
- package/lean/luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/advanced.lua
- package/lean/luci-app-ssr-plus/po/zh-cn/ssr-plus.po
- package/lean/luci-app-ssr-plus/root/etc/config/shadowsocksr
> luci-app-ssr-plus: add custom Netflix IP Url

- package/lean/luci-app-ssr-plus/luasrc/view/shadowsocksr/server_list.htm
>  luci-app-ssr-plus: feat server list draggable

- package/lean/luci-app-ssr-plus/Makefile
- package/lean/luci-app-ssr-plus/luasrc/controller/shadowsocksr.lua
- package/lean/luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/advanced.lua
- package/lean/luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/status.lua
- package/lean/luci-app-ssr-plus/po/zh-cn/ssr-plus.po
- package/lean/luci-app-ssr-plus/root/etc/config/shadowsocksr
- package/lean/luci-app-ssr-plus/root/etc/uci-defaults/luci-ssr-plus
- package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/update.lua
**Adjust custom URL item display**
> luci-app-ssr-plus:Adjust custom item display

- package/lean/luci-app-ssr-plus/luasrc/view/shadowsocksr/server_list.htm
> luci-app-ssr-plus: reset the behavior of btns in server list

- target/linux/x86/image/Makefile
> x86: fix path for qemu-img

- README.md
* [x ] 我知道
创建优化了README.md，使视觉效果更好。原文档于README
> 创建优化了README.md，使视觉效果更好。

- README.md
> README.md: Optimize English version and code view

- package/lean/luci-app-diskman/Makefile
- package/lean/parted/Makefile
> Add luci-app-diskman

- package/lean/trojan/Makefile
> luci-app-ssr-plus: update trojan to 1.50.0

- target/linux/ramips/files-4.14/drivers/net/ethernet/mediatek/gsw_mt7621.c
- target/linux/ramips/files-4.14/drivers/net/ethernet/mediatek/mtk_eth_soc.c
> MT 7621 断LAN修复

- .github/workflows/openwrt-ci.yml
remove `fatal: Invalid revision range` in CI log
related code: https://github.com/coolsnowwolf/lede/blob/db75f73a54dbc3af09e405f7444ddc1be41f141b/scripts/getver.sh#L15
* [ x ] 我知道
> CI: add fetch depth

- package/lean/luci-app-nft-qos/Makefile
>  luci-app-nft-qos: correct path to luci.mk

- package/lean/luci-app-ssr-plus/Makefile
- package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/update.lua
**luci-app-ssr-plus:Fix update.lua**
> luci-app-ssr-plus:Fix update.lua

- package/lean/luci-app-adbyby-plus/root/etc/init.d/adbyby
> luci-app-adbyby_plus: bugfix

- package/kernel/mwlwifi/patches/001-disable-AMSDU.patch
> mwlwifi: disable A-MSDU

- package/lean/luci-app-ssr-plus/Makefile
- package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/update.lua
> luci-app-ssr-plus: fix gfwlist update error

- package/lean/luci-app-ssr-plus/root/etc/init.d/shadowsocksr
- package/lean/luci-app-ssr-plus/root/etc/uci-defaults/luci-ssr-plus
**Adjust uci-defaults:Create data file**
> luci-app-ssr-plus:Adjust uci-defaults

- package/lean/luci-app-ssr-plus/root/usr/bin/ssr-rules
**Maintenance Usage ssr-rules**
> luci-app-ssr-plus:Maintenance Usage ssr-rules

- package/lean/luci-app-ssr-plus/root/etc/init.d/shadowsocksr
输出自动更新的日志到日志文件。现在是自动更新完后节点乱成一团，没有日志不知道发生了什么事
> luci-app-ssr-plus: output auto update logs to log file

- target/linux/x86/Makefile
> Remove repeat select zerotier

- package/lean/luci-app-cpufreq/Makefile
- package/lean/luci-app-cpufreq/luasrc/model/cbi/cpufreq.lua
- package/lean/luci-app-cpufreq/po/zh-cn/cpufreq.po
**luci-app-cpufreq:Add translation**
> luci-app-cpufreq:Add translation

- target/linux/ath79/generic/base-files/lib/upgrade/platform.sh
- target/linux/bcm27xx/base-files/lib/upgrade/platform.sh
- target/linux/mediatek/mt7623/base-files/lib/upgrade/platform.sh
- target/linux/mvebu/base-files/lib/preinit/79_move_config
- target/linux/mvebu/base-files/lib/preinit/81_linksys_syscfg
- target/linux/mvebu/base-files/lib/preinit/82_uDPU
- target/linux/mvebu/base-files/lib/upgrade/linksys.sh
- target/linux/mvebu/base-files/lib/upgrade/platform.sh
- target/linux/mvebu/base-files/lib/upgrade/sdcard.sh
- target/linux/mvebu/base-files/lib/upgrade/uDPU.sh
> treewide: revert use new procd sysupgrade variable

- package/firmware/ath10k-firmware/Makefile
- package/kernel/ath10k-ct/Makefile
- package/kernel/ath10k-ct/patches/164-ath10k-commit-rates-from-mac80211.patch
- package/kernel/ath10k-ct/patches/170-mac80211-pass-the-vif-to-cancel_remain_on_channel.patch
- package/kernel/ath10k-ct/patches/201-ath10k-4.16_add-LED-and-GPIO-controlling-support-for-various-chipsets.patch
- package/kernel/ath10k-ct/patches/202-ath10k-4.16-use-tpt-trigger-by-default.patch
- package/kernel/ath10k-ct/patches/205-ath10k-Add-NL80211_EXT_FEATURE_AQL-flag.patch
- package/kernel/ath10k-ct/patches/960-0010-ath10k-limit-htt-rx-ring-size.patch
- package/kernel/ath10k-ct/patches/960-0011-ath10k-limit-pci-buffer-size.patch
- package/kernel/ath10k-ct/patches/976-ath10k-Check-if-station-exists-before-forwarding-tx-.patch
> ath10k-ct: bump to 5.4

- package/lean/luci-app-nfs/Makefile
- package/lean/luci-app-nfs/luasrc/controller/nfs.lua
- package/lean/luci-app-nfs/luasrc/model/cbi/nfs.lua
- package/lean/luci-app-nfs/po/zh-cn/nfs.po
- package/lean/luci-app-nfs/root/etc/config/nfs
- package/lean/luci-app-nfs/root/etc/init.d/nfs
- package/lean/luci-app-nfs/root/etc/uci-defaults/nfs
* [yep~ ] 我知道
初始提交是: springsunx  感谢他的工作
已带有依赖关联，已测试本地存储挂载共享正常，还有个挂在远程目录没测试。
通过测试的机型：Newifi D1、竞斗云、EA4500、R3G、K3
此处强烈推荐NFS共享+EXT4啊啊啊啊啊，兼容性俱佳啊啊啊啊啊啊
> 增加NFS服务控制台

- package/lean/luci-app-ssr-plus/luasrc/view/shadowsocksr/ssrurl.htm
- package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua
> luci-app-ssr-plus: OpenWrt SNAPSHOT compatibility

- .github/workflows/openwrt-ci.yml
> CI: add release step

- package/lean/luci-app-unblockmusic/luasrc/model/cbi/unblockmusic.lua
- package/lean/luci-app-unblockmusic/root/etc/init.d/unblockmusic
> luci-app-unblockmusic: add flac switch for nodejs

- target/linux/ipq40xx/base-files/etc/board.d/01_leds
- target/linux/ipq40xx/base-files/etc/board.d/02_network
- target/linux/ipq40xx/base-files/etc/hotplug.d/firmware/11-ath10k-caldata
- target/linux/ipq40xx/base-files/lib/preinit/05_set_iface_mac_ipq40xx.sh
- target/linux/ipq40xx/base-files/lib/preinit/06_set_preinit_iface_ipq40xx.sh
- target/linux/ipq40xx/base-files/lib/upgrade/platform.sh
> ipq40xx: add missing device config for rt-ac1300uhp

- package/lean/luci-app-ssr-plus/Makefile
- package/lean/luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
- package/lean/luci-app-ssr-plus/root/etc/init.d/shadowsocksr
- package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/gentrojanconfig.lua
- package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/genv2config.lua
> luci-app-ssr-plus:Fix kcptun startup errors

- package/lean/luci-app-ssr-plus/Makefile
- package/lean/luci-app-ssr-plus/root/usr/share/rpcd/acl.d/luci-app-ssr-plus.json
Forked from https://github.com/LGA1150/openwrt
> Add ACL rule to compatible with new Luci requirement

- package/kernel/linux/modules/netdevices.mk
> netdevices.mk: fix SFC9x00 config(#4271)

- toolchain/gcc/minimal/Makefile
This can speed up building toolchain
> gcc:use the main make jobserver to install gcc

- README.md
> README.md: Add dependent package for Ubuntu 20.04

- package/lean/v2ray-plugin/Makefile
- package/lean/v2ray/Makefile
> v2ray-plugin:Add GOPROXY support

- package/network/services/dropbear/files/dropbear.config
看了一下系统日志，最近几天，总是有各种来自外网的 ip 尝试连接 ssh，还有几次试成功密码了。
只监听 lan 会安全一点
> dropbear: only bind lan by default

- package/lean/shadowsocksr-libev/Makefile
参数来源：https://github.com/openwrt/packages/commit/c54a826086092b9af17258355af465879dfc9acd#diff-517378957dd5ecc51358b1ae79836edb
经测试，对于ssr也可以优化
测试平台：ar71xx ramips
* [x ] 我知道
>  shadowsocksr-libev：reduce file size

- target/linux/ipq40xx/image/Makefile
> ipq40xx: correct device packages

- package/firmware/linux-firmware/qca_ath10k.mk
- package/kernel/mac80211/ath.mk
> linux-firmware: enable qca4019

- package/boot/uboot-envtools/files/ath79
- package/boot/uboot-envtools/files/ramips
- target/linux/ramips/dts/mt7621_xiaomi_redmi-router-ac2100.dts
- target/linux/ramips/image/mt7621.mk
- target/linux/ramips/mt7621/base-files/etc/board.d/02_network
This commit fix switch and image config for Redmi AC2100.
> ramips: fix support for Redmi AC2100

- target/linux/ramips/dts/mt7621_xiaomi_redmi-router-ac2100.dts
> ramips: fix build error

- package/lean/luci-app-arpbind/Makefile
- package/lean/luci-app-arpbind/root/usr/share/rpcd/acl.d/luci-app-arpbind.json
- package/lean/luci-app-zerotier/Makefile
- package/lean/luci-app-zerotier/root/usr/share/rpcd/acl.d/luci-app-zerotier.json
> make compatible with new upstream Luci requirement

- package/network/services/wireguard/Makefile
> Bump wireguard to 1.0.20200429

- package/lean/luci-app-openvpn-server/root/etc/uci-defaults/openvpn
just one uci commit in script is well
too many commits may crash start in AR9341 routers
> luci-app-openvpn-server:fix start crash in AR9341

- package/lean/luci-app-openvpn-server/root/etc/uci-defaults/openvpn
we can control client directly by adding this forwarding 
also use uci -q batch commands can make starting router faster
> luci-app-openvpn-server:add lan to vpn forwarding

- package/network/services/wireguard/Makefile
> Bump wireguard to version 1.0.20200506

- package/lean/npc/Makefile
add:
api /client/list 添加获取服务端连接host和连接类型 #483
添加自定义客户端断开时间 #485
fix:
web手机浏览输入框或者按钮被遮挡问题，感谢 @kekxv
android客户端无法粘贴的问题 #479
p2p 由于上个版本的一些改动造成无法使用的问题 #515
* [ x] 我知道
> npc：bump version to 0.26.7

- target/linux/ipq40xx/base-files/etc/board.d/02_network
> ipq40xx: adjust switch configuration for netgear ex61x0v2

- package/kernel/mac80211/broadcom.mk
> mac80211: correct target name for bcm

- package/lean/luci-app-frpc/root/usr/share/rpcd/acl.d/luci-app-frpc.json
> Add ACL rule to compliance with new Luci

- package/network/utils/wireguard-tools/Makefile
> Bump wireguard-tool to 1.0.20200513

- package/devel/gdb/patches/130-musl_signal_fix.patch
* Tested on RaspberryPi 4B(bcm2711)
> gdb: Fix build on AArch64

- package/lean/luci-app-unblockmusic/root/etc/hotplug.d/iface/099-unblockmusic
- package/lean/luci-app-unblockmusic/root/etc/init.d/unblockmusic
- package/lean/luci-app-unblockmusic/root/usr/share/UnblockNeteaseMusic/logcheck.sh
> luci-app-unblockmusic: Refresh ipset music list when ifup

- package/lean/luci-app-cifsd/luasrc/model/cbi/cifsd.lua
> make force_root option work

- target/linux/ar71xx/files/arch/mips/ath79/mach-tl-wdr8500-v1.c
> ar71xx: wdr8500: fix build on 4.14

- package/network/services/wireguard/Makefile
> Bump wireguard to 1.0.20200520

- package/lean/baidupcs-web/Makefile
> baidupcs-web: correct download for arm

- package/lean/v2ray-plugin/Makefile
v2ray-plugin:
> Update upstream to v4.23.2.
> v2ray-plugin: update to 1.3.1

- package/lean/default-settings/i18n/default.zh-cn.po
> default-settings: i18n: add space between Chinese and English characters

- package/lean/luci-app-frpc/luasrc/model/cbi/frp/config.lua
- package/lean/luci-app-frpc/po/zh-cn/frp.po
- package/lean/luci-app-frpc/root/etc/init.d/frp
> luci-app-frpc: add plugin "https2http"

- package/network/services/wireguard/Makefile
Bump wireguard to the newest version
> Bump wireguard to v1.0.20200611

- package/lean/verysync/Makefile
@aizhouyi 大佬提供了这个网址，再也不怕他们删历史版本导致编译失败了（x
> verysync: add auto select latest version support

- package/network/services/dnsmasq/patches/900-filter-aaaa.patch
> firewall: refresh 900-filter-aaaa.patch

- package/lean/luci-app-frps/root/usr/share/rpcd/acl.d/luci-app-frps.json
> Add ACL file to luci-app-frps

- package/lean/mt/drivers/mt_wifi/files/firmware.sh
> /sbin/mtkwifi 777 to 755

- package/lean/baidupcs-web/Makefile
> fix baidupcs-go

- package/lean/v2ray-plugin/Makefile
Bump v2ray-plugin to the newest version
> Bump v2ray-plugin to version 1.3.2

- package/lean/UnblockNeteaseMusicGo/Makefile
UnblockNeteaseMusicGo: bump version to 0.2.1
> UnblockNeteaseMusicGo: bump version to 0.2.1

- package/lean/wol/patches/001-fix-build-on-x86.patch
> wol: fix build on x86

- package/lean/rclone-ng/Makefile
* **tasks:** remove tasks viewer
* **list-view:** In Mobile View, double click to open directory, lomg press it to popup detail log.
* **home-mode:** In Mobile View, double click remote item to enter file system,and long press it to popup
detail dialog.
* **dashboard:** add version card ([a36fcbe](https://github.com/ElonH/RcloneNg/commit/a36fcbe91912a1f35c9c84693b4c96647d72d268))
* **home-mode:** support remote detail on mobile view ([2015e2f](https://github.com/ElonH/RcloneNg/commit/2015e2fea6db9fa7eb2adc3b3b5f755c33a52031))
* **jobs-manager:** clean finished groups ([188fcdf](https://github.com/ElonH/RcloneNg/commit/188fcdf56cc00ab0f9be5520714ea09677c15259))
* **jobs-manager:** enable reset stats ([ec025bd](https://github.com/ElonH/RcloneNg/commit/ec025bd8d4a0322f7bcf3b1bfd7cf1f4303f9e1a …
> RcloneNg: bump version from 0.3.2 to 0.4.0

- package/lean/luci-app-rclone/Makefile
- package/lean/luci-app-rclone/luasrc/model/cbi/rclone.lua
- package/lean/luci-app-rclone/po/zh-cn/rclone.po
- package/lean/luci-app-rclone/po/zh_Hans/luci-app-rclone.po
set web client and fuse packages as optional
> luci-app-rclone: bump version from 1.4.0 to 1.4.1

- .github/workflows/openwrt-ci.yml
- README.md
> add missing dependence

- package/lean/mt/drivers/mt7615d/config.in
> mtwifi: repair options

- package/lean/qBittorrent/Makefile
> qBittorrent: bump to v4.2.5

- package/lean/mt/drivers/mt_wifi/Makefile
- target/linux/ramips/mt7621/base-files/etc/board.d/01_leds
> rampis: newifi3: adjust led settings

- package/lean/fast-classifier/Makefile
- package/lean/fast-classifier/src/fast-classifier.c
- package/lean/shortcut-fe/files/etc/init.d/shortcut-fe
其实不用这个 init.d 的，luci 控制即可，fix #5011
> shortcut-fe-cm: load only once to avoid panic

- package/kernel/mwlwifi/patches/002-disable-AMSDU.patch
-----------------------------
重新添加disable-amsdu补丁，解决wrt3200acm、wrt32x，无线延迟的问题
> mwlwifi:add disable-amsdu patch

- target/linux/rockchip/armv8/base-files/etc/board.d/02_network
R2S的描述是eth1为LAN，eth0为WAN(强迫症xD
> R2S:更换接口物理设置

- package/firmware/wireless-regdb/patches/600-custom-change-txpower-and-dfs.patch
> wireless-regdb: custom change txpower and dfs

- target/linux/ramips/image/mt7621.mk
> fix menuconfig missing DIR-878 A1 DIR-882 A1

- target/linux/ramips/image/mt7621.mk
> fix missing dir-882 and dir-878

- target/linux/bcm53xx/image/Makefile
> fix k3 wifi drive problem

- target/linux/bcm27xx/base-files/lib/preinit/82_set_rpi4_info
> bcm27xx: rpi4: enable wifi by default

- package/lean/luci-app-unblockmusic/root/etc/init.d/unblockmusic
> Fix Unblockmusic Cloud unlock Log typo

- .gitignore
> 使项目默认忽略*.log文件

- target/linux/ramips/dts/mt7621_dlink_dir-867-a1.dts
- target/linux/ramips/dts/mt7621_dlink_dir-878-a1.dts
- target/linux/ramips/dts/mt7621_dlink_dir-8xx-a1.dtsi
- target/linux/ramips/dts/mt7621_motorola_mr2600.dts
- target/linux/ramips/dts/mt7621_xiaomi_mir3g.dts
- target/linux/ramips/dts/mt7621_xiaomi_router-ac2100.dtsi
- target/linux/ramips/image/mt7621.mk
- target/linux/ramips/mt7621/base-files/etc/board.d/01_leds
- target/linux/ramips/mt7621/base-files/etc/board.d/02_network
> ramips: improve ac2100/dir882 support

- package/lean/dnsforwarder/files/etc/init.d/dnsforwarder
- package/lean/luci-app-flowoffload/root/etc/init.d/flowoffload
- package/lean/luci-app-sfe/root/etc/init.d/sfe
> fix dnsmasq resolvfile path

- package/lean/mt/drivers/mt7603e/Makefile
- package/lean/mt/drivers/mt7612e/Makefile
- package/lean/mt/drivers/mt_wifi/Makefile
- package/lean/mt/luci-app-mtwifi/Makefile
- package/lean/mt/luci-app-mtwifi/luasrc/view/admin_mtk/mtk_wifi_apcli.htm
- package/lean/mt/luci-app-mtwifi/luasrc/view/admin_mtk/mtk_wifi_overview.htm
- package/lean/mt/luci-app-mtwifi/root/usr/lib/lua/mtkwifi.lua
汉化参考了：https://www.right.com.cn/forum/thread-4040065-1-1.html
> luci-app-mtwifi: add wifi relay support

- README.md
> Readme: Update English version

- package/lean/UnblockNeteaseMusicGo/Makefile
> UnblockNeteaseMusicGo: bump to 0.2.4

- package/lean/luci-app-diskman/Makefile
> luci-app-diskman: bump to v0.2.10

- package/lean/luci-app-zerotier/Makefile
- package/lean/luci-app-zerotier/luasrc/model/cbi/zerotier/info.lua
- package/lean/luci-app-zerotier/root/etc/init.d/zerotier
- package/lean/luci-app-zerotier/root/etc/zerotier.start
- package/lean/luci-app-zerotier/root/etc/zerotier.stop
1.support muilt network id 
2.drop network config when stop 
3.restart service when network changed
code by CN_SZTL 1715173329
https://github.com/project-openwrt/openwrt
> luci-app-zerotier: fix bugs

- README.md
- package/libs/libselinux/Makefile
- package/libs/libsepol/Makefile
- package/libs/pcre/Config.in
- package/libs/pcre/Makefile
Fix depends for libdevmapper & change host pkg name
> fix depends for libdevmapper & change host pkg name

- package/network/utils/iproute2/Makefile
- package/network/utils/iproute2/patches/002-configure-support-ipset-v7.patch
- package/network/utils/iproute2/patches/175-reduce-dynamic-syms.patch
- package/network/utils/iproute2/patches/300-selinux-configurable.patch
follow openwrt:iproute2: disable SELinux for now
> iproute2: disable SELinux for now

- package/lean/luci-app-flowoffload/luasrc/controller/flowoffload.lua
- package/lean/luci-app-sfe/luasrc/controller/sfe.lua
> keep TruboAcc at bottom

- package/network/utils/wireguard-tools/Makefile
> Wireguard-tools: Bump to 1.0.20200820

- package/lean/n2n_v2/Makefile
> update n2n version to 2.8.0

- package/lean/UnblockNeteaseMusicGo/Makefile
> UnblockNeteaseMusicGo 0.2.5

- package/lean/luci-app-docker/root/etc/docker-web
> Change portainer to portainer-ce

- package/lean/verysync/Makefile
> verysync: add more download address to avoid official changes

- package/lean/verysync/Makefile
> verysync: adjust download address

- package/lean/luci-app-kodexplorer/Makefile
> luci-app-kodexplorer: add missing dependencies unzip

- package/system/fstools/Makefile
- package/system/fstools/patches/0001-fstools-support-extroot-for-non-MTD-rootfs_data.patch
> fstools-support-extroot-for-non-MTD-rootfs_data

- package/lean/automount/Makefile
> automount: add libblkid dependencies for exfat

- package/network/services/wireguard/Makefile
> Wireguard: bump to 1.0.20200908

- package/lean/UnblockNeteaseMusicGo/Makefile
> Update UnblockNeteaseMusicGo v0.2.7

- package/lean/v2ray-plugin/Makefile
> v2ray-plugin: bump to 1.5.0

- package/lean/v2ray/Makefile
**v2ray:switch asset files' download url to v2fly**
> v2ray:switch asset files' download url to v2fly

- target/linux/rockchip/armv8/base-files/lib/preinit/82_show_temp
* [x ] 我知道
为NanoPi R2S添加Luci首页的CPU温度显示，效果如图
> show CPU Temperature for NanoPi R2S

- target/linux/rockchip/armv8/base-files/lib/preinit/82_show_temp
revert #5612  to resolve nanopi r2s startup problems,fix #5643
> remove 82_show_temp to resolve r2s start up problems

- package/lean/luci-app-unblockmusic/luasrc/model/cbi/unblockmusic.lua
> Fix Migu typo

- package/lean/microsocks/Makefile
- package/lean/redsocks2/Makefile
- package/lean/simple-obfs/Makefile
- package/lean/trojan/Makefile
**Adjust submenu
Easy to find**
> Adjust submenu

- package/system/fstools/Makefile
> Sync Upstream Code

- package/lean/fast-classifier/Makefile
- package/lean/fast-classifier/src/fast-classifier.c
- package/lean/shortcut-fe/Makefile
> 修复sfe在ipv4环境中打不开的小bug

- package/lean/autocore/Makefile
- package/lean/autocore/files/arm/sbin/cpuinfo
- target/linux/mvebu/Makefile
> autocore-arm: add support for mvebu

- package/network/services/dropbear/files/dropbear.config
> set default interface to lan to avoid attacks

- package/lean/vsftpd-alt/files/vsftpd_prepare
> 使vsftpd返回的文件修改时间与路由器时间同步

- package/network/services/wireguard/Makefile
> Bump wireguard to 1.0.20201112

- package/lean/xray/Config.in
- package/lean/xray/Makefile
搬运至 [xiaorouji](https://github.com/xiaorouji/openwrt-passwall/tree/main/xray) 大佬源码且稍有修改 ,如有冒犯  可随时关闭pr
> add xray (搬运)

- target/linux/ramips/mt7621/base-files/etc/board.d/02_network
* [ x ] 我知道
K2p 32m版本添加板级配置，之前的PR忘了
> K2p 32m 板级配置

- package/lean/luci-app-v2ray-server/root/etc/init.d/v2ray_server
Adjust compatibility with Xray
> Adjust compatibility with Xray

- package/lean/luci-app-v2ray-server/root/etc/init.d/v2ray_server
修复v2ray服务器无法启动问题（那个，下次能不能稍微细心一点）。
> fix v2ray server

- package/lean/xray/Makefile
> xray: bump to 1.1.2 version

- package/lean/qBittorrent/Makefile
- package/lean/qt5/Makefile
Add qt5-sql to the dependencies of qbt.
> Fix qbt compilation errors in specific situation

- package/lean/fast-classifier/Makefile
- package/lean/fast-classifier/src/fast-classifier.c
- package/lean/luci-app-sfe/luasrc/model/cbi/sfe.lua
- package/lean/shortcut-fe/Makefile
Fix unable to start SFE with IPv4 only
> Fix unable to start SFE with IPv4 only

- include/kernel-version.mk
- target/linux/layerscape/patches-5.4/701-net-0149-soc-fsl-dpio-change-CENA-regs-to-be-cacheable.patch
- target/linux/layerscape/patches-5.4/817-spi-0003-MLK-21960-1-spi-fspi-enable-fspi-on-imx8qxp-and-imx8.patch
- target/linux/layerscape/patches-5.4/817-spi-0004-MLK-21960-2-spi-fspi-dynamically-alloc-AHB-memory.patch
- target/linux/rockchip/patches-5.4/004-arm64-dts-rockchip-Add-txpbl-node-for-RK3399-RK3328.patch
> kernel: bump 5.4 to 5.4.84

- target/linux/ramips/dts/mt7621_phicomm_k2p-32m.dts
- target/linux/ramips/dts/mt7621_phicomm_k2p.dts
- target/linux/ramips/dts/mt7621_phicomm_k2p.dtsi
- target/linux/ramips/image/mt7621.mk
fix #6031 , fix #6056 , fix #6077 .
> ramips: fix k2p 32m reboot problems

- package/lean/luci-app-flowoffload/root/etc/init.d/flowoffload
- package/lean/luci-app-sfe/root/etc/init.d/sfe
**Fix flowoffload and SFE disable DNS acceleration without deleting DNS forwarding errors**
> Fix flowoffload and SFE disable DNS acceleration without deleting DNS forwarding errors

- package/lean/autocore/Makefile
- package/lean/autocore/files/arm/sbin/cpuinfo
> autocore: avoid resource busy issue on rpi4

- package/lean/UnblockNeteaseMusicGo/Makefile
- package/lean/frp/Makefile
- package/lean/v2ray-plugin/Makefile
> treewide: upx ignore errors

- package/kernel/linux/files/sysctl-br-netfilter.conf
> 保持默认关闭网桥防火墙，修复NAT loopback不可用的问题

- package/lean/ddns-scripts_aliyun/update_aliyun_com.sh
- package/lean/ddns-scripts_dnspod/update_dnspod_cn.sh
- package/lean/ddns-scripts_dnspod/update_dnspod_com.sh
> 修复某些情况下未定义WGET_SSL变量而找不到wget

- package/lean/uugamebooster/Makefile
- package/lean/uugamebooster/files/uugamebooster.init
fix https://github.com/coolsnowwolf/lede/issues/6193
> uugamebooster: fix missing depends & file conflict

- package/lean/luci-app-ssrserver-python/luasrc/model/cbi/ssrs.lua
- package/lean/luci-app-ssrserver-python/root/etc/init.d/ssrs
> ssrs ipv6 chacha20 支持

- package/lean/luci-app-jd-dailybonus/Makefile
> luci-app-jd-dailybonus: fix install error

- package/lean/luci-app-jd-dailybonus/Makefile
- package/lean/luci-app-jd-dailybonus/luasrc/controller/jd-dailybonus.lua
- package/lean/luci-app-jd-dailybonus/luasrc/model/cbi/jd-dailybonus/client.lua
- package/lean/luci-app-jd-dailybonus/luasrc/view/jd-dailybonus/cookie_tools.htm
- package/lean/luci-app-jd-dailybonus/luasrc/view/jd-dailybonus/update_service.htm
> luci-app-jd-dailybonus：bump to v1.0.2

- package/lean/luci-app-jd-dailybonus/Makefile
> luci-app-jd-dailybonus: update v1.0.3  from jerrykuku

- include/kernel-version.mk
- target/linux/generic/hack-5.4/721-phy_packets.patch
- target/linux/generic/pending-5.4/655-increase_skb_pad.patch
- target/linux/layerscape/patches-5.4/303-core-0001-net-readd-skb_recycle.patch
- target/linux/mediatek/patches-5.4/0600-net-phylink-propagate-resolved-link-config-via-mac_l.patch
> kernel: bump 5.4 to 5.4.92

- package/lean/luci-app-jd-dailybonus/luasrc/controller/jd-dailybonus.lua
- package/lean/luci-app-jd-dailybonus/luasrc/model/cbi/jd-dailybonus/log.lua
- package/lean/luci-app-jd-dailybonus/luasrc/model/cbi/jd-dailybonus/script.lua
- package/lean/luci-app-jd-dailybonus/luasrc/view/jd-dailybonus/update_service.htm
- package/lean/luci-app-jd-dailybonus/root/usr/share/jd-dailybonus/newapp.sh
https://github.com/coolsnowwolf/lede/issues/6260
> luci-app-jd-dailybonus: merge upstream code

- package/network/services/dnsmasq/Makefile
- package/network/services/dnsmasq/files/dhcp.conf
- package/network/services/dnsmasq/files/dnsmasq.init
- package/network/services/dnsmasq/files/dnsmasqsec_hotplug_acl.json
- package/network/services/dnsmasq/patches/900-filter-aaaa.patch
> Revert "dnsmasq: force sync with official code"

- package/lean/luci-app-jd-dailybonus/Makefile
- package/lean/luci-app-jd-dailybonus/luasrc/controller/jd-dailybonus.lua
- package/lean/luci-app-jd-dailybonus/luasrc/model/cbi/jd-dailybonus/log.lua
- package/lean/luci-app-jd-dailybonus/luasrc/view/jd-dailybonus/cookie_tools.htm
- package/lean/luci-app-jd-dailybonus/luasrc/view/jd-dailybonus/log.htm
- package/lean/luci-app-jd-dailybonus/luasrc/view/jd-dailybonus/update_service.htm
- package/lean/luci-app-jd-dailybonus/root/lib/upgrade/keep.d/jd-dailybonus
- package/lean/luci-app-jd-dailybonus/root/usr/share/jd-dailybonus/JD_DailyBonus.js
> luci-app-jd-dailybonus: Keep up to date from jerrykuku

- package/network/services/wireguard/Makefile
> Bump wireguard to 1.0.20210124

- package/lean/npc/Makefile
Bump npc to the newest version
> Bump npc to 0.26.9

- package/lean/ipt2socks/Makefile
https://github.com/zfl9/ipt2socks/releases/tag/v1.1.3
> ipt2socks:bump to 1.1.3

- package/base-files/files/etc/rc.common
同步[openwrt 3f1109bf](https://github.com/openwrt/openwrt/blob/3f1109bf2af2cf4977689a33ea481afaaac8dc98/package/base-files/files/etc/rc.common)源码，增加了`extra_command`方法，且兼容旧版本。
> add function extra_command

- target/linux/ramips/dts/mt7621_netgear_sercomm_bzv.dtsi
- target/linux/ramips/mt7621/base-files/etc/board.d/02_network
Signed-off-by: noire11 <noire.wei@gmail.com>
> ramips: use mt proprietary driver for Netgear R6800

- package/lean/v2ray-plugin/patches/001-replace-incompatible.patch
> v2ray-plugin: fix build with goproxy

- package/lean/xray-plugin/Makefile
> Add xray-plugin from Tianling Shen

- package/lean/luci-app-ipsec-vpnd/Makefile
> Revert "luci-app-ipsec-vpnd: add strongswan-mod-kernel-libipsec"

- include/kernel-version.mk
- target/linux/generic/pending-5.4/491-ubi-auto-create-ubiblock-device-for-rootfs.patch
- target/linux/layerscape/patches-5.4/701-net-0273-net-dsa-ocelot-add-tsn-support-for-felix-switch.patch
- target/linux/layerscape/patches-5.4/701-net-0381-net-dsa-Pass-pcs_poll-flag-from-driver-to-PHYLINK.patch
- target/linux/mediatek/patches-5.4/0601-net-dsa-propagate-resolved-link-config-via-mac_link_.patch
> kernel: bump 5.4 to 5.4.101

- package/lean/r8125/Makefile
- package/lean/r8125/src/Makefile
- package/lean/r8125/src/Makefile_linux24x
- package/lean/r8125/src/r8125.h
- package/lean/r8125/src/r8125_dash.h
- package/lean/r8125/src/r8125_n.c
- package/lean/r8125/src/r8125_ptp.c
- package/lean/r8125/src/r8125_ptp.h
- package/lean/r8125/src/r8125_realwow.h
- package/lean/r8125/src/r8125_rss.c
- package/lean/r8125/src/r8125_rss.h
- package/lean/r8125/src/rtl_eeprom.c
- package/lean/r8125/src/rtl_eeprom.h
- package/lean/r8125/src/rtltool.c
- package/lean/r8125/src/rtltool.h
Enabled RSS support for performance.
Signed-off-by: CN_SZTL <cnsztl@project-openwrt.eu.org>
> r8125: bump to 9.005.01

- feeds.conf.default
Synchronize official source code
> feeds.conf.default: remove freifunk

- package/lean/luci-app-jd-dailybonus/luasrc/model/cbi/jd-dailybonus/client.lua
> luci-app-jd-dailybonus: Add CDN

- package/libs/mbedtls/Makefile
> mbedtls: fix typo error

- target/linux/rockchip/armv8/base-files/etc/board.d/01_leds
> rockchip: leds: fix boardname for NanoPi R4S

- package/lean/luci-app-jd-dailybonus/Makefile
- package/lean/luci-app-jd-dailybonus/luasrc/model/cbi/jd-dailybonus/client.lua
- package/lean/luci-app-jd-dailybonus/luasrc/view/jd-dailybonus/cookie_tools.htm
> luci-app-jd-dailybonus：“bug fix” from jerrykuku

- package/lean/UnblockNeteaseMusicGo/Makefile
> UnblockNeteaseMusicGo: update v0.2.9

- package/network/utils/curl/Makefile
> Remove expired source

- package/boot/uboot-rockchip/patches/102-rockchip-rk3399-Add-support-for-FriendlyARM-NanoPi-R.patch
- package/boot/uboot-rockchip/patches/200-rockchip-rk3399-split-nanopi-r4-rk3399-out-of-evb_rk.patch
- target/linux/rockchip/armv8/base-files/etc/board.d/01_leds
- target/linux/rockchip/patches-5.4/009-rockchip-rk3399-Add-support-for-FriendlyARM-NanoPi-R.patch
- target/linux/rockchip/patches-5.4/100-rockchip-use-system-LED-for-OpenWrt.patch
Link: https://lore.kernel.org/r/20210319051627.814-2-cnsztl@gmail.com
> rockchip: nanopi-r4s: refresh latest patches accepted by upstream

- package/lean/uugamebooster/Makefile
> uugamebooster: update to 2.9.0

- package/lean/luci-app-xlnetacc/Makefile
- package/lean/luci-app-xlnetacc/luasrc/model/cbi/xlnetacc.lua
- package/lean/luci-app-xlnetacc/po/zh-cn/xlnetacc.po
- package/lean/luci-app-xlnetacc/root/usr/bin/xlnetacc.sh
在 https://github.com/sensec/luci-app-xlnetacc/commit/821c5dcf7a45dd73068151ac3c93f74fe5891ba6 的基础上重放了大雕对luci-app-xlnetacc的修改，
然后merge https://github.com/sensec/luci-app-xlnetacc
编译了ipk经测无问题
[luci-app-xlnetacc_1.0.5-1_all.ipk.zip](https://github.com/coolsnowwolf/lede/files/6222796/luci-app-xlnetacc_1.0.5-1_all.ipk.zip)
> luci-app-xlnetacc: update to 1.0.5

- package/lean/v2ray-plugin/Makefile
> v2ray-plugin: update to 4.37.2

- include/kernel-version.mk
- target/linux/generic/hack-5.4/204-module_strip.patch
- target/linux/generic/hack-5.4/721-phy_packets.patch
- target/linux/generic/pending-5.4/680-NET-skip-GRO-for-foreign-MAC-addresses.patch
- target/linux/generic/pending-5.4/690-net-add-support-for-threaded-NAPI-polling.patch
- target/linux/layerscape/patches-5.4/802-can-0002-can-rx-offload-fix-long-lines.patch
- target/linux/layerscape/patches-5.4/802-can-0003-can-rx-offload-can_rx_offload_compare-fix-typo.patch
- target/linux/layerscape/patches-5.4/802-can-0004-can-rx-offload-can_rx_offload_irq_offload_timestamp-.patch
- target/linux/layerscape/patches-5.4/802-can-0005-can-rx-offload-can_rx_offload_reset-remove-no-op-fun.patch
- target/linux/layerscape/patches-5.4/802-can-0006-can-rx-offload-Prepare-for-CAN-FD-support.patch
- target/linux/layerscape/patches-5.4/802-can-0018-can-flexcan-use-struct-canfd_frame-for-CAN-classic-f.patch
> kernel: bump 5.4 to 5.4.110

- package/lean/dnsforwarder/files/etc/init.d/dnsforwarder
fix dnsmasq configuration modification logic
> fix dnsforwarder configuration modification logic

- package/lean/v2ray-plugin/Makefile
https://github.com/coolsnowwolf/lede/issues/6693
> Revert "v2ray-plugin: update to 4.37.3"

- package/kernel/linux/modules/can.mk
> kernel: Adapt renamed can-dev.ko

- package/lean/frp/Makefile
Upgrade frp to v0.36.2.
已经自己编译通过，测试可以正常使用。
> Upgrade frp to the latest version.

- package/lean/shadowsocksr-libev/Makefile
> Reduce file size again

- package/network/services/wireguard/Makefile
> Bump wireguard to the latest version

- target/linux/ramips/dts/mt7621_xiaomi_mi-router-cr6606.dts
- target/linux/ramips/image/mt7621.mk
- target/linux/ramips/mt7621/base-files/etc/board.d/01_leds
- target/linux/ramips/mt7621/base-files/etc/board.d/02_network
> ramips: xiaomi cr6606: typo fixes

- include/kernel-version.mk
> kernel: bump 5.4 to 5.4.116

- package/lean/vsftpd-alt/files/vsftpd_prepare
> 修复 FTP 欢迎提示 配置不生效问题

- package/lean/luci-app-unblockmusic/root/etc/init.d/unblockmusic
> go版本仅这两个源可用，全部加上优化体验

- package/lean/luci-app-ttyd/luasrc/view/terminal/terminal.htm
> luci-app-ttyd 修改iframe高度自适应

- README_EN.md
- line 8: add `for compiling` to make the sentence clear
- line 23: source should be source code
- line 61: safe should be safety; archive should be achieve
- line 65: `motivate` is better
* [x ] 我知道
> fix mistakes for English Readme

- package/lean/luci-theme-argon/htdocs/luci-static/argon/css/style.css
* [ x] 我知道
主要内容：
.cbi-value | .cbi-value-title | .cbi-value-field
修改成 flex，做了行内垂直居中
修改影响到的 table 样式稍微修改了一下行高
> 修改 argon 的样式，好多不对齐，改 cbi-value 相关成 flex，chrome 90 测试

- package/system/zram-swap/Makefile
- package/system/zram-swap/files/zram.init
> zram-swap: sync upstream source

- package/lean/luci-app-frpc/Makefile
- package/lean/luci-app-frpc/luasrc/model/cbi/frp/frp.lua
- package/lean/luci-app-frpc/po/zh-cn/frp.po
- package/lean/luci-app-frpc/root/etc/init.d/frp
> luci-app-frpc: Support TLS Connection and Admin Web

- package/lean/r8152/Makefile
- package/lean/r8152/patches/010-compat-skb_mark_not_on_list-was-backported-since-ker.patch
Fixes: 1024f0ec23f63d ("r8152: update to 2.15 (#6900)")
Fixes: #6946
> r8152: fix build under kernel >= 4.19.10 or kernel >= 4.14.217

- package/lean/mt/drivers/mt7612e/src/mt76x2/ap/ap_wds.c
> mtwifi: mt7612: fix build error

- package/kernel/mac80211/files/lib/wifi/mac80211.sh
> Set WiFi country to US by default

- package/network/utils/dpdk/Makefile
> fix dpdk Makefile errors

- scripts/download.pl
> download.pl: add more mirrors addresses

- package/base-files/files/bin/config_generate
> base-files: NTP服务器默认设置为国内有效服务器

- package/network/services/dropbear/files/dropbear.config
> dropbear: 指定监听接口为lan

- target/linux/mvebu/Makefile
已经在本地编译通过，WRT1200AC实机测试各项常用功能正常
* [x ] 我知道
> mvebu内核更新为5.10

- package/lean/frp/Makefile
> Update frp to v0.37.0

- package/network/services/hostapd/files/hostapd.sh
> hostapd: add default_disabled option to the supplicant

- package/lean/luci-lib-docker/Makefile
- package/lean/luci-lib-docker/luasrc/docker.lua
> Luci-lib-docker: Update to v0.3.4

- package/lean/luci-app-diskman/Makefile
- package/lean/luci-lib-docker/Makefile
- package/lean/luci-lib-docker/luasrc/docker.lua
> Luci-app-diskman: update to v0.2.11

- package/network/services/hostapd/files/hostapd.sh
> hostapd: add support for providing vendor specific IE elements

- package/lean/luci-app-easymesh/root/etc/init.d/easymesh
> update lan bat0 binding

- package/kernel/mac80211/ath.mk
- package/kernel/mac80211/files/lib/netifd/wireless/mac80211.sh
- package/kernel/mac80211/patches/ath10k/983-ath10k-allow-vht-on-2g.patch
- package/kernel/mac80211/patches/subsys/600-mac80211-allow-vht-on-2g.patch
- package/network/services/hostapd/files/hostapd.sh
> ath10k: re-added 256qam support

- package/lean/luci-app-arpbind/po/zh-cn/arpbind.po
- package/lean/luci-app-flowoffload/po/zh-cn/flowoffload.po
- package/lean/luci-app-sfe/po/zh-cn/sfe.po
> Perfect translation

- package/lean/vlmcsd/Makefile
> Fix Makefile Error

- package/lean/luci-app-docker/Makefile
> Add docker-cli depend

- package/lean/k3screenctrl/Makefile
> fix k3screenctrl DEPENDS

- package/base-files/files/bin/config_generate
https://help.aliyun.com/document_detail/92704.html
> base-files: 更换阿里云 NTP 地址为官方帮助文档中的第一条

- package/lean/dnsforwarder/files/etc/init.d/dnsforwarder
- package/network/config/ltq-adsl-app/files/dsl_control
- package/network/config/ltq-vdsl-app/files/dsl_control
- package/system/zram-swap/files/zram.init
修复https://github.com/coolsnowwolf/lede/issues/7245
> packages: use old extra_command wrapper

- package/lean/qtbase/Makefile
add qt-sql for qBittorrent-Enhanced-Edition
> add qt-sql for qBittorrent-Enhanced-Edition

- package/lean/luci-app-docker/luasrc/model/cbi/docker.lua
- package/lean/luci-app-docker/po/zh-cn/docker.po
> 改正把Docker写成Dokcer的小错误

- package/lean/luci-app-nfs/luasrc/model/cbi/nfs.lua
系统-挂载点 路径应为 `admin/system/fstab` 而不是 `admin/system/mounts`
> luci-app-nfs: adjust fstab_url

- package/lean/uugamebooster/Makefile
> uugamebooster: update to 2.12.0

- package/network/services/hostapd/src/src/ap/ubus.c
> hostapd: add "force" parameter for channel switch

- package/lean/mentohust/Makefile
> mentohust: add new package

- toolchain/gcc/Config.in
- toolchain/gcc/Config.version
- toolchain/gcc/common.mk
- toolchain/gcc/patches/11.1.0/002-case_insensitive.patch
- toolchain/gcc/patches/11.1.0/010-documentation.patch
- toolchain/gcc/patches/11.1.0/110-Fix-MIPS-PR-84790.patch
- toolchain/gcc/patches/11.1.0/230-musl_libssp.patch
- toolchain/gcc/patches/11.1.0/300-mips_Os_cpu_rtx_cost_model.patch
- toolchain/gcc/patches/11.1.0/810-arm-softfloat-libgcc.patch
- toolchain/gcc/patches/11.1.0/820-libgcc_pic.patch
- toolchain/gcc/patches/11.1.0/840-armv4_pass_fix-v4bx_to_ld.patch
- toolchain/gcc/patches/11.1.0/850-use_shared_libgcc.patch
- toolchain/gcc/patches/11.1.0/851-libgcc_no_compat.patch
- toolchain/gcc/patches/11.1.0/870-ppc_no_crtsavres.patch
- toolchain/gcc/patches/11.1.0/881-no_tm_section.patch
- toolchain/gcc/patches/11.1.0/900-bad-mips16-crt.patch
- toolchain/gcc/patches/11.1.0/910-mbsd_multi.patch
- toolchain/gcc/patches/11.1.0/920-specs_nonfatal_getenv.patch
- toolchain/gcc/patches/11.1.0/930-fix-mips-noexecstack.patch
- toolchain/gcc/patches/11.1.0/931-libffi-fix-MIPS-softfloat-build-issue.patch
- toolchain/gcc/patches/11.1.0/960-gotools-fix-compilation-when-making-cross-compiler.patch
> toolchain: add gcc 11 version

- package/network/services/dnsmasq/files/dnsmasq.init
> dnsmasq: add /tmp/hosts/ to jail_mount

- README.md
> update readme.md add wsl note

- package/lean/qtbase/Makefile
- package/lean/qtbase/patches/010-gcc11.patch
- package/lean/qttools/Makefile
> qt: Update to 5.15.2

- package/lean/ntfs3/Makefile
> fix ntfs3 compiling problem

- package/lean/autocore/Makefile
> Fix autocore-arm Makefile for ipq807x

- package/lean/luci-app-ttyd/luasrc/view/terminal/terminal.htm
> fix: 修复ttyd无法在https下使用

- target/linux/ath79/dts/qca9558_tplink_tl-wdr7500-v3-16MB.dts
- target/linux/ath79/generic/base-files/etc/board.d/02_network
- target/linux/ath79/generic/base-files/etc/hotplug.d/firmware/11-ath10k-caldata
- target/linux/ath79/image/generic-tp-link.mk
> add TP-LINK TL-WDR7500 V3-16MB

- target/linux/ramips/mt7621/base-files/etc/board.d/02_network
> ramips: cr660x: fix network settings

- package/network/services/dnsmasq/files/dnsmasq.init
> dnsmasq: rework jail mounts

- target/linux/ramips/dts/mt7621_hiwifi_hc5962.dts
- target/linux/ramips/image/mt7621.mk
- target/linux/ramips/mt7621/base-files/etc/board.d/02_network
> ramips: hc5962: switch to use ralink-eth driver

- target/linux/rockchip/armv8/base-files/lib/preinit/79_move_config
- target/linux/rockchip/armv8/base-files/lib/upgrade/platform.sh
> rockchip: revert upgrade part change

- package/lean/luci-app-pushbot/Makefile
- package/lean/luci-app-pushbot/README.md
- package/lean/luci-app-pushbot/luasrc/controller/pushbot.lua
- package/lean/luci-app-pushbot/luasrc/model/cbi/pushbot/advanced.lua
- package/lean/luci-app-pushbot/luasrc/model/cbi/pushbot/client.lua
- package/lean/luci-app-pushbot/luasrc/model/cbi/pushbot/log.lua
- package/lean/luci-app-pushbot/luasrc/model/cbi/pushbot/setting.lua
- package/lean/luci-app-pushbot/luasrc/view/pushbot/log.htm
- package/lean/luci-app-pushbot/luasrc/view/pushbot/status.htm
- package/lean/luci-app-pushbot/root/etc/config/pushbot
- package/lean/luci-app-pushbot/root/etc/init.d/pushbot
- package/lean/luci-app-pushbot/root/etc/uci-defaults/luci-pushbot
- package/lean/luci-app-pushbot/root/usr/bin/pushbot/pushbot
- package/lean/luci-app-pushbot/root/usr/share/rpcd/acl.d/luci-app-pushbot.json
添加-luci-app-pushbot
[luci-app-pushbot](https://github.com/zzsj0928/luci-app-pushbot.git)跟[luci-app-serverchan](https://github.com/tty228/luci-app-serverchan)不同点如下：
* 实现了 IOS-bark的通知推送
* 通知栏：直接显示推送主题，一目了然，按设备不同，分组显示
* 消息列表：直接显示最新推送的标题
* 消息内容：直接显示所有推送信息，不用二次点开再查看
* [感谢 tty228 开发了这个插件](https://github.com/tty228/luci-app-serverchan)
* [感谢zzsj0928实现了上数功能](https://github.com/zzsj0928/luci-app-pushbot.git)
* 添加原因: 为了方便和快速编译。
> 添加luci-app-pushbot

- package/lean/qBittorrent-static/Makefile
- package/lean/qBittorrent/Makefile
> qbittorrent: bump to v4.3.7

- package/lean/vsftpd-alt/Makefile
- package/lean/vsftpd-alt/patches/001-destdir.patch
- package/lean/vsftpd-alt/patches/002-find_libs.patch
- package/lean/vsftpd-alt/patches/003-chroot.patch
- package/lean/vsftpd-alt/patches/007-CVE-2015-1419.patch
- package/lean/vsftpd-alt/patches/010-openssl-deprecated.patch
- package/lean/vsftpd-alt/patches/100-add-uci-auth-support.patch
- package/lean/vsftpd-alt/patches/101-enable-chroot-on-writable-dir.patch
- package/lean/vsftpd-alt/patches/102-keep-local-user-rights.patch
> vsftpd-alt: update to 3.0.5

- package/kernel/mac80211/files/lib/netifd/wireless/mac80211.sh
- package/kernel/mac80211/patches/subsys/376-mac80211-add-rate-control-support-for-encap-offload.patch
- package/kernel/mac80211/patches/subsys/383-mac80211-fix-enabling-4-address-mode-on-a-sta-vif-af.patch
- package/kernel/mac80211/patches/subsys/386-mac80211-check-per-vif-offload_flags-in-Tx-path.patch
- package/kernel/mac80211/patches/subsys/782-net-next-1-of-net-pass-the-dst-buffer-to-of_get_mac_address.patch
> mac80211: sync upstream

- target/linux/ramips/dts/mt7621_raisecom_msg1500-x-00.dts
- target/linux/ramips/image/mt7621.mk
- target/linux/ramips/mt7621/base-files/etc/board.d/02_network
- target/linux/ramips/mt7621/base-files/etc/hotplug.d/ieee80211/10_fix_wifi_mac
- target/linux/ramips/mt7621/base-files/lib/upgrade/platform.sh
> ramips: add support for RAISECOM MSG1500 X.00

- package/lean/default-settings/files/zzz-default-settings
> default-settings: move samba4 to nas

- package/lean/shortcut-fe/shortcut-fe/Makefile
- package/lean/shortcut-fe/shortcut-fe/files/etc/init.d/shortcut-fe
- package/lean/shortcut-fe/shortcut-fe/src/sfe_cm.c
* [ x] 我知道
**~~!!! NEED MORE TEST !!!~~**
**~~DON'T PULL REQUEST NOW PLEASE~~**
**~~WE NEED MORE LOG DATA~~**
~~你们SFE有问题，又不给我提交日志，我很难办啊。~~
**已修复：**
**bug fixes:**
多拨等环境下的路由问题
a problem of lookup routes when skb provided.
shortcut-fe-cm启动太快
fix the issue of shortcut-fe-cm premature loading
> shortcut-fe: fix the issue of shortcut-fe-cm.

- package/lean/luci-app-pushbot/Makefile
- package/lean/luci-app-pushbot/luasrc/model/cbi/pushbot/advanced.lua
- package/lean/luci-app-pushbot/root/usr/bin/pushbot/api/bark.json
- package/lean/luci-app-pushbot/root/usr/bin/pushbot/pushbot
- 增加全球互联判断，
- 新增支持读取宿主机PVE温度，<- 抄自原作者主项目(serverchan)
- 新增支持宿主机的自定义SSH端口，
- 修复bark推送百分号
> luci-app-pushbot: update to 3.55-21

- package/lean/qBittorrent-static/Makefile
- package/lean/qBittorrent/Makefile
> qbittorrent: bump to v4.3.8

- package/network/utils/wireguard-tools/Makefile
> Bump wireguard-tools to the latest version

- include/kernel-version.mk
- target/linux/bcm27xx/patches-5.10/950-0057-Improve-__copy_to_user-and-__copy_from_user-performa.patch
- target/linux/bcm27xx/patches-5.10/950-0139-xhci-implement-xhci_fixup_endpoint-for-interval-adju.patch
- target/linux/bcm27xx/patches-5.10/950-0201-mmc-sdhci-Silence-MMC-warnings.patch
- target/linux/bcm27xx/patches-5.10/950-0376-ARM-dts-bcm27xx-Remove-enable_headphones-setting.patch
- target/linux/bcm27xx/patches-5.10/950-0438-dt-Add-a-camera-regulator-node-to-all-downstream-Pi-.patch
- target/linux/bcm27xx/patches-5.10/950-0509-ARM-dts-bcm2711-Add-aliases-for-additional-SPIs.patch
- target/linux/bcm27xx/patches-5.10/950-0639-cgroup-Disable-cgroup-memory-by-default.patch
- target/linux/bcm27xx/patches-5.10/950-0706-ARM-dts-bcm2711-Tidy-the-HDMI-I2C-aliases.patch
- target/linux/bcm27xx/patches-5.10/950-0733-usb-xhci-workaround-for-bogus-SET_DEQ_PENDING-endpoi.patch
- target/linux/bcm27xx/patches-5.10/950-0736-ARM-dts-Adapt-to-upstream-changes.patch
- target/linux/generic/backport-5.10/600-v5.12-net-extract-napi-poll-functionality-to-__napi_poll.patch
- target/linux/generic/backport-5.10/601-v5.12-net-implement-threaded-able-napi-poll-loop-support.patch
- target/linux/generic/backport-5.10/602-v5.12-net-add-sysfs-attribute-to-control-napi-threaded-mod.patch
- target/linux/generic/backport-5.10/603-v5.12-net-fix-race-between-napi-kthread-mode-and-busy-poll.patch
- target/linux/generic/backport-5.10/604-v5.12-net-fix-hangup-on-napi_disable-for-threaded-napi.patch
- target/linux/generic/hack-5.10/953-net-patch-linux-kernel-to-support-shortcut-fe.patch
- target/linux/generic/pending-5.10/680-NET-skip-GRO-for-foreign-MAC-addresses.patch
- target/linux/ramips/patches-5.10/720-Revert-net-phy-simplify-phy_link_change-arguments.patch
- target/linux/ramips/patches-5.10/721-NET-no-auto-carrier-off-support.patch
Signed-off-by: boos4721 <3.1415926535boos@gmail.com>
> kernel: bump 5.10 to 5.10.77

- include/kernel-version.mk
- target/linux/bcm27xx/patches-5.10/950-0054-BCM2708-Add-core-Device-Tree-support.patch
- target/linux/bcm27xx/patches-5.10/950-0138-usb-add-plumbing-for-updating-interrupt-endpoint-int.patch
- target/linux/bcm27xx/patches-5.10/950-0139-xhci-implement-xhci_fixup_endpoint-for-interval-adju.patch
- target/linux/generic/pending-5.10/811-pci_disable_usb_common_quirks.patch
Signed-off-by: boos4721 <3.1415926535boos@gmail.com>
> kernel: bump 5.10 to 5.10.78

- package/lean/go-aliyundrive-webdav/Makefile
> go-aliyundrive-webdav:Update to v1.0.15

- package/boot/uboot-rockchip/Makefile
- package/boot/uboot-rockchip/patches/105-rockchip-rk3399-Add-support-for-EmbedFire-DoorNet2.patch
- target/linux/rockchip/armv8/base-files/etc/board.d/01_leds
- target/linux/rockchip/armv8/base-files/etc/board.d/02_network
- target/linux/rockchip/armv8/base-files/etc/hotplug.d/net/40-net-smp-affinity
- target/linux/rockchip/image/armv8.mk
- target/linux/rockchip/patches-5.4/205-rockchip-rk3399-Add-support-for-EmbedFire-DoorNet2.patch
Hardware Specification:
CPU: RockChip RK3399
RAM:  DDR3 1GB or More
Ethernet: 2x 1000 Base-T
Wireless: RTL8811CU WIFI module, SMA antenna base
Emmc: 8GB or More
LED: POWER, SYS, WAN, LAN
MicroSD Slot x 1
Button: Reset, Flash
USB: 2 x 3.0  Type-A
Serial: 3 Pin debug port
Type-C: for power input
Power Supply: DC 5V/3A
> rockchip: add support for Embedfire DoorNet2

- package/lean/autocore/files/arm/sbin/cpuinfo
- target/linux/rockchip/patches-5.10/205-rockchip-rk3399-Add-support-for-EmbedFire-DoorNet2.patch
> rockchip:rk3399 increases the frequency of complete information of the big core

- package/lean/autocore/files/arm/sbin/cpuinfo
> Make up the ipq temperature

- package/lean/uugamebooster/Makefile
> uugamebooster: bump to v2.18.0

- target/linux/ipq806x/patches-5.4/0065-arm-override-compiler-flags.patch
> ipq806x: fix compile error

- package/base-files/files/lib/functions.sh
- package/base-files/files/lib/functions/caldata.sh
- package/base-files/files/lib/functions/system.sh
> base-file: Add mmc support

- package/lean/uugamebooster/Makefile
>  uugamebooster: bump to v2.18.2

- target/linux/x86/patches-5.4/993-bnx2x_warpcore_8727_2_5g_sgmii_txfault.patch
https://www.dslreports.com/forum/r32230041-Internet-Bypassing-the-HH3K-up-to-2-5Gbps-using-a-BCM57810S-NIC
> Bypassing the HH3K up to 2.5Gbps using a BCM578xx

- package/lean/luci-app-easymesh/Makefile
- package/lean/luci-app-easymesh/luasrc/model/cbi/easymesh.lua
- package/lean/luci-app-easymesh/po/zh-cn/easymesh.po
- package/lean/luci-app-easymesh/root/etc/init.d/easymesh
加入 角色选择项 可选择主MESH 子MESH
支持多无线设备组网（2.4G 5G同时）
组网后无活动节点请关闭mesh加密设置
> luci-app-easymesh update v1.9

- package/lean/luci-app-easymesh/root/etc/init.d/easymesh
> Fix the missing lan configuration

- package/lean/n2n_v2/Makefile
Closed: #8205 , need someone to test this.
> n2n: update to 3.0

- include/kernel-version.mk
- target/linux/ipq60xx/patches-5.10/994-ipq6018-mem-profile.patch
- target/linux/ipq60xx/patches-5.10/995-ipq6018-mem-block.patch
Signed-off-by: boos4721 <3.1415926535boos@gmail.com>
Build system: x86_64
Build-tested: ipq807x/AX3600
Run-tested: ipq807x/AX3600
> kernel: bump 5.10 to 5.10.87

- package/lean/luci-app-unblockmusic/Makefile
- package/lean/luci-app-unblockmusic/root/usr/share/UnblockNeteaseMusic/update_core.sh
1：修复界面版本显示不正常
2：使用重定向git源
3：修复UnblockNeteaseMusic core 更新不成功问题
> UnblockNeteaseMusic: Bug Fix

- package/lean/luci-app-unblockmusic/Makefile
- package/lean/luci-app-unblockmusic/luasrc/model/cbi/unblockmusic/unblockmusic.lua
- package/lean/luci-app-unblockmusic/root/etc/init.d/unblockmusic
1：新增本地黑胶VIP选项
2：修复320Kbps高质量功能无法使用，改为自定义选择音乐音质
PS：Part of the code refers to the UnblockNeteaseMusic upstream project
> UnblockNeteaseMusic: add local VIP and repair failure to replace 320Kbps music source

- package/lean/qBittorrent-static/Makefile
- package/lean/qBittorrent/Makefile
* qBittorrent: bump to v4.4.0
* qBittorrent-static: bump to v4.4.0_v1.2.15
> qBittorrent: bump to v4.4.0

- target/linux/x86/patches-5.10/993-bnx2x_warpcore_8727_2_5g_sgmii_txfault.patch
bnx2x 2.5G SGMII patch for BCM5771x/578xx 10/20-Gigabit NIC
> Add bnx2x 2.5G SGMII patch

- target/linux/ipq60xx/patches-5.10/999-add-ipq6018-dts.patch
> remove an already patched modification in target/linux/ipq60xx/patches-5.10/999-add-ipq6018-dts.patch

- package/kernel/linux/modules/video.mk
fix missing depends for multimedia-input
> fix missing depends for multimedia-input

- package/kernel/linux/modules/netdevices.mk
> kernel:fix kmod-phylink missing depends

- package/kernel/linux/modules/usb.mk
> kernel:fix kmod-usb-net-smsc95xx deppends

- package/lean/luci-app-ipsec-server/luasrc/view/ipsec-server/index.htm
>  luci-app-ipsec-server: adapter luci-theme-openwrt-2020 theme

- package/lean/r8152/patches/010-compat-skb_mark_not_on_list-was-backported-since-ker.patch
Reverts coolsnowwolf/lede#8455
> Revert "r8152: drop patch"

- package/lean/autocore/files/x86/index.htm
> 概览页面DHCP列表按IP地址排序

- package/network/services/hostapd/patches/0001-Sync-with-mac80211-next.git-include-uapi-linux-nl802.patch
- package/network/services/hostapd/patches/370-ap_sta_support.patch
- package/network/services/hostapd/patches/v2-1-5-bss-coloring-add-support-for-handling-collision-events-and-triggering-CCA.patch
- package/network/services/hostapd/patches/v2-2-5-bss_coloring-add-the-code-required-to-generate-the-CCA-IE.patch
- package/network/services/hostapd/patches/v2-3-5-bss-coloring-disable-BSS-color-during-CCA.patch
- package/network/services/hostapd/patches/v2-4-5-bss-coloring-add-the-switch_color-handler-to-the-nl80211-driver.patch
- package/network/services/hostapd/patches/v2-5-5-bss-coloring-handle-the-collision-and-CCA-events-coming-from-the-kernel.patch
> hostapd: add BSS CCA support

- target/linux/ramips/dts/mt7621_hilink_hlk-7621a.dts
- target/linux/ramips/image/mt7621.mk
设计源文件：
https://github.com/cyijun/MT7621A-Router-Design
到OpenWrt的commit已经合并：
https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=eb00fb8f7153535512b2dad365e76a2bc0dfb6c1
> Add Support for HLK-7621 Router Designed By Me

- package/utils/busybox/patches/220-add_lock_util.patch
> Busybox: update patches

- package/qat/firmware/quickassist-c3xxx/Makefile
Fix Intel® QuickAssist Technology Driver download url
> Fix Intel QAT Driver download url

- package/qat/libs/openssl-qat/Makefile
> Update openssl-qat version to 0.6.12

- target/linux/generic/pending-5.15/768-net-dsa-mv88e6xxx-Request-assisted-learning-on-CPU-port.patch
- target/linux/mediatek/patches-5.15/500-gsw-rtl8367s-mt7622-support.patch
Signed-off-by: aakkll <94471752+aakkll@users.noreply.github.com>
> kernel: fix kernel5.15.45

- target/linux/rockchip/armv8/base-files/etc/init.d/fa-fancontrol
- target/linux/rockchip/armv8/base-files/etc/rc.d/S21fa-fancontrol
- target/linux/rockchip/armv8/base-files/usr/bin/cputemp.sh
- target/linux/rockchip/armv8/base-files/usr/bin/fa-fancontrol-direct.sh
- target/linux/rockchip/armv8/base-files/usr/bin/fa-fancontrol.sh
> rockchip: add fan control for r2s/r4s from friendlywrt

- package/lean/mt/drivers/mt7615d/files/lib/netifd/wireless/mt_dbdc.sh
- package/lean/mt/mtkiappd/Makefile
- package/lean/mt/mtkiappd/files/README
- package/lean/mt/mtkiappd/files/firewall.include
- package/lean/mt/mtkiappd/files/mtkiappd.defaults
- package/lean/mt/mtkiappd/files/mtkiappd.sh
- package/lean/mt/mtkiappd/src/Makefile
- package/lean/mt/mtkiappd/src/iappdefs.h
- package/lean/mt/mtkiappd/src/mt_iapp_util.c
- package/lean/mt/mtkiappd/src/rt_config.h
- package/lean/mt/mtkiappd/src/rt_typedef.h
- package/lean/mt/mtkiappd/src/rtmpiapp.c
- package/lean/mt/mtkiappd/src/rtmpiapp.h
如标题所示：
不知道80211w是否确切的支持，如不支持请大佬删除！
配合luci补丁[gh pr checkout 136](https://github.com/coolsnowwolf/luci/pull/136#issue-1279619920)！
Signed-off-by: nanchuci nanchuci023@gmail.com
> 增加mt7615_dbdc闭源驱动对80211k 80211v 80211r 80211w和wps的支持

- target/linux/ipq807x/patches-5.10/011-v5.11-PCI-dwc-Move-MSI-interrupt-setup-into-DWC-common-cod.patch
- target/linux/ipq807x/patches-5.10/012-v5.11-PCI-dwc-Rework-MSI-initialization.patch
- target/linux/ipq807x/patches-5.10/013-v5.11-PCI-dwc-Move-link-handling-into-common-code.patch
- target/linux/ipq807x/patches-5.10/014-v5.11-PCI-dwc-Move-dw_pcie_msi_init-into-core.patch
- target/linux/ipq807x/patches-5.10/115-phy-qcom-qmp-Add-IPQ8074-PCIe-Gen3-QMP-PHY-support.patch
- target/linux/ipq807x/patches-5.10/117-PCI-qcom-add-support-for-IPQ60xx-PCIe-controller.patch
- target/linux/ipq807x/patches-5.10/120-PCI-qcom-Add-IPQ8074-PCIe-Gen3-support.patch
- target/linux/ipq807x/patches-5.10/600-qca-nss-ecm-support-CORE.patch
- target/linux/ipq807x/patches-5.10/603-net-core-Flag-to-identify-ingress-shaping-done-for-e.patch
- target/linux/ipq807x/patches-5.10/604-net-core-Replace-nss-keyword-with-offload.patch
- target/linux/ipq807x/patches-5.10/720-net-phy-add-aqr-phys.patch
- target/linux/ipq807x/patches-5.10/722-net-phy-aquantia-enable-AQR112-and-AQR412.patch
- target/linux/ipq807x/patches-5.10/723-net-phy-aquantia-fix-system-side-protocol-mi.patch
- target/linux/ipq807x/patches-5.10/724-net-phy-aquantia-Add-AQR113-driver-support.patch
- target/linux/ipq807x/patches-5.10/725-net-phy-aquantia-add-PHY_IDs-for-AQR112-variants.patch
> kennel: ipq807x: refresh patches

- package/lean/igb-intel/Makefile
> igb-intel: mark conflict with kmod-igb

- package/lean/shortcut-fe/fast-classifier/src/fast-classifier.c
> Update fast-classifier.c fix kmod-fast-classifier compile error

- package/kernel/linux/modules/fs.mk
- package/kernel/linux/modules/netdevices.mk
- package/kernel/linux/modules/other.mk
- package/kernel/linux/modules/usb.mk
- package/kernel/linux/modules/video.mk
Signed-off-by: xiangfeidexiaohuo <jsjson@163.com>
> Fix modules in kernel 5.19

- target/linux/generic/hack-5.19/902-debloat_proc.patch
- target/linux/generic/hack-5.19/904-debloat_dma_buf.patch
- target/linux/generic/hack-5.19/952-add-net-conntrack-events-support-multiple-registrant.patch
- target/linux/generic/hack-5.19/953-net-patch-linux-kernel-to-support-shortcut-fe.patch
- target/linux/generic/pending-5.19/120-Fix-alloc_node_mem_map-with-ARCH_PFN_OFFSET-calcu.patch
- target/linux/generic/pending-5.19/670-ipv6-allow-rejecting-with-source-address-failed-policy.patch
- target/linux/rockchip/patches-5.19/0057-arm64-dts-rockchip-add-hardware-random-number-genera.patch
- target/linux/rockchip/patches-5.19/0061-arm64-dts-rockchip-rk3328-add-dfi-node.patch
- target/linux/rockchip/patches-5.19/0063-drv-net-phy-add-JLSemi-jl2xxx-driver.patch
- target/linux/rockchip/patches-5.19/0900-arm-boot-add-dts-files.patch
- target/linux/rockchip/patches-5.19/0903-crypto-rockchip-permit-to-pass-self-tests.patch
Signed-off-by: aakkll <94471752+aakkll@users.noreply.github.com>
> kernel: refresh 5.19 patch

- target/linux/rockchip/armv8/base-files/etc/board.d/02_network
> rockchip: fix r5s 避免每次刷机或者重启都会弹出网络新发现 by DHDAXCW

- target/linux/rockchip/patches-5.15/208-rockchip-rk3399-add-support-for-GuangMiao-G4C.patch
Signed-off-by: aakkll <94471752+aakkll@users.noreply.github.com>
> kernel: refresh 5.15 patch

- target/linux/rockchip/armv8/base-files/etc/hotplug.d/net/40-net-smp-affinity
> rockchip:supplement r5s missing symbols

- target/linux/rockchip/files-5.19/arch/arm64/boot/dts/rockchip/rk3568-rock-3a.dts
- target/linux/rockchip/files/arch/arm64/boot/dts/rockchip/rk3568-rock-3a.dts
> rockchip: add Radxa ROCK3 Model A dummy dts for build

- package/lean/r8101/Makefile
> r8101: fix PKG_SOURCE_URL

- target/linux/generic/pending-5.15/851-0006-Revert-PCI-aardvark-Fix-initialization-with-old-Marv.patch
> kernel: 5.15: fix bug in patch format

- target/linux/x86/base-files/etc/board.d/02_network
> x86: add CheShi R69S ( Cnction N4500 ) support

- target/linux/rockchip/files-5.15/arch/arm64/boot/dts/rockchip/rk3568-nanopi-r5s.dts
- target/linux/rockchip/image/armv8.mk
add some names to dts, it will take effect
r5s nvme
To increase the speed, you need to open the pcie3.0 2 line to take effect
> rockchip:fix r5s led not bright and add nvme driver

- tools/cmake/Makefile
Release Notes:
https://www.kitware.com/cmake-3-24-2-is-available-for-download/
Signed-off-by: Nick Hainke <vincent@systemli.org>
> tools/cmake: update to 3.24.2

- package/base-files/files/bin/config_generate
* [x ] 我知道
默认开启NTP服务，便于局域网内老旧设备可以通过网关纯IP获取NTP服务
> system.ntp.enable_server default

- package/network/utils/umbim/Makefile
Fixes: https://github.com/coolsnowwolf/lede/issues/10126
> Fixes package/network/utils/umbim failed to build

- README.md
---
今日编译时发现大量警告：
`Can't exec "aria2c": No such file or directory at /lede/lede/scripts/download.pl line 90.`
查阅 commit 历史，发现 [`320adae` 加入了 `aria2` 支持](https://github.com/coolsnowwolf/lede/commit/320adae6f63a7fdec770440e47f33821cf34128a)。
`aria2` 在速度和稳定性上应该远胜 `curl`，手动安装后体验不错，故开此 pull request.
> Add `aria2` to deps

- tools/meson/Makefile
This reverts commit 5fcaadd8ce51e46a32577f7bda023930a5a217c8.
fix: #10213 
> Revert "tools/meson: update to 0.63.1"

- .github/workflows/openwrt-ci.yml
> github workflows: avoid skipping

- target/linux/rockchip/Makefile
Signed-off-by: liulinhui36 <liulinhui36@gmail.com>
> rockchip: remove redundant symbols for Makefile

- target/linux/rockchip/Makefile
Signed-off-by: Linhui Liu <liulinhui36@gmail.com>
> rockchip: fix Makefile format

- scripts/download.pl
Signed-off-by: Linhui Liu <liulinhui36@gmail.com>
> download.pl: use more Chinese mirrors

- package/lean/autosamba/files/20-smb
- samba4 config file path: /etc/config/samba4
- samba4 config name: samba4
- samba4 init path: /etc/init.d/samba4
- fix: coolsnowwolf/lede#10314
> package/autosamba: compatible with samba4

- feeds.conf.default
Signed-off-by: Jianhui Zhao <zhaojh329@gmail.com>
> feed: add a new feed for oui

- package/kernel/linux/modules/netsupport.mk
> netsupport.mk: add MultiPath TCP modules

- package/system/procd/patches/001-procd_ujail_static_binary_fix.patch
> procd: ujail static-linked binary

- package/system/procd/Makefile
- package/system/procd/patches/001-procd_ujail_static_binary_fix.patch
> procd: ujail upgrade patch for latest version

- package/utils/busybox/files/sysntpd
> fix ntpd path problem

- tools/mpfr/Makefile
- tools/mpfr/patches/001-only_src.patch
Changes:
- Bug fixes
- Improved manual formatting
Refresh patches:
- 001-only_src.patch
Signed-off-by: Nick Hainke <vincent@systemli.org>
> tools/mpfr: update to 4.1.1

- package/lean/r8101/Makefile
* Upstream removed this version
> package: Revert r8101 update to 1.038.02

- package/lean/automount/Makefile
> automount: add kmod-fs-ntfs3

- package/kernel/mt76/patches/001-Revert-sync-with-upstream.patch
- package/kernel/mt76/patches/002-Revert-wifi-mt76-mt7921-introduce-chanctx-support.patch
- package/kernel/mt76/patches/003-Revert-changed-IEEE80211_MAX_AMPDU_BUF-defi.patch
- package/kernel/mt76/patches/020-fix-crash-in-chip-reset-fail.patch
- package/kernel/mt76/patches/090-backport-to-linux-5.19.patch
- package/kernel/mt76/patches/091-fix-linux-6.1-build.patch
Fixes: #10687 
Signed-off-by: Linhui Liu <liulinhui36@gmail.com>
> mt76: refresh patches

- package/lean/ddns-scripts_aliyun/update_aliyun_com.sh
> ddns_aliyun: fix subdomain

- package/boot/uboot-rockchip/Makefile
- package/boot/uboot-rockchip/patches/307-rockchip-rk3399-Add-support-for-Rocktech-MPC1903.patch
- target/linux/rockchip/files/arch/arm64/boot/dts/rockchip/rk3399-mpc1903.dts
- target/linux/rockchip/image/armv8.mk
- target/linux/rockchip/image/mpc1903.bootscript
- target/linux/rockchip/patches-5.15/212-rockchip-rk3399-add-support-for-Rocktech-MPC1903.patch
- target/linux/rockchip/patches-6.1/212-rockchip-rk3399-add-support-for-Rocktech-MPC1903.patch
> Add support for Rocktech MPC1903

- package/firmware/intel-microcode/Makefile
> intel-microcode: update to 20221108

- package/network/utils/uqmi/Makefile
使用gcc11会导致建构失败，解决方法：改回去
ERROR: package/network/utils/uqmi failed to build.
> uqmi:fix build failure

- target/linux/ramips/dts/mt7620a_hiwifi_r33.dts
- target/linux/ramips/mt7620/base-files/etc/board.d/01_leds
Thanks to developer yousong for finding and solving problems
修复之前提交设备遗留问题
1、内存偏移
2、LED 规则修改
> Fix: MT7620-R33 DST: Memory Offset and Led rule

- target/linux/rockchip/armv8/base-files/etc/board.d/02_network
- target/linux/rockchip/image/armv8.mk
> rockchip:fix build failure and change network for MPC1903

- package/kernel/mac80211/Makefile
- package/kernel/mt76/patches/091-fix-linux-6.1-build.patch
> mt76x2: fix for 6.1

- .github/workflows/openwrt-ci.yml
> Openwrt-CI: small cleanup

- package/boot/uboot-rockchip/Makefile
- package/boot/uboot-rockchip/patches/316-uboot-add-NanoPi-R5C-board.patch
- target/linux/rockchip/armv8/base-files/etc/board.d/01_leds
- target/linux/rockchip/armv8/base-files/etc/board.d/02_network
- target/linux/rockchip/armv8/base-files/etc/hotplug.d/net/40-net-smp-affinity
- target/linux/rockchip/files/arch/arm64/boot/dts/rockchip/rk3568-nanopi-r5c.dts
- target/linux/rockchip/image/armv8.mk
- target/linux/rockchip/image/nanopi-r5c.bootscript
- target/linux/rockchip/patches-5.15/210-rockchip-rk356x-add-support-for-new-boards.patch
- target/linux/rockchip/patches-6.1/210-rockchip-rk356x-add-support-for-new-boards.patch
> add NanoPi R5C board

- .github/workflows/openwrt-ci.yml
dpkg: error processing package grub-efi-amd64-signed (--configure)
https://github.com/coolsnowwolf/lede/actions/runs/4276705033/jobs/7444992777#step:2:1554
> fix  CI issues

- target/linux/rockchip/armv8/base-files/etc/board.d/02_network
- target/linux/rockchip/files/arch/arm64/boot/dts/rockchip/rk3399-mpc1903.dts
- target/linux/rockchip/image/armv8.mk
> Add GSM module support for MPC1903

- package/firmware/linux-firmware/intel.mk
* Adapt: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/?id=494389cbc3b3f080bbe4ee921f1b08eae3b6fdbf
* https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/?id=3435843535f747e5d68c7b084d234254dcd74f55
> linux-firmware: Fix ax201 firmware version

- package/firmware/linux-firmware/intel.mk
* [ * ] 我知道
test on N5000 / N5030
> x86: add missing glk_guc_70.1.1.bin for intel 10th gpu

- target/linux/ramips/dts/mt7620a_hiwifi_r33.dts
一定程度上缓解R33 2.4G WiFi信号弱的问题，感谢 @yousong
> fix: R33 WIFI Weak signal

- target/linux/generic/hack-5.10/999-add-fibocom-id-and-zeropacket.patch
- target/linux/generic/hack-5.15/999-add-fibocom-id-and-zeropacket.patch
- target/linux/generic/hack-5.4/999-add-fibocom-id-and-zeropacket.patch
- target/linux/generic/hack-6.1/999-add-fibocom-id-and-zeropacket.patch
* 按照广和通手册加入，在5.4/5.10/5.15/6.1四个内核都已经编译过一次。
> add-fibocom-id-and-usbzeropacket

- package/lean/shortcut-fe/fast-classifier/src/fast-classifier.c
- package/lean/shortcut-fe/shortcut-fe/src/sfe_cm.c
Synchronous official master branch build
> shortcut-fe: fix build

- package/firmware/intel-microcode/Makefile
> Fix intel-firmware file name

- package/kernel/linux/modules/netdevices.mk
> Update netdevices.mk to fix depends

- target/linux/ramips/dts/mt7620a_bolt_bl201.dts
- target/linux/ramips/image/mt7620.mk
- target/linux/ramips/mt7620/base-files/etc/board.d/01_leds
- target/linux/ramips/mt7620/base-files/etc/board.d/02_network
Changes: 
1. add bolt_bl201 LED aliases
2. fix bolt_bl201 restart key gpio
3. make bolt_bl201 bootloader read-only
4. add bolt_bl201 partition settings
5. fix bolt_bl201 wrong gpio group
6. update bolt_bl201 LED and network switch settings
> update bolt_bl201 device tree, fix the gpio keys, etc.

- target/linux/ramips/mt7620/base-files/etc/board.d/02_network
To fix error in old devices version
> ramips: mt7620a bolt_bl201 revert back switch configuration

- package/kernel/linux/modules/netdevices.mk
> Update netdevices.mk to fix qlogic device support

- target/linux/realtek/files-5.4/drivers/net/dsa/rtl83xx/rtl838x.h
> Fix typo in rtl838x.h

- target/linux/sunxi/Makefile
sync with upstream commit.
https://github.com/openwrt/openwrt/commit/d05ac928f68f108f22ec36e5a24e7217f938becc
> sunxi: make use of 'rootfs-part' feature

- target/linux/ramips/dts/mt7628an_nradio_wt6285.dts
- target/linux/ramips/image/mt76x8.mk
- target/linux/ramips/mt76x8/base-files/etc/board.d/01_leds
- target/linux/ramips/mt76x8/base-files/etc/board.d/02_network
- target/linux/ramips/patches-5.4/0999-mt76x8-ec200a.patch
> Add support for NRadio WT6285 device

- config/Config-kernel.in
- package/kernel/linux/modules/netsupport.mk
> kernel: add MultiPath TCP module

- README.md
> add python3-setuptools

- target/linux/generic/files/drivers/bcma/fallback-sprom.c
- target/linux/generic/files/drivers/ssb/fallback-sprom.c
https://github.com/coolsnowwolf/lede/issues/11329
修复这里的问题
> add missing ssb and bcma

- README.md
- README_EN.md
- Sync'ed `README_EN.md` to the latest commit
- Optimise MarkDown & HTML styles.
[README_EN](https://github.com/KKtheGhost/lede/blob/doc/README_EN/README_EN.md)
> doc: Sync'ed README_EN.md to the latest commit

- .github/workflows/openwrt-ci.yml
> fix "E: Unable to locate package moby*"

- package/wwan/driver/fibocom_QMI_WWAN/src/qmi_wwan_f.c
> Fixed #11374

- package/lean/autocore/files/x86/index.htm
expr does not support floating point operations, added a bit of logitech for converting integers
> fix: cpu usage display

- package/qca/nss/qca-nss-clients-64/Makefile
- target/linux/ipq807x/patches-5.10/606-qca-nss-ecm-bonding-add-bond_get_id.patch
- target/linux/ipq807x/patches-5.10/607-qca-nss-ecm-Add-bridge-join-and-leave-netdev-cmds.patch
> Fix ipq807x qca-nss-ecm-bonding error

- package/boot/uboot-envtools/files/mediatek_filogic
- package/boot/uboot-mediatek/Makefile
- package/boot/uboot-mediatek/patches/436-add-glinet-mt6000.patch
- target/linux/mediatek/dts/mt7986a-glinet-gl-mt6000.dts
- target/linux/mediatek/filogic/base-files/etc/board.d/02_network
- target/linux/mediatek/filogic/base-files/etc/hotplug.d/ieee80211/11_fix_wifi_mac
- target/linux/mediatek/filogic/base-files/lib/upgrade/platform.sh
- target/linux/mediatek/image/filogic.mk
修复
1、lan口顺序
2、WiFi mac
3、web的固件升级
添加
1、uboot相关
> Improve gl-mt6000

- README.md
- README_JA.md
> docs: add Japanese readme

- package/kernel/linux/modules/usb.mk
- package/kernel/linux/modules/video.mk
> kernel: fixes usb-audio depends

- package/kernel/linux/modules/usb.mk
- package/kernel/linux/modules/video.mk
> kmod-media-core: fix kconfig error with kernel 6.1

- target/linux/x86/image/Makefile
https://github.com/coolsnowwolf/lede/issues/11805
> Revert 'x86: increase bios boot partition to 1 MiB (#11741)'

- package/firmware/linux-firmware/marvell.mk
Add support for Marvell 88W8897 SDIO
> Add support for Marvell 88W8897 SDIO

- target/linux/mediatek/filogic/base-files/lib/upgrade/platform.sh
- 禁止有关 "GitHub Actions" 的提交
- 禁止使用 users.noreply.github.com 提交
> mediatek: filogic: Increase free disk space for Asus routers AX4200

- package/network/ipv6/ipip6/Makefile
- package/network/ipv6/ipip6/files/ipip6.sh
Add IPIP6(RFC2473) support.
[coolsnowwolf/luci#271](https://github.com/coolsnowwolf/luci/pull/271)
> ipip6: add ipip6 support

- target/linux/ramips/mt7621/base-files/lib/upgrade/platform.sh
fix zte e8820s nandupgrade & led
> ramips: improve zte e8820s support

- package/lean/luci-app-leigod-acc/Makefile
- package/lean/luci-app-leigod-acc/po/zh-cn/leigo-acc.po
新增 conntrack & conntrackd 组件，用于连接性检测
>  leigod-acc: fix typo and add conntrack depends

- package/lean/leigod-acc/Makefile
原：
```im
路由器加速游戏失败和绑定不了的问题，请重启路由器就恢复正常。（10月25日10点50分已发布了雷神新版本插件，重启路由器就会更新。）
```
来源：雷神官方下载服务器
http://119.3.40.126/router_plugin/acc-gw.linux.$arch
> leigod-acc: update binary program

- package/libs/openssl/Makefile
> openssl: make compatible with v1.1 pkg

- package/boot/uboot-envtools/files/ath79
- target/linux/ath79/dts/qca9563_alibaba_ap121-db.dts
- target/linux/ath79/generic/base-files/etc/board.d/02_network
- target/linux/ath79/generic/base-files/etc/hotplug.d/firmware/11-ath10k-caldata
- target/linux/ath79/image/generic.mk
为国内breed用户适配，启动位置0x50000
https://www.right.com.cn/forum/thread-8421962-1-1.html
> ath79: add support for Alibaba AP121-DB

- target/linux/bcm53xx/patches-6.6/180-usb-xhci-add-support-for-performing-fake-doorbell.patch
Fixes: https://github.com/coolsnowwolf/lede/issues/13608
> bcm53xx: fix build with kernel 6.6.97
