- target/linux/ar71xx/base-files/etc/hotplug.d/firmware/11-ath10k-caldata
- target/linux/ar71xx/base-files/etc/hotplug.d/ieee80211/10_fix_wifi_mac
- target/linux/ar71xx/files/arch/mips/ath79/mach-tl-wdr6500-v6.c
- target/linux/ar71xx/image/tp-link.mk
由于tl-wdr6500 v6和tl-wdr6500 v2分区结构相异，直接用v2的代码编译出来的固件无法正常工作。
官方固件v6的art信息位于0x1c000(2.4G), 0x1d000(5G)处，mac位于0x1b80d，而v2的art位于最后64kb，0x7f1000(2.4G)，0x7f5000(5G)处，mac位于0xfc00。要对代码和art分区进行修改才能正常工作。
第一次刷固件，先将0x1b000开始的64kb复制到flash最后64kb，防止art被固件覆盖。
usb转ttl线进uboot命令行，运行以下命令改art分区
erase 0x9f7f0000 +0x10000
cp.b 0x80060000 0x9f01b000 0x10000
cp.b 0x9f7f0000 0x80060000 0x10000
之后ttl刷入v2的breed(v6没有专用的breed...)，进breed刷固件。
> 修复tl-wdr6500 v6 无线

- package/lean/luci-app-aliddns/root/usr/sbin/aliddns
add urlencode for $aliddns_name,fix the aliddns  that can't add universal parse * or primary domain name @
the current_ip use "query_recordid" instead of "nslookup" and add query_result to replicate "query_recordid"
> fix the aliddns that can't add * or @

- package/lean/luci-app-pptp-server/root/etc/pptpd.include
Every time restart firewall, pptpd.include will be executed. Thus two ppp policies will be added to forwarding_rule chain, resulting a very long firewall table.
Modified to delete old policies before add new ones.
P.S. according to [wiki](https://wiki.openwrt.org/doc/howto/vpn.server.pptpd) , ppp+ policies will also allow data from other ppp interfaces, including pppoe. Thus if you are using ppp (PPPoE or similar) in wan(that's what in my case), this configuration is insecure. However someone made it like [this](https://datahunter.org/openwrt_pptp).
> Fix too much ppp policies in forwarding_rule chain

- package/lean/luci-app-sfe/root/etc/init.d/sfe
> fixed exists /dev/sfe_ipv6

- include/target.mk
`kmod-nft-offload` is only needed for `nftables`, OpenWrt's firewall is currently using `iptables`
> Remove kmod-nft-offload from default packages

- package/lean/luci-app-ssr-plus/Makefile
修复po2lmo路径错误，只测试了K3[编译环境](https://gl.tossp.com:1443/zh/lede-k3/-/jobs/6759)
```
install -d -m0755 /builds/zh/lede-k3/build_dir/target-arm_cortex-a9_musl_eabi/luci-app-ssr-plus-1/.pkgdir/luci-app-ssr-plus/usr/lib/lua/luci/i18n
/builds/zh/lede-k3/build_dir/target-arm_cortex-a9_musl_eabi/luci-base/po2lmo ./po/zh-cn/ssr-plus.po /builds/zh/lede-k3/build_dir/target-arm_cortex-a9_musl_eabi/luci-app-ssr-plus-1/.pkgdir/luci-app-ssr-plus/usr/lib/lua/luci/i18n/ssr-plus.zh-cn.lmo
bash: /builds/zh/lede-k3/build_dir/target-arm_cortex-a9_musl_eabi/luci-base/po2lmo: No such file or directory
make[3]: *** [/builds/zh/lede-k3/build_dir/target-arm_cortex-a9_musl_eabi/luci-app-ssr-plus-1/.pkgdir/luci-app-ssr-plus.installed] Error 127
make[3]: Leaving directory …
```
> fix  po2lmo path error

- package/lean/luci-app-vlmcsd/luasrc/controller/vlmcsd.lua
- package/lean/luci-app-vlmcsd/po/zh-cn/vlmcsd.zh-cn.po
- package/lean/luci-app-vlmcsd/root/etc/init.d/vlmcsd
- package/lean/luci-app-vlmcsd/root/etc/uci-defaults/luci-app-vlmcsd
修复”自动激活局域网客户端“不能关闭的问题
使用 pid 文件
禁止默认外网访问，有需要的自行开放端口
> vlmcsd 使用自带的 uci 配置，不修改 /etc/dnsmasq.conf

- target/linux/ramips/base-files/etc/board.d/01_leds
- target/linux/ramips/base-files/etc/board.d/02_network
- target/linux/ramips/dts/GHL-R-001.dts
- target/linux/ramips/image/mt7621.mk
Specs
SoC: MT7621AT
RAM: 512MiB
Flash: 32MiB MX25L25635F SPI NOR
2.4G: MT7603EN
5G: MT7612EN
Ethernet: 4x GE ports (1x WAN, 3x LAN) with link status LEDs
USB 3.0
LEDs: POWER, 5G WIFI, 2.4G WIFI, USB, Internet.
The last two ones are controlled by GPIO
UART: There are 2 UARTs (UARTLITE1/ttyS0 and UARTLITE3/ttyS1) on board.
UARTLITE1 is close to LEDs, and UARTLITE3 is close to flash chip.
The stock u-boot uses UARTLITE1 by default. Baud rate is 57600
Flash instruction
1. telnet 192.168.9.1 2317, username is "root" and password is "admin"
One can alternatively use UART to log in
2. Put OpenWrt firmware in a FAT32 USB drive, and connect it to the router
One can alternatively download the firmware via wget through Internet
3. mtd write /path/to/openwrt.bin firmware
4. reboot
Signed-off-by: Deng …
> ramips: add support for GeHua GHL-R-001

- target/linux/ramips/image/mt7621.mk
> PBR-M1固件大小不正确

- target/linux/mvebu/patches-4.14/403-net-mvneta-convert-to-phylink.patch
解决mvebu编译失败的问题
引用自：https://github.com/openwrt/openwrt/commit/1e3800df1808b4a5a977c3a9651958611df51c83
err_free_stats has been deprecated. Replace with err_netdev.
> mvebu: fixes commit

- package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.sh
优化分组和节点的唯一标识方法，大体的规则是:
1. 对于组: 使用订阅地址的hash值作为分组id
2. 对于节点: 使用订阅节点的所有值的hash值作为节点id
该改进解决了以下问题:
1. 某些订阅服务没有返回分组信息（比如v2ray）的时候，默认分组为default，从而导致分组失败的时候将其他订阅服务的节点一并进行判断的问题。
2. 对于同组内的节点，可能存在server相同而端口不同或者局部参数不同的情况，单纯判断server会导致同server节点被覆盖的问题。
3. 修正非v2ray类型的订阅却保存了v2ray订阅信息的问题
> luci-ssr-plus: optimize subscribe group and node identity method

- target/linux/ramips/base-files/etc/board.d/02_network
- target/linux/ramips/dts/ADSLR-G7.dts
- target/linux/ramips/image/mt7621.mk
SoC: MT7621AT
RAM: 256MB
Flash: 16M SPI
Ethernet: 5x GE ports
WiFi: 2.4G: MT7615N
5G: MT7615N
Flash instruction:
1.Modify the file to linux.bin
2.Set up FTP service
3.Computer settings fixed IP: 192.168.179.50 255.255.255.0
4.Turn on the power and press and hold the reset button until the indicator light is on for about 5 seconds.
More detailed information: https://www.right.com.cn/forum/thread-481788-1-1.html
The machine lights up the LED light normally, the switch is normal, the WIFI is normal, and the upgrade is normal.
> ramips: add support for ADSLR G7

- package/lean/luci-app-dnspod/files/dnspod.sh
- package/lean/luci-app-dnspod/files/root/etc/config/dnspod
- package/lean/luci-app-dnspod/files/root/etc/init.d/dnspod
- package/lean/luci-app-dnspod/files/root/usr/lib/lua/luci/model/cbi/dnspod.lua
* 增加了 dnspod 目前 token 验证方式的支持
* ***只支持一个子域名***
* 支持设置更新频率
* 日志输出在 `/tmp/dnspod.log`
* 修复脚本的bug
* `*`域名需要写作`\*`，否则通过 uci 拿到的参数就是目录下的文件
###日志示例
```bash
2019-09-01 16:19:29: Start in Service mode, check in every 60 seconds
2019-09-01 16:19:29: domain: xxxxx.me, sub_domain: *
2019-09-01 16:19:30: WAN IP: xxx.xx.xx.52
2019-09-01 16:19:30: old ip: [], new ip: [xxx.xx.xx.52]
2019-09-01 16:19:30: Change record: *.xxxxx.me from xxx.xx.xx.52 to xxx.xx.xx.52
2019-09-01 16:19:31: response: Action completed successful
2019-09-01 16:20:31: old ip: [xxx.xx.xx.52], new ip: [xxx.xx.xx.52]
2019-09-01 16:21:32: old ip: [xxx.xx.xx.52], new ip: [xxx.xx.xx.52]
2019-09-01 16:22:32: old ip: [xxx.xx.xx.52], new ip: [xxx.xx.xx.52]
2019-09-01 16:23:32: old ip: [xxx.xx.xx.52], new ip: [xxx.xx.xx.52]
2019-09-01 …
```
> support dnspod api by token, add wait second config

- package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.sh
${uci_set}type为服务器节点类型，固定为v2ray，不应该取ssr_security字段。
> 修正v2ray订阅更新问题

- package/lean/luci-app-ssr-plus/root/usr/bin/ssr-switch
针对如下场景进行优化
1、ssr-plus仅仅设置了一个服务器节点
2、该节点使用域名地址
3、域名对应的DNS解析ip修改了
问题原因：
在存在多节点情况下，select_proxy会挑选下一个节点重启ssr服务，但是在单一节点下由于不符合if [ "$ENABLE_SERVER" != nil ] 条件，导致并不调用switch_proxy来重启服务。但是域名对应的ip已经修改了，ssr服务本身是依赖ip参数启动的，ssr服务在重启依然停留在老的ip上。
调整方式：
这个修改调整为在每次检测网络失败的情况下，就算只有一个节点，也重启ssr服务，保证ssr服务有机会切换到域名新的ip地址。
此外假如因为ssr服务本身存在一些小概率bug，也可以通过重启ssr解决。
这种情况在付费的ssr服务中很常见，因为服务商往往只提供一个域名，假如因为服务器调整（比如某个服务器ip被和谐了），服务提供商都会重新给域名绑定新的服务器(或新IP)
> 优化ssr-switch单一节点下的ss重启

- target/linux/ipq40xx/base-files/etc/board.d/02_network
- target/linux/ipq40xx/base-files/etc/hotplug.d/firmware/11-ath10k-caldata
- target/linux/ipq40xx/files-4.14/arch/arm/boot/dts/qcom-ipq4019-hugo-ac1200.dts
- target/linux/ipq40xx/files-4.14/arch/arm/boot/dts/qcom-ipq4019-hugo-ac1200.dtsi
- target/linux/ipq40xx/image/Makefile
- target/linux/ipq40xx/patches-4.14/901-arm-boot-add-dts-files.patch
- target/linux/ipq40xx/patches-4.14/999-fix-m25p-shutdown.patch
Hugo AC1200 based on IPQ4019
Specifications:
SOC:	Qualcomm IPQ4019
DRAM:	256 MiB
FLASH:	32 MiB Macronix MX25L25635F
ETH:	Qualcomm QCA8075
WLAN:	5G + 2.4G
* 2T2R 2.4GHz
- QCA4019 hw1.0 (SoC)
* 2T2R 5 GHz
- QCA4019 hw1.0 (SoC)
> ipq40xx: add Hugo AC1200 support

- tools/mkimage/patches/060-remove_kernel_includes.patch
tools: mkimage: fix __u64 typedef conflict with new glibc
Including "sys/stat.h" from newer glibc will cause __u64 from linux uapi
header to be included, causing compilation failure for u-boot tools
USE_HOSTCC
Remove typedef for __u64 in include/compiler.h to fix the issue.  It should be
safe because as of u-boot-2018.03, no ref to __u64 is found under u-boot tools/
directory
Error message snippet follows
HOSTCC  tools/mkenvimage.o
In file included from /usr/include/asm-generic/types.h:7,
from /usr/include/asm/types.h:5,
from /usr/include/linux/types.h:5,
from /usr/include/linux/stat.h:5,
from /usr/include/bits/statx.h:30,
from /usr/include/sys/stat.h:446,
from tools/mkenvimage.c:21:
/usr/include/asm-generic/int-ll64.h:31:42: error: conflicting types for '__u64'
31 | __extension__ typedef …
> tools: mkimage: fix __u64 typedef conflict with new glibc

- package/lean/luci-app-familycloud/Makefile
- package/lean/luci-app-familycloud/root/etc/uci-defaults/familycloud
- package/lean/luci-app-familycloud/root/usr/share/familycloud/CloudDisk/config.json
库文件树下存在这个文件:\
`/package/lean/luci-app-familycloud/root/usr/share/familycloud/CloudDisk/config.json`\
这个文件其实是一个软链接, 但是在本地库所在的文件系统中并没有这个链接指向的`/tmp/config.json`.\
因而Git无法追踪这个文件, 但是在远程库中这个软链接文件本身又的确存在, 所以会导致GitHub提示如下错误:
这个错误可以在[这个页面](https://github.com/coolsnowwolf/lede/settings) (只有lean本人可以访问) `GitHub Pages`一栏看到.
解决方法: 删除这个问题文件并改为在软件包安装时创建该软链接.
> luci-app-familycloud: fix git tracking issue

- package/lean/luci-app-verysync/Makefile
- package/lean/verysync/Makefile
软件包`luci-app-verysync`并没有和`verysync`形成依赖关系, 而是使用预置的二进制文件. 
本次提交修复了这个问题.
> luci-app-verysync: fix wrong dependency

- target/linux/ipq40xx/base-files/etc/hotplug.d/firmware/11-ath10k-caldata
编译之后竞斗云没有2.4G，改正之后有了，不过2.4G灯不亮
> Fixed a problem with no 2.4G

- package/lean/luci-app-unblockmusic/Makefile
- package/lean/luci-app-unblockmusic/luasrc/model/cbi/unblockmusic.lua
- package/lean/luci-app-unblockmusic/root/etc/config/unblockmusic
- package/lean/luci-app-unblockmusic/root/etc/init.d/unblockmusic
解决苹果iOS和MacOS下无法使用的问题，同时也支持自定义转发域配置
参考https://github.com/nondanee/UnblockNeteaseMusic/issues/65
> UnblockNeteaseMusic增加转发音源配置

- package/lean/luci-theme-netgear/Makefile
- package/lean/luci-theme-netgear/root/etc/uci-defaults/30_luci-theme-netgear
每次重启都会自动应用`luci-theme-netgear`主题.
uci默认脚本执行错误 (退出代码`0`不合法) 造成不能正常自动删除导致每次重启都会执行脚本.
为什么`0`不合法, 这件事是个谜🤔. 脚本中所有语句都正常执行, 唯独不能正常退出. 解决这个问题也很简单, 只要在`exit 0`后面加个空格即可.
> luci-theme-netgear: fix self enabled

- .github/workflows/openwrt-ci.yml
[KFERMercer/OpenWrt-CI](https://github.com/KFERMercer/OpenWrt-CI)
感谢[P3TERX](https://github.com/P3TERX/Actions-OpenWrt)珠玉在前.
---
> ### 这个CI脚本和[P3TERX/Actions-OpenWrt](https://github.com/P3TERX/Actions-OpenWrt)的同样是云编译, 有什么不同?
这个 CI 脚本可以帮助你在你的 OpenWrt 分支下构建当前库的Op固件, 无需上传配置文件, 不依赖外挂配置脚本, 所以不会污染库文件树, 对Op开发者比较友好.
P3TERX/Actions-OpenWrt 的优势在于, 其可以独立于文件库存在, 可以快速搭建起可用的编译配置, 但是由于 OpenWrt make configure 自身机制的缘故, 生成的配置文件鲁棒性较差, 需要经常重新生成上传配置, 有形中加重了维护负担, 使得使用起来不是很`优雅`.
> ### 这个CI脚本适合哪些人?
- 伸手党 (大雕如果合并此pr, 访问者就可以每日下载到当日最新的完全基于大雕代码的原味固件)
- 正在维护自己的 OpenWrt 分支的大佬/初学者/玩家 (可以快速测试自己的代码)
- 没有精力维持一个专用编译机的佛系人士 (梯子到期了?)
> ### 开始吧.
在一切开始前, 你需要的是:
- GitHub 账号
- 申请使用 GitHub Actions
- 自己的OpenWrt分支(fork大雕源或者官方源)
- 识字能力以及基本电脑操作技能
- 脑子
你不需要的是:
- Linux技能
- 对编译失败的处置能力 (脚本由我维护)
- 梯子
> ### 现在暂停一下, 代码里需要留意一些东西... …
> Deploy OpwnWrt CI

- .github/workflows/openwrt-ci.yml
在此之前是上传整个`/bin/targets/`并打包, 导致下载的文件很大, 而绝大部分普通用户只需要固件本身. 
国内的网络环境并不适合下载GitHub上的大文件, 现在改成只上传编译好的完整固件, 体积缩小了好几倍. 并且匹配了其他平台的固件格式, 为以后可能加进去的多平台编译做准备. 
- 6个小时完全可以同时编译三个平台, 大雕觉得有必要部署多平台编译吗?
- CI文件里的注释部分太过冗长, 对程序实际运行又没什么用, 而且可能会对不懂代码的小白造成误导. 现在已经有了针对性的教程, 这些又臭又长的山炮注释大雕觉得要不要删掉?
> CI:  upload firmwares only

- package/lean/luci-app-ssr-plus/Makefile
- package/lean/openssl1.1/Makefile
根据 https://github.com/trojan-gfw/trojan/issues/127#issuecomment-555415538 改了下makefile，以便编译arm64平台。
> fixed compile trojan problems on arm64

- .github/workflows/openwrt-ci.yml
- 修复近期多发的因巨硬土豆集群发芽导致的流程失败
- 多线程编译失败时自动切换为单线程
- 由于难以匹配几亿种不同的固件格式和命名格式, 放弃只上传固件
- 删除定制模板部分以改进代码可读性
- 同步最近更改
> CI: rm useless apt sources

- package/lean/baidupcs-web/Makefile
- package/lean/luci-app-baidupcs-web/Makefile
- package/lean/luci-app-baidupcs-web/luasrc/controller/baidupcs-web.lua
- package/lean/luci-app-baidupcs-web/luasrc/model/cbi/baidupcs-web.lua
- package/lean/luci-app-baidupcs-web/luasrc/view/baidupcs-web/baidupcs-web_status.htm
- package/lean/luci-app-baidupcs-web/root/etc/config/baidupcs-web
- package/lean/luci-app-baidupcs-web/root/etc/init.d/baidupcs-web
之前的插件太简陋, 而且交互有问题.
- 加了些自定义功能.
- 实时刷新运行状态, 开启时显示web按钮.
- 把baidupcs-web包名改了, 大小写混杂有些不规范 (没在暗示UnblockNeteaseMusic).
- 测试过了, 各项功能正常.
效果图:
---
> luci-app-baidupcs-web: refactoring

- target/linux/ipq40xx/base-files/etc/hotplug.d/firmware/11-ath10k-caldata
- target/linux/ipq40xx/files-4.14/arch/arm/boot/dts/qcom-ipq4019-r619ac.dtsi
- target/linux/ipq40xx/files-4.19/arch/arm/boot/dts/qcom-ipq4019-r619ac.dtsi
- target/linux/ipq40xx/patches-4.14/854-add-sdhci-reset-implementation.patch
- target/linux/ipq40xx/patches-4.19/854-add-sdhci-reset-implementation.patch
懒得重新发pr了，写点说明。
dts：删掉sd的gpio后，拔出sd卡后2.4G灯会恢复亮起。
4.19的漏了pcie0部分补上。
这个sd reset的系统日志很烦，没插上sd的话，有的人没有这些日志，有的人一直会有这个出现，我的机子是有时会有。
谷歌查了下引入一个patch：https://patchwork.kernel.org/patch/9449851
现在插上sd卡也不会有上图的日志了。
> ipq40xx: update r619ac source code

- package/lean/luci-app-v2ray-server/luasrc/model/cbi/v2ray_server/api/genv2rayconfig.lua
- package/lean/luci-app-v2ray-server/luasrc/model/cbi/v2ray_server/config.lua
- package/lean/luci-app-v2ray-server/po/zh-cn/v2ray_server.po
V2ray服务端：
1.增加http代理支持
2.修复保存socks设置时用户名或密码为空，服务无法启动问题
3.增加缺失的翻译文字
> luci-app-v2ray-server: add http proxy support and fix bug

- package/system/fstools/patches/0010-fstools-block-make-extroot-mount-preparation-more-robust.patch
patch source: https://bugs.openwrt.org/index.php?do=details&task_id=2231
修复了非mtd存储无法正常挂载分区到/overlay的问题，这个patch我已经用了一个多月，正常稳定。本来extroot无法正常使用，添加后正常。上述网址里两个其他用户的反馈也是积极的。
> Fix extroot on non-MTD storage

- target/linux/mpc85xx/image/Makefile
> fix AeroHive AP-330

- package/lean/luci-app-ssr-plus/luasrc/controller/shadowsocksr.lua
- package/lean/luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/log.lua
- package/lean/luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/servers.lua
- package/lean/luci-app-ssr-plus/luasrc/view/shadowsocksr/server_list.htm
- package/lean/luci-app-ssr-plus/luasrc/view/shadowsocksr/socket.htm
- package/lean/luci-app-ssr-plus/luasrc/view/shadowsocksr/subscribe.htm
- package/lean/luci-app-ssr-plus/po/zh-cn/ssr-plus.po
- package/lean/luci-app-ssr-plus/root/etc/init.d/shadowsocksr
- package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua
* 重写订阅脚本，现在订阅解析速度非常快。
* 重写 ping 测试，之前一起并发上百个的情况不会出现了。
* 服务器列表增加 socket 连接测试，
* 优化日志获取的方式。
> luci-app-ssr-plus: optimize subscribe script and support ssd subscribe

- config/Config-images.in
- package/boot/kexec-tools/Makefile
- package/kernel/brcm2708-gpu-fw/Makefile
- package/kernel/broadcom-wl/Makefile
- package/system/procd/Makefile
- package/utils/mdadm/Makefile
- package/utils/mdadm/patches/100-cross_compile.patch
- package/utils/mdadm/patches/101-mdadm.h-Undefine-dprintf-before-redefining.patch
- package/utils/mdadm/patches/102-Add-missing-include-file-sys-sysmacros.h.patch
- package/utils/mdadm/patches/200-reduce_size.patch
- package/utils/nvram/Makefile
- package/utils/otrx/Makefile
- target/linux/generic/pending-4.14/681-NET-add-of_get_mac_address_mtd.patch
- target/linux/generic/pending-4.19/681-NET-add-of_get_mac_address_mtd.patch
- target/linux/generic/pending-4.9/681-NET-add-of_get_mac_address_mtd.patch
1. update mdadm to latest version, fix issue #2751
2. fix syntax errors exposed after kconfig update
3. revert add support for mtd-mac-address-ascii in device-tree, this change have problems in some platforms.
> kernel: bump to 4.9.208, 4.14.162, 4.19.93

- package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua
1. 新的订阅处理不能处理以空格分割节点的订阅内容，会触发以下错误
```
2020-01-13 16:20:29 发生错误, 正在恢复服务
[C]: ?
/usr/share/shadowsocksr/subscribe.lua:328: in main chunk
[C]: in function 'xpcall'
/usr/share/shadowsocksr/subscribe.lua:249: in function </usr/share/shadowsocksr/subscribe.lua:199>
/usr/share/shadowsocksr/subscribe.lua:125: in function 'processData'
/usr/share/shadowsocksr/subscribe.lua:29: in function 'split'
/usr/share/shadowsocksr/subscribe.lua:330: in function </usr/share/shadowsocksr/subscribe.lua:328>
2020-01-13 16:20:29 stack traceback:
2020-01-13 16:20:29 /usr/share/shadowsocksr/subscribe.lua:29: attempt to index local 'full' (a nil value)
```
2. 增加当订阅节点为空字符串时的处理。
未处理时导致的错误，[如图](https://user-images.githubusercontent.com/33367701/72317765-3eeee900-36d5-11ea-9c1b-86f48ebc855b.png)
#2721
> 支持以空格分割的订阅节点和空订阅节点的处理

- target/linux/ramips/mt76x8/target.mk
change default package from wpad-basic to wpad-openssl for mt76x8 to solve some problems during compiling.
> Solve a problem during compiling for mt76x8

- target/linux/x86/image/Makefile
生成的EFI镜像文件大小不是8k的倍数，在导入使用zfs文件系统的pve虚拟机中会出现问题，网上搜了一圈，需要重新pad镜像文件
root@pve:~/openwrt/1# qm importdisk 103 openwrt-x86-64-uefi-gpt-squashfs.img local-zfs
importing disk 'openwrt-x86-64-uefi-gpt-squashfs.img' to VM 103 ...
zfs error: cannot create 'rpool/data/vm-103-disk-3': volume size must be a multiple of volume block size
root@pve:~/openwrt/1# qm importdisk 103 openwrt-x86-64-uefi-gpt-squashfs.qcow2 local-zfs
importing disk 'openwrt-x86-64-uefi-gpt-squashfs.qcow2' to VM 103 ...
zfs error: cannot create 'rpool/data/vm-103-disk-3': volume size must be a multiple of volume block size
> x86 EFI image: fix EFI image file size

- package/lean/pdnsd-alt/patches/01-musl-compat.patch
Pdnsd generated segmentation fault  in debug mode(-g or debug=on), it calls pthread_getspecific() through DEBUG_MSG()
before pthread_key_create() has been called yet. This works on glibc and
uclibc but segfaults on musl because motion is relying on undefined
behaviour here.
References:
https://github.com/openwrt/packages/pull/1847
中文：
pdnsd 在debug模式(启动时加-g或conf里加debug=on)下一启动就直接coredump，用gdb发现最后调用函数是c库函数pthread_getspecific()，google了一圈，最后发现跟 https://github.com/openwrt/packages/pull/1847 是同一个问题，所以就把pthread_key_create提到了main函数的开头。
> fix segfault in debug mode

- package/lean/v2ray-core/Makefile
修复 v2ray-core 安装位置导致的编译失败 https://github.com/coolsnowwolf/lede/issues/2842
> v2ray-core: fix directory error

- package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua
- fix protoparam parse error in ssr subscribe
- in function split, when sep='/\\?', slen(sep)=3, but matched string
len is 2, fix by get end position of matched string
> luci-app-ssr-plus: fix ssr subscribe

- package/lean/qBittorrent/Makefile
I don't know how does this happened.
They passed the compilation after adding the `CONFIGURE_VARS`.
> qBittorrent: fix cannot find qmake

- package/lean/luci-app-ssr-plus/Makefile
- package/lean/luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
- package/lean/luci-app-ssr-plus/luasrc/view/shadowsocksr/ssrurl.htm
- package/lean/luci-app-ssr-plus/root/etc/init.d/shadowsocksr
- package/lean/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua
- package/lean/simple-obfs/Makefile
- package/lean/v2ray-plugin/Makefile
1. add simple-obfs package (simple-obfs same as obfs-local)([openwrt-simple-obfs](https://github.com/aa65535/openwrt-simple-obfs))
2. add v2ray-plugin package 
3. support plugin option of SSD subscribe
4. support import SIP002(shadowsocks) URI
Test on Raspberry Pi 4B
> luci-app-ssr-plus: support shadowsocks SIP003 plugin(Experimental)

- package/lean/npc/Makefile
> npc:bump to v0.26.2

- package/lean/v2ray-plugin/Makefile
缺失`go/host`编译依赖。
reference:
https://github.com/coolsnowwolf/lede/blob/master/package/lean/v2ray/Makefile#L55
> v2ray-plugin: fix host dependence missing

- tools/Makefile
missing ucl library dependence
reduce error probability on parallel build
> upx: fix dependence

- package/lean/npc/Makefile
fix:
mux 无锁队列同时进行pop可能导致死循环的问题
mux buffer pool 同一对象可能放入两次的问题
socks5 tcp连接未及时断开问题
udp 穿透逻辑不完善
change:
文件记录改为临时文件写入完毕后替换，避免文件被截断照成数据丢失 #412
service初始化失败后继续运行，但无法提供相关功能 #407
> npc: bump version to v0.26.3

- package/lean/luci-app-ssr-plus/luasrc/view/shadowsocksr/ssrurl.htm
Ref :https://github.com/trojan-gfw/trojan-url
在其基础上增加别名的支持
>trojan://password@remote_host:remote_port#url-encode-tag
close #3175
> luci-app-ssr-plus: fix trojan url import

- package/lean/luci-app-haproxy-tcp/luasrc/model/cbi/haproxy.lua
- package/lean/luci-app-haproxy-tcp/po/zh-cn/haproxy-tcp.po
- package/lean/luci-app-haproxy-tcp/root/etc/haproxy_init.sh
感谢老大鼓励,发个pr
修改了haproxy的配置,让"HAProxy- LuCI"可以配置后端时可以直接写域名,毕竟1.8版本的HAproxy原生支持直接在配置文件中写域名了.
> HAproxy has supported both domain and ip now

- tools/mkimage/Makefile
`http://mirror2.openwrt.org/source` is no longer updated. Replace it with `https://sources.openwrt.org`.
> update PKG_SOURCE_URL of mkimage

- package/lean/srelay/patches/001-compile.patch
Fix compile error on none linux os like macOS. 
```
In file included from init.c:36:0:
srelay.h:54:10: fatal error: sys/filio.h: No such file or directory
#include <sys/filio.h>
^~~~~~~~~~~~~
compilation terminated.
```
ref: https://www.right.com.cn/forum/thread-2764451-1-1.html
> srelay: fix build on none linux os

- package/kernel/linux/modules/hwmon.mk
- package/kernel/linux/modules/input.mk
- package/kernel/linux/modules/netdevices.mk
- package/kernel/linux/modules/sound.mk
- target/linux/ramips/base-files/lib/preinit/07_set_preinit_iface_ramips
- target/linux/ramips/dts/mt7621_iodata_wn-ax1167gr2.dts
- target/linux/ramips/dts/mt7621_iodata_wn-dx1167r.dts
- target/linux/ramips/dts/mt7621_iodata_wn-xx-xr.dtsi
- target/linux/ramips/dts/mt7628an_hiwifi_hc5761a.dts
- target/linux/ramips/files-4.14/drivers/net/ethernet/mediatek/gsw_mt7621.c
- target/linux/ramips/image/mt7621.mk
- target/linux/ramips/modules.mk
- target/linux/ramips/mt7621/base-files/etc/board.d/02_network
- target/linux/ramips/mt7621/base-files/lib/upgrade/iodata.sh
- target/linux/ramips/mt7621/base-files/lib/upgrade/platform.sh
- target/linux/ramips/mt76x8/base-files/etc/board.d/02_network
From issue #3242 
This commit sync ramips source code from openwrt master.
1. ramips: gsw_mt7621: disable PORT 5 MAC RX/TX flow control by default
2. ramips: allow to set switchdev by board in ramips_set_preinit_iface
3. kernel: fix typos in KernelPackage description
> ramips: sync source code

- package/lean/luci-app-dockerman/Makefile
- package/lean/luci-app-dockerman/luasrc/controller/dockerman.lua
抱歉, 上次在操作合并时直接打了 patch , 没仔细看原作者的具体代码更改, 导致 dockerman 页面错误出现在了 luci 的一级菜单里, 这可能会导致部分功能异常.
原作者这几次提交代码量巨大, 走马观花紧急抢救了一下, 现在应该正常了, 但是还没有经过测试, 请暂缓拉取.
> dockerman: fix luci entry display

- package/lean/luci-app-dockerman/luasrc/view/dockerman/cbi/xsimpleform.htm
合并上游提交时使用的批量替换脚本出现的小问题.
会导致镜像/容器的路径读取出现错误, 但应该不影响使用.
总之先放在这里
> dockerman: fix path issue

- package/lean/npc/Makefile
fix:
busybox与sysV环境下(openwrt)service库失效问题 #419
客户端使用http代理连接服务端问题
> npc: bump version to v0.26.4

- package/lean/npc/Makefile
* Improved compile duplicate download issues
* Change package download url
> NPC软件包下载在编译目录里，不在 dl 目录下，导致每次编译都重新下载，优化了文件命名和下载逻辑，有个问题要吐槽就是NPS发布的软件包文件名为啥不带版本号--O_O--
> npc: Improved compile duplicate download issues

- package/lean/luci-app-qbittorrent/root/etc/init.d/qbittorrent
> luci-app-qbittorrent: switch WebUI use UPnP to false

- package/lean/luci-app-autoreboot/root/etc/init.d/autoreboot
* [y] 我知道
你好，自动重启插件配置后没有立即生效，因为没有重启crontab服务导致
> fix autoreboot crontab not restart issue

- package/lean/npc/Makefile
add:
web 新增和编辑tunnel时增加使用场景提示实现 #410 提到的在hostlist 列表中点击在线状态可以直接访问这个穿透地址。感谢@hzgjq
添加版本打印，现在客户端和服务端均可以用-version参数打印版本了
添加客户端linux sdk文件打包
> npc:bump to 0.26.5

- package/lean/luci-app-ssr-plus/root/etc/init.d/shadowsocksr
5222 is the port that needed by Telegram(refer to https://core.telegram.org/mtproto/transports).
* [ x ] 我知道
> Make luci-app-ssr-plus' common mode able to use Telegram

- target/linux/generic/config-4.19
- target/linux/generic/hack-4.19/835-misc-owl_loader.patch
- target/linux/generic/pending-4.19/681-NET-add-of_get_mac_address_mtd.patch
1. misc-owl_loader是mac80211 v5.4的更改，故revert
2. 681-NET-add-of_get_mac_address_mtd.patch这个改动是支持`mtd-mac-ascii`的
> Revert "kernel: update 4.19 patch"

- package/lean/luci-app-ssr-plus/root/etc/init.d/shadowsocksr
当使用dns2socks时，选择的dns ip未添加到gfwlist 中，导致 dns 的 TCP 请求未通过代理转发
> luci-app-ssr-plus: fix dns2socks unavailable in gfw mode

- package/lean/automount/Makefile
> automount: avoid using uas for xhci-mtk

- package/lean/luci-app-ssr-plus/root/etc/init.d/shadowsocksr
- package/lean/luci-app-ssr-plus/root/usr/bin/ssr-rules
1. 当 netflix 服务器与主服务器相同时，应该只启动一个服务
2. 当 netflix 服务器与主服务器相同时，应该是 Netflix 分流服务也继续起作用，所以netflix域名和ip也应该继续添加进对应当dnsmasq和ipset中，但是相应的 redir port 应该和主服务器保持一致
3. 当 netflix 服务器与主服务器相同时，主服务器的 dns 和 netflix 服务的 dns 保持一致
> luci-app-ssr-plus: fix ssrp alwawys start two server

- package/libs/openssl/Makefile
- package/libs/openssl/patches/150-openssl.cnf-add-engines-conf.patch
- package/libs/openssl/patches/430-e_devcrypto-make-the-dev-crypto-engine-dynamic.patch
- package/libs/openssl/patches/500-e_devcrypto-default-to-not-use-digests-in-engine.patch
- package/libs/openssl/patches/510-e_devcrypto-ignore-error-when-closing-session.patch
This version includes bug and security fixes, including medium-severity
CVE-2019-1551, affecting RSA1024, RSA1536, DSA1024 & DH512 on x86_64.
Ref: openwrt/openwrt@dcef8d6
> openssl: update to 1.1.1e

- package/lean/luci-app-ssr-plus/Makefile
- package/lean/luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client.lua
- package/lean/luci-app-ssr-plus/root/etc/init.d/shadowsocksr
- package/lean/luci-app-ssr-plus/root/usr/bin/ssr-rules
为 netflix 分流服务增加停用模式
1. 不使用为 netflix 分流服务制定的相关规则
2. 不创建优先度很高的 nat 转发规则
3. 停用后与未增加 netflix 分流服务 时的状态保持一致
https://github.com/coolsnowwolf/lede/issues/3846#issuecomment-600980973
> luci-app-ssr-plus: add stop mode for netflix service

- package/kernel/linux/modules/iio.mk
This commit fix:
SPS30 particulate matter sensor (SPS30) [N/m/y/?] (NEW)
Run-tested-on: sunxi
> kernel: iio.mk: add missing kernel modules

- package/lean/npc/Makefile
fix:
web重新显示id #453 #461 #475
客户端首次添加时限速问题
mux计算长度重复赋值
服务端启动可能卡住的问题 #470
web中丢失的服务器ip项
> npc:bump to 0.26.6

- package/lean/luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/advanced.lua
- package/lean/luci-app-ssr-plus/root/etc/init.d/shadowsocksr
> luci-app-ssr-plus: add "same" mode for global socks5 server

- target/linux/ipq806x/base-files/etc/board.d/01_leds
- target/linux/ipq806x/base-files/lib/preinit/05_set_iface_mac_ipq806x.sh
- target/linux/ipq806x/files-4.14/arch/arm/boot/dts/qcom-ipq8064-mtfi-m520.dts
- target/linux/ipq806x/files-4.19/arch/arm/boot/dts/qcom-ipq8064-mtfi-m520.dts
- target/linux/ipq806x/image/Makefile
dmesg:
```
[   15.868426] lm75 0-0048: hwmon0: sensor 'lm75'
[   15.922580] Bluetooth: RFCOMM TTY layer initialized
[   15.922610] Bluetooth: RFCOMM socket layer initialized
[   15.926267] Bluetooth: RFCOMM ver 1.11
[   15.939812] rtc-pcf8563 0-0051: rtc core: registered rtc-pcf8563 as rtc0
```
> ipq806x: add i2c chips support for m520

- package/lean/luci-app-diskman/Makefile
partition: automatic FIX GPT PARTITION TABLE while create partition
当硬盘分区表为GPT时，硬盘容量与GPT分区表不对应（使用DD刷入gpt镜像，或者调整RAID分区大小后），自动修复分区表，修复上述情况下无法创建新分区的BUG
> luci-app-diskman: bump to 0.2.7

- package/lean/default-settings/files/zzz-default-settings
修复一处 distfeeds.conf 中将源地址的 http 替换成 https 可能引发的问题
如果 distfeeds.conf 的默认源就是 https，那将会引发更严重的后果
>  default-settings: fix string replace

- package/network/services/wireguard/Makefile
The newest official stable release.
* [X ] 我知道
> Bump wireguard to 1.0.20200401

- target/linux/ipq40xx/files-4.19/arch/arm/boot/dts/qcom-ipq4018-rt-ac58u.dts
- target/linux/ipq40xx/image/Makefile
RT-AC1300UHP has 256M memory and does not need to use ath10k-ct-smallbuffers.
> ipq40xx: fix support for Asus RT-AC1300UHP in 4.19

- package/libs/openssl/Makefile
Fixes NULL dereference in SSL_check_chain() for TLS 1.3, marked with
high severity, assigned CVE-2020-1967.
Ref: https://www.openssl.org/news/secadv/20200421.txt
Cherry-pick from openwrt/openwrt@3773ae1.
Also add mirror for mainland China user in this commit.
Signed-off-by: Petr Štetiar <ynezz@true.cz>
Signed-off-by: CN_SZTL <cnsztl@project-openwrt.eu.org>
> openssl: bump to 1.1.1g

- package/lean/luci-app-xlnetacc/root/etc/init.d/xlnetacc
迅雷快鸟openwrt的原作者项目：https://github.com/sensec/luci-app-xlnetacc/blob/master/files/root/etc/init.d/xlnetacc
原项目并没有采用kill -9的强杀方式
lean项目中迁移后的版本使用kill -9会导致不能正确注销，从而产生如下问题。
1、luci 快鸟web界面中切换从“启用”切换为“不启用”后，短期内无法停止提速效果（因为只是强杀xlnetacc.sh）
2、强杀将导致未注销就丢失了最近一次的sessionid（该变量为xlnetacc.sh的临时变量，强杀后就丢失了）。根据迅雷快鸟的官方规则，在前一次未注销的情况下，假如ip变化，那么新ip在24小时内将无法再次加速。
所以导致了在
a.重启路由
b.重启光猫
c.重新插拔光猫网线
d.web界面中手工停用快鸟后又进行了重新拨号
这些操作都将导致24小时内无法再次提速
原始项目中采用不加-9的kill能够安全发送信号导致注销操作
> 修改迅雷快鸟的注销问题

- package/lean/luci-app-openvpn-server/root/etc/uci-defaults/openvpn
Fix the bug that flashing firmware multiple times will cause repeated forwarding rules in firewall.
> luci-app-openvpn-server: avoid repeated forwarding rules

- package/network/services/ppp/files/ppp.sh
这边 interface 的数量获取可能出现问题。
`proto` 与 `'pppoe'` 之间有多个空格就没法匹配了，但是 uci config 语法可是允许的
> ppp: syncppp: fix grep's regex match

- package/lean/luci-app-rclone/Makefile
> add fuse-utils

- target/linux/ipq40xx/files-4.14/arch/arm/boot/dts/qcom-ipq4019-cm520-79f.dts
- target/linux/ipq40xx/files-4.19/arch/arm/boot/dts/qcom-ipq4019-cm520-79f.dts
- target/linux/ipq40xx/files-4.19/arch/arm/boot/dts/qcom-ipq4019-wpj419.dts
arch/arm/boot/dts/qcom-ipq4019-cm520-79f.dtb: Warning (reg_format):
"reg" property in /led_spi/led_gpio@0 has invalid length (4 bytes)
(#address-cells == 1, #size-cells == 1)
arch/arm/boot/dts/qcom-ipq4019-cm520-79f.dtb: Warning
(avoid_default_addr_size): Relying on default #size-cells value for
/led_spi/led_gpio@0
arch/arm/boot/dts/qcom-ipq4019-wpj419.dtb: Warning (reg_format):
/soc/spi@78b5000/flash0@0/partitions/partition@0:reg: property has
invalid length (8 bytes) (#size-cells == 1)
> ipq40xx: fix dtc warning

- package/lean/v2ray/Makefile
* [x ] 我知道
Please refer to https://github.com/v2fly/v2ray-core/releases for further updates instead of the V2Ray release page. Currently, update in V2Fly will be mirrored to the V2Ray release page but this will NOT continue indefinitely.
> Update v2ray-core to 4.23.4

- package/lean/luci-app-rclone/Makefile
- package/lean/luci-app-rclone/luasrc/model/cbi/rclone.lua
- package/lean/luci-app-rclone/po/templates/luci-app-rclone.pot
- package/lean/luci-app-rclone/po/zh_Hans/luci-app-rclone.po
- package/lean/luci-app-rclone/root/etc/init.d/rclone
- package/lean/rclone-ng/Makefile
- package/lean/rclone/patches/010-change-default-config-path.patch
- package/lean/rclone/patches/020-Notice-Access-Control-Allow-Origin-only-once.patch
* feat(rcloneng): an angular web application for rclone
* feat(backup): backup rclone configuration files during system upgrade
* :bug: luci-app-rclone: rclone service without bash
* :mute: filter out duplicate log
* :bug: luci-app-rclone: proxy work around
* :page_facing_up: add license header
* rclone: set /etc/rclone/rclone.conf as default config path
> Rclone-OpenWRT: upgrade

- target/linux/apm821xx/base-files/lib/upgrade/wdbook.sh
- target/linux/bcm27xx/base-files/lib/upgrade/platform.sh
This commit fix sysupgrade failed for bcm27xx, fix #4072, fix #4108 
Run-tested-by: @1715173329 Dalao on Raspberry Pi 3B
Run-tested-by: @EnnawYang Dalao on Raspberry Pi 4B
> treewide: adjust sysupgrade script

- package/network/services/ppp/files/ppp.sh
/etc/config/network这个文件里的写法可以各种各样，pppoe外面可以有引号，也可以没引号。proto与pppoe之间可以有不同类型、不同数量的空格（或Tab）。用uci show，可以把输出格式统一掉，省得考虑配置文件不同写法的区别。
> ppp: syncppp: further fix grep's regex match

- package/lean/rclone-ng/Makefile
* **manager:** Detail sidebar is not support in mobile
* **breadcurmb:** adapt to mobile view ([8546f49](https://github.com/ElonH/RcloneNg/commit/8546f49695886dfb8d128dcf0a52091695611b8e))
* **manager:** bind remote, path with url params ([0a7b48c](https://github.com/ElonH/RcloneNg/commit/0a7b48cb2ac57ce4021e419b0388f24153ec0456))
* **manager:** enable detail sidebar support ([74501dd](https://github.com/ElonH/RcloneNg/commit/74501dd2390de98e388dd17fa20357ed2504ae14))
* **manager:** show snipper when loading ([078675a](https://github.com/ElonH/RcloneNg/commit/078675a26a43a4aa96c26bf4c88545f6b818d10e))
* **manager:** show task button in bottom bar as default ([aa3fc66](https://github.com/ElonH/RcloneNg/commit/aa3fc660925e419ecaf87f4de5df038323a8eb85))
* …
> RcloneNg: bump version to 0.3.0

- package/lean/luci-app-nps/root/etc/init.d/nps
when uci configuration about nps has been changed, 
service doesn't restart itself
> luci-app-nps: monitor uci configuration changes

- package/lean/rclone-ng/Makefile
* **jobs-manager:** add animation on refresh button ([b7cc817](https://github.com/ElonH/RcloneNg/commit/b7cc817b2302b63415deb74617027078f862d05e))
* **list-view:** table index except first page ([b9d7fcf](https://github.com/ElonH/RcloneNg/commit/b9d7fcfb1ce884c5d7625e13c9a89835f68ffab8))
* **about:** show changelog ([9d7bea5](https://github.com/ElonH/RcloneNg/commit/9d7bea5f62a04560601ef37c371bcef8f1834182))
* **breadcurmb:** edit mode, double click to edit path. double again, back to normal ([60c57b4](https://github.com/ElonH/RcloneNg/commit/60c57b4368bea4b9cd9be39524e59a32a90014ff))
* **file.detail:** enable download file ([1f578f7](https://github.com/ElonH/RcloneNg/commit/1f578f7d54ca772eec85a5eab744d7e7de91a1ce))
* **file.detail:** show spaces usage …
> RcloneNg: bump version to 0.3.2

- package/lean/npc/Makefile
* bump version to [v0.26.8](https://github.com/ehang-io/nps/releases/tag/v0.26.8)
* change logs => [nps-0.26.8](https://github.com/ehang-io/nps/releases/tag/v0.26.8)
> npc: bump version to v0.26.8

- package/lean/r8168/Makefile
- target/linux/x86/Makefile
> r8168: Cancel default selection

- package/firmware/linux-firmware/intel.mk
Q：你知道这是`pull request`吗？
降级Intel无线网卡的固件版本以修复9260AC、3168AC无线网卡在4.19内核上iwlwifi驱动模块报固件加载失败的错误。
> linux-firmware: intel: Downgrade wifi firmware version for k4.19

- package/lean/UnblockNeteaseMusicGo/Makefile
更新版本到0.2.3，0.2.2版本解决了0.2.1版本pc客户端无法正常播放的bug。
> UnblockNeteaseMusicGo: bump version to 0.2.3

- package/lean/k3screenctrl/Makefile
解决target名称变化造成k3screenctrl无法选中编译问题
* [ x ] 我知道
> fix k3screenctrl depends

- package/lean/mt/drivers/mt7615d/config.in
- target/linux/ramips/dts/mt7621_dlink_dir-878-a1.dts
- target/linux/ramips/dts/mt7621_dlink_dir-882-a1.dts
- target/linux/ramips/dts/mt7621_dlink_dir.dtsi
- target/linux/ramips/dts/mt7621_motorola_mr2600.dts
- target/linux/ramips/image/mt7621.mk
- target/linux/ramips/mt7621/base-files/etc/board.d/01_leds
- target/linux/ramips/mt7621/base-files/etc/board.d/02_network
Added missing i2c groups and usb packages. Turn on the mt7615's leds support will not affect the machine without wifi led.
> ramips: improve support for dir878/882

- package/lean/luci-app-xlnetacc/root/etc/hotplug.d/iface/95-xlnetacc
出于以下两个原因，调整快鸟服务对于iface事件的处理策略：
1. 快鸟服务跟随系统启动，ifup事件使快鸟服务重复启动，出现2个快鸟脚本运行实例（原始脚本对于重复运行的判断失效，原因未知）。修改为restart后可保证快鸟服务启动前关闭正在运行的快鸟服务。
2. ifdown事件后不应该立即停止快鸟服务。iface下线后，快鸟脚本无法访问快鸟服务器进行账户注销。未正常注销的账户在外部ip变动后重新上线会触发812错误（12或24小时内无法提速）。因此ifdown事件触发后不停止快鸟服务，而是等iface重新上线（网络恢复正常）后重启服务，以此保证账户注销流程可以正常进行。
> xlnetacc: adjust iface event handling strategy

- package/lean/luci-app-openvpn-server/root/etc/uci-defaults/openvpn
修复防火墙端口号。用户如果设置自定义端口，例如1197，则升级固件时，需要uci查询用户设定的自定义端口号，然后打开防火墙端口。
> luci-app-openvpn-server: fix uci-defaults script

- package/lean/wget/Makefile
- package/lean/wget/patches/001-prefer_ipv4.patch
修改wget的ip协议优先级，默认使用ipv4进行连接：
在ipv6开启的情况下，可以保证wget配置文件时不会受到国内ipv6相关网络问题的影响
> 修改wget的ip协议优先级，默认使用ipv4进行连接

- package/lean/mt/luci-app-mtwifi/luasrc/controller/mtkwifi.lua
- package/lean/mt/luci-app-mtwifi/luasrc/view/admin_mtk/mtk_wifi_overview.htm
- target/linux/ramips/image/mt7621.mk
- target/linux/ramips/mt7621/base-files/etc/board.d/02_network
The apcli interface can be bound to either lan or wan, also fix #5180
> ramips/mtwifi: disable bind apcli interface to lan by default

- package/lean/mt/luci-app-mtwifi/Makefile
- package/lean/mt/luci-app-mtwifi/luasrc/controller/mtkwifi.lua
- package/lean/mt/luci-app-mtwifi/luasrc/view/admin_mtk/mtk_wifi_apcli.htm
- package/lean/mt/luci-app-mtwifi/root/usr/lib/lua/mtkwifi.lua
1. NEWIFI2D（新3路由）的5G，在使用`iwpriv`扫描周边无线热点时，所获取的`Security`有些不一样，表现主要有：‘WPAPSKWPA2PSK’显示为‘WPA1PSKWPA2PSK’，'OPEN/NONE'显示为'NONE‘，’OPEN/WEB‘显示为'WEB’，所以在scan_ap函数里处理Security信息时需要修改。
2. 添加bssid(ApCliBssid)选项（非强制使用），使用bssid，经过简单的测试，设置bssid可在多个相同cannel相同ssid中，连接目标路由，若在多个相同ssid的热点中，不存在指定bssid的热点，也会连接其它的热点。
> add check and format 'security' parameter in function  scan_app , and  function connect_ap add bssid option

- package/kernel/exfat/Makefile
- package/kernel/exfat/patches/010-fstream.patch
- package/kernel/linux/modules/fs.mk
- package/lean/automount/Makefile
In openwrt/openwrt@cd41234:
```
Namjae Jeon:
Hm... exfat in 5.4 kernel  that we did crap shit long time ago is
contributed by someone who we don't know.
This version is unstable and low quality code. We have been improving
it continuously.
and staging version exfat is removed from linux 5.7 kernel.
linux exfat oot  version is a backport of exfat in linux 5.7 kernel to
support lower version kernel, and it is a real.
You can see the patch history fro linux-exfat-oot.
this version support timezone and boot sector verification feature newly.
and better filesystem structure and much clean code quality that
reviewed by high profile kernel developers. and add many bug fixes.
And this version is officially maintained by me and kernel guys.
I would not recommend to use staging exfat version.
```
> linux: improve exFAT support

- package/lean/baidupcs-web/Makefile
在编译适用于 x86_generic (x86 平台 32 位) 设备固件的过程中，进行到下载 baidupcs-web 源码包这一步时出现 "文件不存在" 的错误，经核对为文件名问题，故修复~
> Fix baidupcs-web file name to fit i386 device

- .github/workflows/openwrt-ci.yml
- Asset release broken.
- Upgrade helloworld failure.
- Add multi-asset delivery support.
- Deliver buildinfo separately to evaluate the results simply.
- Deliver packages for quick testing and individual upgrades.
Since `GITHUB_TOKEN` will expire in one hour from the time the response was generated, you need [creating and storing encrypted secrets](https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets) to make `Upload release asset` work properly.
When previous step is completed, edit `YOURTOKEN` on line 106 to [name of the secrets](https://github.com/coolsnowwolf/lede/settings/secrets) that you just set.
After everything is done, the workflow will run normally.
---
> CI: multi-asset delivery support

- package/lean/coremark/Makefile
> Coremark: use the general way to detect 64bit or not.

- package/lean/verysync/Makefile
> Update to verysync 1.5.5 version

- package/lean/dns2socks/Makefile
换用GitHub源避免SF重定向，减少出错 #5367（出错一次，编译的时间不止x2 〒▽〒）。
> dns2sock: use github source instead

- package/libs/mbedtls/Makefile
- package/libs/mbedtls/patches/200-config.patch
Mbed TLS 2.16.7 is a maintenance release of the Mbed TLS 2.16 branch,
and provides bug fixes and minor enhancements. This release includes
fixes for security issues and the most severe one is described in more
detail in a security advisory:
https://tls.mbed.org/tech-updates/security-advisories/mbedtls-security-advisory-2020-07
* Fix a side channel vulnerability in modular exponentiation that could
reveal an RSA private key used in a secure enclave.
* Fix side channel in mbedtls_ecp_check_pub_priv() and
mbedtls_pk_parse_key() / mbedtls_pk_parse_keyfile() (when loading a private
key that didn't include the uncompressed public key), as well as
mbedtls_ecp_mul() / mbedtls_ecp_mul_restartable() when called with a NULL
f_rng argument. An attacker with access to precise enough timing and
memory …
> mbedtls: update to 2.16.7

- package/lean/rclone-ng/Makefile
ChangeLog：https://github.com/ElonH/RcloneNg/releases/tag/v0.5.0
> RcloneNg: bump version from 0.4.0 to 0.5.0

- package/kernel/mt76/Makefile
This update fix clients can not get correct IP address on mt76x2u
Then add disable_usb_sg module parameter to fix wireless devices crash when multi-devices connect to mt76x2u devices (Line 336)
Details: https://github.com/openwrt/mt76/issues/405#issuecomment-665737497
> Bump mt76 from 2020-08-22 to 2020-08-25

- package/lean/mt/drivers/mt_wifi/files/dbdc.l1profile.dat
- package/lean/mt/drivers/mt_wifi/files/mt7615.lua
设备：k2p
当前很多无线配置无法生效或者莫名其妙，例如配置CountryRegion、Channel或者AutoChannelSelect。
经过调查发现驱动在内部会对两个配置文件作合并。合并双配置文件的时候，如果编译开启了DEFAULT_5G_PROFILE，会假设l1profile的profile_path中第一个为5g配置，第二个为2g配置。依据此顺序从两个文件提取需要的设置。目前默认提供的l1profile的顺序是2g5g，导致很多配置项实际上采纳了对方配置文件的内容，产生了混乱。
修改后配置功能正常。
麻烦@AmadeusGhost 看看有没有什么问题。
应该也能解决这个评论提到的问题：
https://github.com/coolsnowwolf/lede/issues/5002#issuecomment-696463636
References:
- https://github.com/coolsnowwolf/lede/blob/099439f051a8b2393554eb26cec2df074f653fae/package/lean/mt/drivers/mt7615d/Makefile#L52
- https://github.com/coolsnowwolf/lede/blob/099439f051a8b2393554eb26cec2df074f653fae/package/lean/mt/drivers/mt7615d/src/mt_wifi/os/linux/rt_profile.c#L211
> mtwifi: mt7615: fix multi-profile merge

- target/linux/ramips/files/drivers/net/ethernet/ralink/mtk_debugfs.c
- target/linux/ramips/files/drivers/net/ethernet/ralink/mtk_eth_soc.c
- target/linux/ramips/files/drivers/net/ethernet/ralink/mtk_eth_soc.h
- target/linux/ramips/files/drivers/net/ethernet/ralink/mtk_offload.c
- target/linux/ramips/files/drivers/net/ethernet/ralink/mtk_offload.h
fix #5693, fix #5695 , fix #5696 , fix #5702
> ramips: ralink: rename some functions

- package/lean/mt/drivers/mt_wifi/files/mt7615.lua
进行有线桥接(Lan to Lan)时，常常会删除WAN接口，而当删除WAN接口后，变量wanif是空字符串，导致函数执行了return，从而导致函数没有对network.lan.ifname进行操作。
> 判断变量wanif是否不为空字符串

- package/lean/mt/drivers/mt7615d/config.in
- package/lean/mt/drivers/mt_wifi/config.in
- target/linux/ramips/dts/mt7621_jcg_y2.dts
- target/linux/ramips/image/mt7621.mk
- target/linux/ramips/mt7621/base-files/etc/board.d/01_leds
- target/linux/ramips/mt7621/base-files/etc/board.d/02_network
```
JCG Y2 is an AC1300M router
SoC: MediaTek MT7621AT
Flash: Winbond W25Q128JVSQ 16MiB
RAM: Nanya NT5CB128M16 256MiB
2.4GHz: MT7615D 2x2
5GHz: MT7615D 2x2
Ethernet: 1 x WAN and 4 x LAN
LED: POWER, INTERNET, 2.4G, 5G
USB: 1 x 3.0
Button: Reset
Flash instructions:
Upload factory.bin in stock firmware's upgrade page.
```
> ramips: add support for JCG Y2

- target/linux/ramips/mt7621/base-files/etc/board.d/02_network
#5863 少写了一个`|`符号，致使XY-C5设备不保留配置升级后网口不通，希望尽快合并，谢谢Lean大佬
> Add missing symbol

- target/linux/ipq40xx/patches-4.19/999-ipq40xx-unlock-cpu-frequency.patch
- target/linux/ipq40xx/patches-5.4/999-ipq40xx-unlock-cpu-frequency.patch
this patch improve cpu operating points to 896Mhz and match the clock-latency-ns values in the device tree  for those found inside the OEM device tree and kernel source code
超频到896Mhz，在星际宝盒（cm520）测试过，没有发现严重的不稳定、发热甚至冒烟等情况。
修改了clock-latency-ns（时钟切换延迟？）
> ipq40xx: improve cpu operating points

- package/lean/mt/drivers/mt7603e/Makefile
- package/lean/mt/drivers/mt7612e/Makefile
- package/lean/mt/drivers/mt7615d/Makefile
- package/lean/mt/drivers/mt_wifi/Makefile
- package/lean/mt/drivers/mt_wifi/files/91_load_wifi.sh
This reverts commit 653b7e432e5ce9c5b3721fe71e91b94861ad6408 due to
the combination of the mtwifi driver for mt603 and mt7615 will cause
some modules to fail to load normally, fix #6044 .
> Revert "mtwifi: enable autoload by default"

- package/libs/libnetfilter-conntrack/Makefile
OpenWrt同时把`libnetfilter-cthelper`, `libnetfilter-cttimeout`, `libnetfilter-log`, `libnetfilter-queue` 软件包移动至 `package` 仓库
>Nothing in base uses this. This will be moved to packages where it is
used.
>
>Signed-off-by: Rosen Penev <rosenp@gmail.com>
依旧同步以上软件包还是移动至 `coolsnowwolf/package` 仓库？
> libnetfilter_conntrack: Update V1.0.8

- package/lean/luci-app-syncdial/root/bin/genwancfg
创建多拨的时候，如果不选择绑定物理接口，不会自动生成跃点，这会导致mwan3去做负载的时候会出现掉线的问题
> hotfix: 修复多拨插件在不选择绑定wan口时不会自动生成跃点导致mawn3负载异常的问题

- target/linux/ramips/dts/mt7621.dtsi
- target/linux/ramips/dts/mt7621_glinet_gl-mt1300.dts
- target/linux/ramips/image/mt7621.mk
- target/linux/ramips/mt7621/base-files/etc/board.d/02_network
- target/linux/ramips/mt7621/base-files/etc/hotplug.d/ieee80211/10_fix_wifi_mac
openwrt官方支持了这个设备，我最近需要用这个机子做定制，就移到这个库了。
> 添加glinet-mt1300支持

- package/lean/luci-app-ssrserver-python/luasrc/controller/ssrs.lua
Running `ps` via luci.exec directly will cause no output
to compare as `ps` cannot detect the size of screen, adding
`-w` to solve this.
Fixes: 0e285c3037c3481d0c1b7a7c672a6ca5692ef35f ("add lean's package")
> luci-app-ssrserver-python: improve status check

- package/lean/uugamebooster/Makefile
- package/lean/uugamebooster/files/uugamebooster-update
- package/lean/uugamebooster/files/uugamebooster.init
> uugamebooster: add package

- target/linux/ramips/patches-5.4/102-mt7621-fix-cpu-clk-add-clkdev.patch
建议还是用 Breed 来超频更为合适
Fix: #6090 , Fix: #6166 , Fix: #6172
> Revert "ramips: mt7621 default overclock to 1000Mhz"

- package/network/services/openvpn/files/openvpn.options
In #6249 we have upgraded openvpn to 2.5.0 & Add xorpatch as a scramble option.
I have compiled your master branch sources for a AR71XX(MW4530R) target platform and tested the new openvpn binaries as server and tunnelblick as client with new scramble option enabled, it works.
We also need to add the 'scramble' option to the option file since the init script will read the config file and generate runtime configuration for the service.
> Add scramble option in options file.

- package/lean/UnblockNeteaseMusicGo/Makefile
- package/lean/v2ray-plugin/Makefile
> goproxy: replace unavailable goproxy.io

- package/lean/ddns-scripts_dnspod/update_dnspod_cn.sh
1. 当一个域名同时有A记录和AAAA记录时，在不需要更新时去更新，接口返回错误导致的脚本挂掉的问题，
接口报错信息：Error message:[记录已经存在，无需再次添加]
2. 文案明显错误修改
* [ x] 我知道
> 修复ddns(dnspod)同一个域名同时有ipv6和ipv4时更新失败的问题

- target/linux/ramips/dts/mt7620a_youku_yk1.dts
虽然估计 1202 年了没多少人用这个百兆 MTK 垃圾了，不过胜在便宜。之前自己编译了刷进去发现一重启就卡死（所有灯熄灭之后就没动静了必须插拔电源），查了一下是 32M 闪存的问题，退回 4.14 内核并给 M25P80.c 打了补丁之后凑合用，后来重温某个傻逼的弱智言论的时候无意中发现 32MB 闪存在 5.4 内核给 dts 加个 `broken-flash-reset` 的标志就好了，测试了一下确实，因为优酷路由宝确实原厂就是有 32MB 闪存（没硬改过）所以这个改动合并进来应该没啥大问题...？
> 优酷路由宝在5.4内核不能软重启

- package/lean/autocore/files/arm/index.htm
After the optimization, we only need to open two processes each time we get cpu usage instead of the previous five.
Also, the front-end will keep refreshing the page to get the cpu usage, so this patch may improve the front-end response time to a certain extent
Preformance Test (on NanoPi R2s, repeat 1000 times):
Since `top` is very time consuming, we stored the results of `top -n1` first
```
root@OpenWrt:~# top -n1 > /tmp/top_tmp
root@OpenWrt:~# cat /tmp/top_tmp 
Mem: 238756K used, 776236K free, 12600K shrd, 37472K buff, 85516K cached
CPU:   0% usr   0% sys   0% nic 100% idle   0% io   0% irq   0% sirq
Load average: 0.47 0.23 0.09 1/130 6202
PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
...
```
Now we test the script performance
old command
```
root@OpenWrt:~# cat cpu_usage_lean …
```
> optimize the performance of obtaining CPU usage

- package/lean/autocore/files/arm/sbin/cpuinfo
Preformance Test (on NanoPi R2s, repeat 1000 times):
old command:
```
root@OpenWrt:~# cat cpu_temp_lean 
#/bin/bash
for i in {0..1000}
do
temp="$(awk "BEGIN{printf (\"%.1f\n\",$(cat /sys/class/thermal/thermal_zone0/temp)/1000) }")°C"
done
root@OpenWrt:~# time bash ./cpu_temp_lean 
real    0m 9.20s
user    0m 3.29s
sys     0m 6.24s
```
new command:
```
root@OpenWrt:~# cat cpu_temp
#/bin/bash
for i in {0..1000}
do
temp="$(awk '{ printf("%.1f °C", $0 / 1000) }' /sys/class/thermal/thermal_zone0/temp)"
done
root@OpenWrt:~# time bash ./cpu_temp
real    0m 5.57s
user    0m 1.78s
sys     0m 3.97s
```
Signed-off-by: Chuck <fanck0605@qq.com>
> optimize the performance of obtaining CPU temperature

- target/linux/ramips/dts/mt7620a_youku_yk1.dts
This reverts commit 90bd81e0991046927634bf74830ec1c835d83e85.
The commit 90bd81e is a duplicate of b132179.
Fixes: #6388
Fixes: #6406
Signed-off-by: CN_SZTL <cnsztl@project-openwrt.eu.org>
> Revert "Add broken-flash-reset flag to Youku YK-L1"

- target/linux/rockchip/patches-5.4/108-rfc-mmc-core-set-initial-signal-voltage-on-power-off.patch
Some boards have SD card connectors where the power rail cannot be switched
off by the driver. If the card has not been power cycled, it may still be
using 1.8V signaling after a warm re-boot. Bootroms expecting 3.3V signaling
will fail to boot from a UHS card that continue to use 1.8V signaling.
Set initial signal voltage in mmc_power_off() to allow re-boot to function.
This fixes re-boot with UHS cards on Asus Tinker Board (Rockchip RK3288),
same issue have been seen on some Rockchip RK3399 boards.
Backport from https://lore.kernel.org/linux-rockchip/AM3PR03MB09664161A7FA2BD68B2800A7AC620@AM3PR03MB0966.eurprd03.prod.outlook.com/
> rockchip: fixes re-boot with UHS cards

- package/libs/mbedtls/Makefile
- package/libs/mbedtls/patches/100-Implements-AES-and-GCM-with-ARMv8-Crypto-Extensions.patch
- package/libs/mbedtls/patches/200-config.patch
From original PR ARMmbed/mbedtls#1424:
> A compact patch that provides AES and GCM implementations that utilize the
> ARMv8 Crypto Extensions. The config flag is MBEDTLS_ARMV8CE_AES_C, which
> is disabled by default as we don't do runtime checking for the feature.
> The new implementation lives in armv8ce_aes.c.
> 
> Provides similar functionality to ARMmbed/mbedtls#432
> Thanks to Barry O'Rourke and others for that contribtion.
> 
> Tested on a Cortex A53 device and QEMU. On a midrange phone the real AES-GCM
> throughput increases about 4x, while raw AES speed is up to 10x faster.
> mbedtls: Implements AES and GCM with ARMv8 Crypto Extensions

- target/linux/ath79/dts/qca9558_domywifi_dw33d.dts
- target/linux/ath79/image/nand.mk
Compiled-on: ath79, kernel 4.19 & 5.4
Run-tested-on: none
Fixes: #5267, #5299
> ath79: domywifi_dw33d: support startup from breed

- target/linux/rockchip/image/armv8.mk
Vendor driver seems to be better than the one from kernel mainline.
> rockchip: nanopi-r4s: use vendor driver for PCIe ethernet adapter

- package/lean/r8152/Makefile
- package/lean/r8152/patches/100-add-LED-configuration-from-OF.patch
This is the vendor driver for r8152/r8153 series USB ethernet adapter, it may be
better than the driver from kernel mainline, or be worse. It's depending on your
use-case.
> r8152: introduce r8152/r8153 driver from vendor

- package/kernel/mwlwifi/Makefile
This should fix the problem of mwlwifi-firmware-* not being found
when using the ImageBuilder.
> mwlwifi: add PKG_FLAGS:=nonshared

- package/libs/openssl/Makefile
- package/libs/openssl/patches/430-e_devcrypto-make-the-dev-crypto-engine-dynamic.patch
This version fixes 2 security vulnerabilities, among other changes:
- CVE-2021-3450: problem with verifying a certificate chain when using
the X509_V_FLAG_X509_STRICT flag.
- CVE-2021-3449: OpenSSL TLS server may crash if sent a maliciously
crafted renegotiation ClientHello message from a client.
> openssl: bump to 1.1.1k

- package/lean/luci-app-unblockmusic/root/etc/init.d/unblockmusic
之前网易解锁的go版没有在启动命令中添加-o参数导致无法更换音源
并且代码中有两个-m重复，删除了多余的一个
> Fix go unblockmusic can't change provider

- package/lean/luci-app-zerotier/root/etc/zerotier.start
* [ x] 我知道
新版zerotier使用原来的表达式无法区分zt的网段是哪个，需添加kernel字符串
> Fix luci-app-zerotier iptables bug

- package/boot/uboot-rockchip/patches/103-rockchip-rk3328-Add-support-for-Orangepi-R1-Plus.patch
- target/linux/rockchip/patches-5.4/202-rockchip-rk3328-Add-support-for-OrangePi-R1-Plus.patch
* [x ] 我知道
这个主要是之前大神提供的Orangepi R1 Plus的支持，我编译之后一直不可用。然后经过自己试验，把香橙派官方那个内核和uboot的内容整合进来了，改完之后，可以正常编译，R1 Plus可以正常使用了。
> 修复Orangepi R1 Plus 编译后不可用的问题

- package/firmware/cypress-firmware/Makefile
These firmware files are not including at the latest cypress-firmware (d037aff9ed5f022c58fb655208cda43e50db29a7) archive:
cypress-firmware-4359-pcie
cypress-firmware-4359-sdio
cypress-firmware-89459-pcie
If select these firmware packages when `make menuconfig`, OpenWrt will build error.
So remove them now.
> Remove outdate cypress firmwares

- package/network/services/dnsmasq/files/dnsmasq.conf
默认情况下 SSR PLUS DNS结果根本无法缓存(由于引入拒绝ipv6结果导致的问题)，nslookup & dig 延迟每次依然有200-300多.
dnsmasq处设置缓存依然无效，设置TTL也无效，应该是bug。
解决办法是手动指定缓存TTL为最大一小时。域名查询实测有效缓存0延迟。 
此变更仅使开启dnsmasq缓存的情况下正常工作。
> 使 DNSMASQ 缓存设置有效化

- package/boot/uboot-envtools/files/ramips
- target/linux/ramips/dts/mt7621_jcg_q20.dts
- target/linux/ramips/image/mt7621.mk
- target/linux/ramips/mt7621/base-files/etc/board.d/01_leds
- target/linux/ramips/mt7621/base-files/etc/board.d/02_network
- target/linux/ramips/mt7621/base-files/etc/hotplug.d/ieee80211/10_fix_wifi_mac
- target/linux/ramips/mt7621/base-files/lib/upgrade/platform.sh
```
JCG Q20 is an AX 1800M router.
SoC: MediaTek MT7621AT
Flash: Winbond W29N01HV 128 MiB
RAM: Winbond W632GU6NB-11 256 MiB
WiFi: MT7915 2.4/5 GHz 2T2R
Ethernet: 10/100/1000 Mbps x3
LED: Status (red / blue)
Button: Reset, WPS
Power: DC 12V,1A
```
> ramips: add support for JCG Q20

- package/lean/UnblockNeteaseMusic/Makefile
- package/lean/luci-app-unblockmusic/Makefile
- package/lean/luci-app-unblockmusic/luasrc/model/cbi/unblockmusic/unblockmusic.lua
- package/lean/luci-app-unblockmusic/root/usr/share/UnblockNeteaseMusic/update_core.sh
编译前需要删除dl/UnblockNeteaseMusic-0.25.3.tar.gz再编译
更新固件前需要ssh进去OpenWrt，删掉/lib/upgrade/keep.d/unblockmusic后再更新
这样才能覆盖掉原有的证书
> UnblockNeteaseMusic: Change source to 1715173329

- package/firmware/cypress-firmware/Makefile
> cypress-firmware: bump to v5.4.18-2021_0527

- package/network/services/hostapd/files/hostapd.sh
启用该功能有可能导致无线连接不稳定，经常自动掉线的问题。且未必所有无线驱动支持该功能
参考OpenWrt FAQ：
https://openwrt.org/faq/disconnected_due_to_excessive_missing_acks
https://openwrt.org/faq/deauthenticated_due_to_inactivity
> hostapd: 默认禁用无线弱信号自动剔除功能

- package/lean/default-settings/Makefile
- package/lean/luci-app-xlnetacc/Makefile
当前源码采用旧版luci，luci-compat此兼容包只配合新版luci使用
> luci-app-xlnetacc: 删除非必要依赖luci-compat

- target/linux/rockchip/patches-5.10/101-dts-rockchip-add-usb3-controller-node-for-RK3328-SoCs.patch
* [ x] 我知道
在 https://github.com/coolsnowwolf/lede/commit/8575f72a6bc2720bc8fdc6e4e75c0da8adaa7317 升级了5.10.51之后nanopi r2s编译就报错通不过
改用 https://github.com/coolsnowwolf/lede/commit/a8ad0940bf17ddc07a138be6014c64b35f37e47a 里面的补丁就通过了
> fix RK3328 compile error on kernel 5.10.51

- package/lean/mtk-eip93/patches/0001-Fix-compilation-issues.patch
- target/linux/ramips/patches-5.10/999-crypto-eip93-fix.patch
- target/linux/ramips/patches-5.4/999-crypto-eip93-fix.patch
* [ x ] 我知道
```
[ 21.618327] cryptodev: driver 1.11 loaded.
[ 21.636856] fuse: init (API version 7.32)
[ 21.651666] usbcore: registered new interface driver cdc_wdm
[ 21.661299] Loading modules backported from Linux version v5.10.42-0-g65859eca4dff
[ 21.668918] Backport generated by backports.git v5.10.42-1-0-gbee5c545
[ 21.680346] mtk-eip93 1e004000.crypto: PRNG initialized
[ 21.693268] mtk-eip93 1e004000.crypto: EIP93 initialized succesfull
```
> ramips: crypto: Fix with Mediatek EIP93 Crypto Engine for MT7621 SoC

- package/boot/uboot-envtools/files/ipq806x
- target/linux/ipq806x/base-files/etc/board.d/02_network
- target/linux/ipq806x/base-files/etc/hotplug.d/firmware/11-ath10k-caldata
- target/linux/ipq806x/base-files/lib/upgrade/platform.sh
- target/linux/ipq806x/files/arch/arm/boot/dts/qcom-ipq8065-rt4230w-rev9.3.dts
- target/linux/ipq806x/files/arch/arm/boot/dts/qcom-ipq8065-rt4230w.dtsi
- target/linux/ipq806x/image/Makefile
- target/linux/ipq806x/patches-5.10/0069-arm-boot-add-dts-files.patch
- target/linux/ipq806x/patches-5.4/0069-arm-boot-add-dts-files.patch
The difference between flashing:
```
Interrupt U-Boot and run these commands:
setenv bootcmd "setenv mtdids nand0=nand0 && set mtdparts
mtdparts=nand0:0xDC00000@0x2400000(firmware) && ubi part firmware &&
ubi read 0x44000000 kernel 0x6e0000 && bootm"
saveenv
```
> ipq806x: add support for askey rt4230w 256m nand version

- package/boot/uboot-envtools/files/ipq806x
- target/linux/ipq806x/base-files/etc/board.d/02_network
- target/linux/ipq806x/base-files/etc/hotplug.d/firmware/11-ath10k-caldata
- target/linux/ipq806x/base-files/lib/upgrade/platform.sh
- target/linux/ipq806x/files/arch/arm/boot/dts/qcom-ipq8065-rac2v1a.dts
- target/linux/ipq806x/image/Makefile
- target/linux/ipq806x/patches-5.10/0069-arm-boot-add-dts-files.patch
- target/linux/ipq806x/patches-5.4/0069-arm-boot-add-dts-files.patch
```
This commit add support for Arris RAC2V1A (aka TR4400-AC).
SoC: Qualcomm IPQ8065
RAM: 256 MB DDR3
Flash: 512 MB NAND
WiFi1: Qualcomm QCA9983 2.4 GHz
WiFi2: Qualcomm QCA9984 5 GHz
Ethernet1: AR8033 PHY -> Wan
Ethernet2: QCA8337 Switch -> Lan 1~4
LED: Status (red / blue)
USB: 1x USB 3.0 Type-A
Button: Reset, WPS
Power: DC 12V,2.5A
Installation:
Interrupt U-Boot, tftpboot initramfs image,
than sysupgrade to openwrt.
```
Very thanks for asushugo's help.
Warning: Do not try to enable nss driver, this will cause the kernel to crash.
> ipq806x: add support for Arris RAC2V1A

- package/lean/luci-app-turboacc/Makefile
- package/lean/luci-app-turboacc/root/etc/init.d/turboacc
- package/lean/shortcut-fe/shortcut-fe/Makefile
- package/lean/shortcut-fe/shortcut-fe/files/etc/init.d/shortcut-fe
* [ x] 我知道
Fix issues #7840
Shortcut-fe-cm supports IPV6 by default. So the Shortcut-fe driver must work in an IPV6-enabled environment to prevent other problems.
**If you encounter problems, please check whether IPv6 is enabled first**
> luci-app-turboacc: fix issues #7840

- target/linux/ipq807x/base-files/etc/board.d/02_network
- target/linux/ipq807x/files/arch/arm64/boot/dts/qcom/ipq8071-mf269.dts
- target/linux/ipq807x/image/generic.mk
Fixed the errors on the original dts, such as the 2.5G network port and usb part. Thanks for @ksong008 's test.
> ipq807x: improve support for ZTE MF269

- target/linux/ramips/dts/mt7621_jcg_jhr-ac945m.dts
- target/linux/ramips/image/mt7621.mk
- target/linux/ramips/mt7621/base-files/etc/board.d/02_network
```
SoC: MediaTek MT7621AT
Flash: SPI NOR 16MB
RAM: DDR3 256MB
2.4GHz: MT7615N bgn 4x4
5GHz: MT7615N nac 4x4
Ethernet: 1 x WAN and 4 x LAN
USB: 1 x 3.0
Button: Reset, WPS
Unsupported chips:
ATMEGA328P-AU
HCLTEK HT1621B
Flash instructions:
Upload factory.bin in stock firmware's upgrade page.
```
> ramips: add support for JCG JHR-AC945M

- target/linux/rockchip/image/Makefile
In rockchip's proprietary ddrloader, the idbloader can be general and
no longer limited to the specific device.
This matches the behavior in arm-trusted-firmware-rockchip-vendor.
Fixes: dd71a38acb78ef ("uboot-rockchip: update package")
Fixes: #7955
> rockchip: update binary name of idbloader

- package/lean/amule/Makefile
- package/lean/amule/patches/001-amule-dlp.patch
- package/lean/amule/patches/003_enable_upnp_cross_compile.patch
- package/lean/amule/patches/004_file_name_conversion.patch
- package/lean/amule/patches/005_best_keyword_kad_search.patch
- package/lean/amule/patches/006_update-libupnp.patch
- package/lean/amule/patches/007-binutils.patch
- package/lean/amule/patches/008-upnp2.patch
The dependencies in the repo doesn't meet the minimum requirements for
upgrading to the latest aMule version.
This reverts commit dc43ea2936dafe5a85cf9154a1c7af5dadec942f.
don't be a smart-ass.
> Revert "amule: update to 2.3.3 (#7935)"

- package/lean/qBittorrent-static/Makefile
- package/lean/qBittorrent/Makefile
x86_64-qbittorrent-nox 4.3.8_v1.2.14 is deleted ...
> qbittorrent: bump to v4.3.9

- target/linux/rockchip/patches-5.10/205-rockchip-rk3399-Add-support-for-EmbedFire-DoorNet2.patch
- target/linux/rockchip/patches-5.4/205-rockchip-rk3399-Add-support-for-EmbedFire-DoorNet2.patch
修复EmbedFire DoorNet2因为emmc默认频率过高造成的初始化错误
> rockchip: fix rk3399 DoorNet2 emmc clk

- target/linux/ipq806x/base-files/etc/board.d/02_network
- target/linux/ipq806x/base-files/etc/hotplug.d/firmware/11-ath10k-caldata
- target/linux/ipq806x/base-files/etc/init.d/bootcount
- target/linux/ipq806x/base-files/lib/upgrade/norton.sh
- target/linux/ipq806x/base-files/lib/upgrade/platform.sh
- target/linux/ipq806x/files/arch/arm/boot/dts/qcom-ipq8065-core-518.dts
- target/linux/ipq806x/image/Makefile
- target/linux/ipq806x/patches-5.10/0069-arm-boot-add-dts-files.patch
- target/linux/ipq806x/patches-5.4/0069-arm-boot-add-dts-files.patch
这个路由器需要更换U后才能刷（因为U开启了安全启动），此固件第一次启动没有无线，开机时间3分钟后再重启无线就有了
1. 先判断当前系统的启动分区，留意下图的位置
如果结尾是10，则使用下面的命令
```
tftpboot kernel.bin && mmc erase 0x00007D22 0x0000CD21 && mmc write 0x44000000 0x00007D22 0x0000CD21
tftpboot rootfs.bin && mmc erase 0x0000CD22 0x0004CD21 && mmc write 0x44000000 0x0000CD22 0x0004CD21
```
如果结尾是21，则使用下面的命令
```
tftpboot kernel.bin && mmc erase 0x00095022 0x0009A021 && mmc write 0x44000000 0x00095022 0x0009A021
tftpboot rootfs.bin && mmc erase 0x0009A022 0x000DA021 && mmc write 0x44000000 0x0009A022 0x000DA021
```
当然，你也可以直接一了百了地把这些命令都执行一遍，把这双分区都刷了
刷完后，输入bootipq即可进入系统
进去系统后，执行一次恢复出厂设置，否则配置可能无法保存。
编译此机箱需要进去make kernel_menuconfig去掉下面这个选项的勾，然后再编译，否则可能无线启动巨慢
位置在
Device Drivers -> Generic Driver Options -> Firmware loader
这个设置可能对其他机型不适用，所以编译其他机型的时候需要重新勾上，或者执行git checkout …
> ipq806x: Add Norton 518 support

- package/kernel/linux/modules/netdevices.mk
kernel: add module for bnxt_en Linux driver for the 
Broadcom NetXtreme-C/NetXtreme-E 
BCM573xx, BCM574xx, BCM575xx, NetXtreme-S BCM5880x
(up to 200 Gbps) Ethernet Network Controllers and Broadcom Nitro
BCM58700 4-port 1/2.5/10 Gbps Ethernet Network Controller.
> kernel: add module for  bcm574xx 575xx serials

- target/linux/ramips/dts/mt7621_raisecom_msg1500-z-00.dts
- target/linux/ramips/image/mt7621.mk
- target/linux/ramips/mt7621/base-files/etc/board.d/01_leds
Hardware:
SoC: MediaTek MT7621AT
Flash: SPI NOR 16MB
RAM: DDR3 64MB
2.4GHz: MT7603EN bgn 2x2
5GHz: MT7612EN nac 2x2
Ethernet: 1 x WAN and 4 x LAN
USB: 1 x 3.0
Button: Reset, WPS
Note: the flash memory capacity is only 64MB.
You may need to uncheck some options to ensure normal startup.
Signed-off-by: LINGJP <lonelyjskj@gmail.com>
MSG1500 Z.00 RAM为64MB，请精简部分插件保证固件正常启动.
> ramips: add support for RAISECOM MSG1500 Z.00

- package/base-files/Makefile
- package/base-files/files/lib/upgrade/emmc.sh
- scripts/target-metadata.pl
- target/Config.in
Adds generic support for sysupgrading on eMMC-based devices.
Provide function emmc_do_upgrade and emmc_copy_config to be used in
/lib/upgrade/platform.sh instead of redundantly implementing the same
logic over and over again.
Similar to generic sysupgrade on NAND, use environment variables
CI_KERNPART, CI_ROOTPART and newly introduce CI_DATAPART to indicate
GPT partition names to be used. On devices with more than one MMC
block device, CI_ROOTDEV can be used to specify the MMC device for
partition name lookups.
Also allow to select block devices directly using EMMC_KERN_DEV,
EMMC_ROOT_DEV and EMMC_DATA_DEV, as using GPT partition names is not
always an option (e.g. when forced to use MBR).
To easily handle writing kernel and rootfs make use of sysupgrade.tar
format convention which is …
> base-files: add eMMC sysupgrade support

- config/Config-images.in
- include/image-commands.mk
- target/linux/x86/Makefile
- target/linux/x86/image/Makefile
######sync upstream#####
Added support to generate dynamic-sized VHDX images for Hyper-V.
Compile-tested on x86 and run-tested on Windows 10 21H2 (Hyper-V).
Signed-off-by: Oldřich Jedlička <oldium.pro@gmail.com>
> x86: added support to generate VHDX images

- include/kernel-version.mk
- target/linux/bcm27xx/patches-5.10/950-0690-drm-Pass-the-full-state-to-connectors-atomic-functio.patch
- target/linux/bcm27xx/patches-5.10/950-0733-usb-xhci-workaround-for-bogus-SET_DEQ_PENDING-endpoi.patch
- target/linux/generic/backport-5.10/103-v5.13-MIPS-select-CPU_MIPS64-for-remaining-MIPS64-CPUs.patch
- target/linux/generic/backport-5.10/600-v5.12-net-extract-napi-poll-functionality-to-__napi_poll.patch
- target/linux/generic/backport-5.10/601-v5.12-net-implement-threaded-able-napi-poll-loop-support.patch
- target/linux/generic/backport-5.10/602-v5.12-net-add-sysfs-attribute-to-control-napi-threaded-mod.patch
- target/linux/generic/backport-5.10/603-v5.12-net-fix-race-between-napi-kthread-mode-and-busy-poll.patch
- target/linux/generic/backport-5.10/604-v5.12-net-fix-hangup-on-napi_disable-for-threaded-napi.patch
- target/linux/generic/backport-5.10/781-v5.13-net-dsa-mt7530-Add-support-for-EEE-features.patch
- target/linux/generic/hack-5.10/220-gc_sections.patch
- target/linux/generic/hack-5.10/301-mips_image_cmdline_hack.patch
- target/linux/generic/hack-5.10/952-net-conntrack-events-support-multiple-registrant.patch
- target/linux/generic/hack-5.10/953-net-patch-linux-kernel-to-support-shortcut-fe.patch
- target/linux/generic/pending-5.10/300-mips_expose_boot_raw.patch
- target/linux/generic/pending-5.10/680-NET-skip-GRO-for-foreign-MAC-addresses.patch
- target/linux/ipq60xx/patches-5.10/011-v5.11-PCI-dwc-Move-MSI-interrupt-setup-into-DWC-common-cod.patch
- target/linux/ipq60xx/patches-5.10/013-v5.11-PCI-dwc-Move-link-handling-into-common-code.patch
- target/linux/ipq60xx/patches-5.10/014-v5.11-PCI-dwc-Move-dw_pcie_msi_init-into-core.patch
- target/linux/ipq60xx/patches-5.10/600-qca-nss-ecm-support-CORE.patch
- target/linux/ipq60xx/patches-5.10/602-qca-add-pppoe-offload-support.patch
- target/linux/ipq60xx/patches-5.10/603-net-core-Flag-to-identify-ingress-shaping-done-for-e.patch
- target/linux/ipq60xx/patches-5.10/604-net-core-Replace-nss-keyword-with-offload.patch
- target/linux/ipq60xx/patches-5.10/703-arm64-dts-ipq6018-Fixdma-node-name.patch
- target/linux/ipq60xx/patches-5.10/711-qcom-socinfo-Add-IPQ6018-SoC-family-ID-s.patch
- target/linux/ipq60xx/patches-5.10/994-ipq6018-mem-profile.patch
- target/linux/ipq60xx/patches-5.10/995-ipq6018-mem-block.patch
- target/linux/ipq60xx/patches-5.10/996-clk-alpha-pll.patch
- target/linux/ipq60xx/patches-5.10/999-add-ipq6018-dts.patch
Signed-off-by: boos4721 <3.1415926535boos@gmail.com>
> kernel: bump 5.10 to 5.10.84

- package/lean/luci-app-softethervpn/Makefile
- package/lean/luci-app-softethervpn/luasrc/model/cbi/softethervpn.lua
I updated the link for downloading Windows client to download the latest
currently available version instead of using beta version, which is not
good to use in production.
Also, the macOS link led to the OpenVPN server, which was wrong. It should
be a client. It was updated to the latest version as well.
> luci-app-softethervpn: update provided links for SoftEtherVPN clients

- package/lean/luci-app-softethervpn/luasrc/model/cbi/softethervpn.lua
> luci-app-softethervpn: Correct the link of SoftEtherVPN Manager

- package/lean/luci-app-softethervpn/luasrc/model/cbi/softethervpn.lua
更正 Mac OS X 的 SoftEtherVPN Server 管理器链接（恢复到最早正确链接。）。
> luci-app-softethervpn: correct the link of SoftEtherVPN Manager for Mac OS X

- .github/workflows/openwrt-ci.yml
- fix alternatives for my.cnf problem. ([see also](https://github.com/actions/virtual-environments/commit/211e6f3c29a79e3028987fbbadc158352d793881#diff-6be9f9ce03ba57ca01e4ae937d5c2bb04893520fdf391ea87eb46acbc43ecdc5))
- expand compilation space to 60GB.
> CI: fix 'alternatives for my.cnf' problem

- package/lean/luci-app-frpc/luasrc/model/cbi/frp/basic.lua
* [ x ] 我知道
frpc 可以通过 http/socks5 代理连接到 frps ，[见文档](https://gofrp.org/docs/features/common/client/)
luci-app-frpc 支持这项参数的设置，但它错误地给代理链接加上了无符号数的限制，导致原本格式正确的链接无法被识别。
我在 /usr/lib/lua/luci/cbi/datatypes.lua 中没有找到能识别这种链接的函数，所以建议直接去除限制。
> luci-app-frpc: remove data type restriction of http_proxy

- package/lean/n2n_v2/files/n2n_v2.init
* [ x] 我知道
n2n 3.0 版本不再支持-s参数，掩码合并到ip中的cidr
```bash
root@OpenWrt:~# /etc/init.d/n2n_v2 start
08/Jan/2022 10:02:55 [edge.c:779] WARNING: unknown option -s
Welcome to n2n v.3.0.0 for Debian bullseye/sid
Built on Jan  7 2022 03:21:27
Copyright 2007-2021 - ntop.org and contributors
general usage:  edge <config file> (see edge.conf)
or   edge  -c <community name> -l <supernode host:port>
.......
```
> n2n 3.0 not support -s param

- package/lean/luci-app-turboacc/root/etc/init.d/turboacc
The actual script dnscache-while.sh is still in the process after the DNS cache stops. This optimization completely stops the script and the DNS cache process
>  luci-app-turboacc: Optimized the dns cache stop action

- package/kernel/linux/modules/netdevices.mk
fix missing depends for kmod-bnxt-en
> fix missing depends for kmod-bnxt-en

- target/linux/ipq806x/base-files/etc/board.d/01_leds
- target/linux/ipq806x/base-files/etc/board.d/02_network
- target/linux/ipq806x/files/arch/arm/boot/dts/qcom-ipq8064-g-nat200.dts
- target/linux/ipq806x/image/Makefile
- target/linux/ipq806x/patches-5.10/0069-arm-boot-add-dts-files.patch
- target/linux/ipq806x/patches-5.4/0069-arm-boot-add-dts-files.patch
```
SoC: Qualcomm IPQ8064
RAM: 1GB DDR3
SPI: 32MB S25FL256S
NAND: 512MB S34MS04G2 (unused)
Ethernet: 5x 10/100/1000 Mbps QCA8337
LED: internet, usb, sata
Button: Reset
USB: 1 x 3.0
Installation:
Interrupt U-Boot, tftpboot initramfs image,
than sysupgrade to openwrt.
```
Closed: #8718
> ipq806x: add support for SURF G-NAT200

- package/boot/uboot-rockchip/patches/105-rockchip-rk3399-Add-support-for-EmbedFire-DoorNet2.patch
- target/linux/rockchip/patches-5.10/205-rockchip-rk3399-Add-support-for-EmbedFire-DoorNet2.patch
- target/linux/rockchip/patches-5.10/992-rockchip-rk3399-overclock-to-2.2-1.8-GHz-for-NanoPi4.patch
- target/linux/rockchip/patches-5.4/205-rockchip-rk3399-Add-support-for-EmbedFire-DoorNet2.patch
- target/linux/rockchip/patches-5.4/992-rockchip-rk3399-overclock-to-2.2-1.8-GHz-for-NanoPi4.patch
u-boot:
Modify the startup method of doornet2: change sd to priority startup, which is convenient for repairing emmc; I think that changing sd to start first is to facilitate the repair of emmc booting to sd in the event of a crash, re-destructing emmc partitions and creating new partitions, and burning the dd command into it.
phy:
According to the manufacturer's board Ethernet, it is recommended to use two timing modes: one is provided by Rockchip by default, and the other is to add 25M timing to solve the self-adaptation problem:The actual test is not affected by other r4s devices,The stmmac_main.c power-on reset time for doornet2 phy is 1.5 seconds.
emmc:
According to the actual test emmc read and write performance, hs400 and hs200 are the same, but …
> rockchip:Fix doornet2 device tree

- target/linux/bcm27xx/modules/video.mk
This fix for following issue:
```
Package kmod-drm-vc4 is missing dependencies for the following libraries:
fb_sys_fops.ko
syscopyarea.ko
sysfillrect.ko
sysimgblt.ko
make[2]: *** [/openwrt/bin/targets/bcm27xx/bcm2711/packages/kmod-drm-vc4_5.4.175-1_aarch64_cortex-a72.ipk] Error 1
/openwrt/target/linux/bcm27xx/modules/video.mk:52: recipe for target '/openwrt/bin/targets/bcm27xx/bcm2711/packages/kmod-drm-vc4_5.4.175-1_aarch64_cortex-a72.ipk' failed
```
Taken from https://github.com/WYC-2020/lede/commit/f3b81b3e65fdcfc1e533ee72377aa16063908cf7
> kmod-drm-vc4:fix drm-vc4 missing dependencies

- package/boot/uboot-rockchip/patches/104-rockchip-rk3328-Add-support-for-EmbedFire-DoorNet1.patch
The dts refers to the official website uboot startup parameters
`arch/arm/mach-rockchip/rk3328/rk3328.c`---Fix boot order parameters,It is 
helpful for other devices to start emmc and sd normally
> uboot-rockchip: Fix doornet1dts

- package/kernel/linux/modules/netsupport.mk
Add option to compile kmod-inet-diag, support for INET (TCP, DCCP, etc)
socket monitoring interface used by native Linux tools such as ss.
> kernel/modules: add kmod-inet-diag package

- target/linux/rockchip/armv8/base-files/etc/board.d/02_network
- target/linux/rockchip/patches-5.10/007-arm64-dts-rockchip-add-EEPROM-node-for-NanoPi-R4S.patch
- target/linux/rockchip/patches-5.15/007-arm64-dts-rockchip-add-EEPROM-node-for-NanoPi-R4S.patch
- target/linux/rockchip/patches-5.4/010-arm64-dts-rockchip-add-EEPROM-node-for-NanoPi-R4S.patch
there will be a change in the next batch of r4s. The specifications are with or 
without eeprom chip. In order to consider the cost of the chip, they decided to 
remove the eeprom chip and reduce the price.
Today is update theme is optimized for with or without eeprom chips.
**if the r4s does not have an eeprom chip, the previous firmware 
cannot be used! have a greater impact on this**
remove the mandatory binding of the mac address in the patch. If it is 
not removed, the initialization will fail for the chip without EEPROM. 
It is recommended to remove the mandatory binding.
```
+&gmac {
+	nvmem-cells = <&mac_address>;
+	nvmem-cell-names = "mac-address";
+};
```
[02_network](https://github.com/coolsnowwolf/lede/commit/966d926746467e6c56b24a782779d10caf …
> rockchip:fix nanopi-r4s mac address

- package/libs/openssl/Makefile
This is a bugfix release. Changelog:
*) Fixed a bug in the BN_mod_sqrt() function that can cause it to loop
forever for non-prime moduli. (CVE-2022-0778)
*) Add ciphersuites based on DHE_PSK (RFC 4279) and ECDHE_PSK
(RFC 5489) to the list of ciphersuites providing Perfect Forward
Secrecy as required by SECLEVEL >= 3.
Signed-off-by: Martin Schiller <ms@dev.tdt.de>
> openssl: bump to 1.1.1n

- target/linux/ipq806x/base-files/etc/board.d/02_network
Fix that the Ethernet interface function cannot work normally due to [5c40fcd](https://github.com/coolsnowwolf/lede/commit/5c40fcd80ee9774b483a1c6babd1025ab0108e61).
> ipq806x: fix Norton 518 switch interface definition

- package/utils/ucode/Makefile
33f1e0b treewide: move json-c compat shims into internal header file
e0e9431 vm: move unhandled exception reporting out of `uc_vm_execute_chunk()`
2b59140 vm: fix callframe double free on unhanded exceptions
7d7e950 main: abort when failing to load a preload library
1032a67 lib: let `json()` accept input objects implementing `read()` method
5ee68d5 fs: implement `fs.readfile()` and `fs.writefile()`
df6b861 ci: debian: change path before attempting to invoke Git operations
dfaf05a ci: debian: automatically update changelog from Git tag
34f3c45 ci: fix YAML syntax of Debian workflow
e956bcf fs: fix off-by-one in fs.dirname() function
6fc4b6c .gitignore: fix overmatching patterns, blacklist cram .venv
7c2e082 build: remove legacy json-c check
77942af build: add polyfills for older libjson-c …
> ucode: update to latest Git HEAD

- package/libs/wolfssl/Makefile
- package/libs/wolfssl/patches/100-disable-hardening-check.patch
- package/libs/wolfssl/patches/200-ecc-rng.patch
- package/libs/wolfssl/patches/300-fix-SSL_get_verify_result-regression.patch
Fixes two high-severity vulnerabilities:
- CVE-2022-25640: A TLS v1.3 server who requires mutual authentication
can be bypassed.  If a malicious client does not send the
certificate_verify message a client can connect without presenting a
certificate even if the server requires one.
- CVE-2022-25638: A TLS v1.3 client attempting to authenticate a TLS
v1.3 server can have its certificate heck bypassed. If the sig_algo in
the certificate_verify message is different than the certificate
message checking may be bypassed.
Signed-off-by: Eneas U de Queiroz <cotequeiroz@gmail.com>
> wolfssl: bump to 5.2.0

- package/libs/libmnl/Makefile
Changes:
Duncan Roe (5):
nlmsg: Fix a missing doxygen section trailer
build: doc: "make" builds & installs a full set of man pages
build: doc: get rid of the need for manual updating of Makefile
build: If doxygen is not available, be sure to report "doxygen: no" to ./configure
src: doc: Fix messed-up Netlink message batch diagram
Fernando Fernandez Mancera (1):
src: fix doxygen function documentation
Florian Westphal (1):
libmnl: zero attribute padding
Guillaume Nault (1):
callback: mark cb_ctl_array 'const' in mnl_cb_run2()
Kylie McClain (1):
examples: nfct-daemon: Fix test building on musl libc
Laura Garcia Liebana (4):
examples: add arp cache dump example
examples: fix neigh max attributes
examples: fix print line format
examples: reduce LOCs during neigh attributes validation
Pablo …
> libmnl: update to 1.0.5

- target/linux/kirkwood/base-files/etc/board.d/02_network
- target/linux/kirkwood/files/arch/arm/boot/dts/kirkwood-net110.dts
- target/linux/kirkwood/image/Makefile
* [ x] 我知道
Changes:
add support device Surfilter Net110
add build uImage only for surfilter_net110
Hwinfo:
CPU: Feroceon 88FR131 Marwell 88F6281 ARMv5TE 1.2Ghz
RAM: 512MB (256MB + 256MB)
NAND: Samsung NAND 128MiB
SWITCH: Marvell 88E6171
PORT: 5 Gbps
Mini-Pcie: 1 half-size
SATA: 2 SATA
USB: 1 USB2
Other: console , SDHCI/MMC , Reset
> Add device support: Surfilter Net110 Marvell 88F6281 based on LCE patch [2]

- package/network/services/dnsmasq/files/dhcp.conf
By this we can change the default dns resolver on ssrplus to dns2tcp and finally get rid of pdnsd.
> dnsmasq: enable cache by default

- include/prereq-build.mk
See: https://github.com/openwrt/openwrt/pull/4736
在 Debian 11 上复现了 https://github.com/coolsnowwolf/lede/issues/9056 描述的错误，实测这个补丁可以在 Debian 11 中解决该错误。
* [ x] 我知道
> build: fix ldconfig executable error in python

- package/lean/n2n_v2/files/n2n_v2.config
- package/lean/n2n_v2/files/n2n_v2.init
supernode参数用于客户端在dhcp模式下自动分配IP，便于使用
-a IP段 | 用于自动分配IP，格式如 -a 192.168.0.0-192.168.255.0/24
luci-app-n2n_v2中也已同步更新
> N2N服务器端dhcp设置

- package/kernel/linux/modules/video.mk
- target/linux/rockchip/modules.mk
Signed-off-by: xiangfeidexiaohuo <jsjson@163.com>
修复编译515时的drm报错，r2s/r4s通过测试。
> rockchip: fix drm for 5.15

- target/linux/kirkwood/base-files/etc/board.d/02_network
- target/linux/kirkwood/files/arch/arm/boot/dts/kirkwood-m8621t.dts
- target/linux/kirkwood/image/Makefile
Hardware all same with the Surfilter Net110, only the switch reg = <0x11> ,and wan reg = <4>, flash 512MiB
Hwinfo:
CPU: Feroceon 88FR131 Marwell 88F6281 ARMv5TE 1.2Ghz
RAM: 512MB (256MB + 256MB)
NAND: Samsung NAND 512MiB
SWITCH: Marvell 88E6171
PORT: 5 Gbps
Mini-Pcie: 1 half-size
SATA: 2 SATA
USB: 1 USB2
Other: console , SDHCI/MMC , Reset
> Add device support: Prafly_m8621t Marvell 88F6281 based on LCE patch (Modified by Jerry Yang) 

- package/lean/igb-intel/Makefile
`CONFLICT` -> `CONFLICTS`.
Fixes: 471976c7d95243 ("igb-intel: mark conflict with kmod-igb")
> igb-intel: fix typo error

- target/linux/rockchip/patches-5.18/801-fix-stmmac_mdio.patch
* [yes] 我知道
通过stmmac_mdio添加延时1.5秒wan复位https://github.com/DHDAXCW/DoorNet2/issues/5
> rockchip：修复linux 5.18 rk3399 wan pppoe拨号异常

- target/linux/armvirt/Makefile
Armvirt is a development and testing platform and should therefore use
the latest OpenWrt Kernel by default.
Tested via qemu.
Acked-by: Rosen Penev <rosenp@gmail.com>
Acked-by: Yousong Zhou <yszhou4tech@gmail.com>
Signed-off-by: Paul Spooren <mail@aparcar.org>
> armvirt: switch to Kernel 5.10

- package/kernel/linux/modules/netdevices.mk
Fix:
Package kmod-mdio-devres is missing dependencies for the following libraries:
of_mdio.ko
Package kmod-of-mdio is missing dependencies for the following libraries:
fwnode_mdio.ko
> kernel: modules: fix kmod-mdio-devres dependency for 5.15

- package/kernel/linux/modules/netdevices.mk
armvirt/64 when compiled with ALL_KMODS=y reports following:
Package kmod-mdio-devres is missing dependencies for the following libraries:
of_mdio.ko
Signed-off-by: Petr Štetiar <ynezz@true.cz>
> kernel: mdio-devres: fix of-mdio dependency

- package/kernel/linux/modules/fs.mk
- package/kernel/linux/modules/netdevices.mk
- package/kernel/linux/modules/other.mk
- package/kernel/linux/modules/usb.mk
- package/kernel/linux/modules/video.mk
- package/kernel/mac80211/ath.mk
- package/lean/ntfs3-mount/Makefile
- target/linux/x86/modules.mk
> kernel: modules: cleanup 5.18

- package/network/services/hostapd/patches/800-hostapd-2.10-lar.patch
由于此补丁 (a5133362edb5d2ff1708bd65de0801141a8eda99) 是针对 ax200/ax210，
但它影响了部分无线驱动检测 DFS 导致开不起 160MHz，故作此修改。
已在 ath11k 编译运行，能够重新开启 160MHz。但我没有条件，未在 ax200/ax210 进行编译运行。
> hostapd: fix this patch to cause some wireless driver DFS detection

- package/firmware/linux-firmware/intel.mk
N5105/6005 的 GUC 最新固件应为 ehl_guc_70.1.1.bin, 使用 ehl_guc_69.0.3.bin 将不能正常加载 GUC 固件
**ehl_guc_69.0.3.bin** `root@OpenWrt[x86_64]:~# dmesg | grep i915`
> [   15.693599] i915 0000:00:02.0: [drm] Finished loading DMC firmware i915/icl_dmc_ver1_09.bin (v1.9)
[   19.317088] i915 0000:00:02.0: GuC firmware i915/ehl_guc_70.1.1.bin: fetch failed with error -12
[   19.318104] i915 0000:00:02.0: Please file a bug on drm/i915; see https://gitlab.freedesktop.org/drm/intel/-/wikis/How-to-file-i915-bugs for details.
[   19.319601] i915 0000:00:02.0: [drm] GuC firmware(s) can be downloaded from https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915
[   19.321752] i915 0000:00:02.0: [drm] GuC firmware i915/ehl_guc_70.1.1.bin version 0.0
[   19.322603] i915 0000:00:02.0: GuC …
> linux-firmware: fix Intel GUC firmware support for N5105/N6005

- target/linux/ramips/dts/mt7621.dtsi
该行已经被反复注释2次了 [第2次](https://github.com/coolsnowwolf/lede/blame/1ccc3bfd54f7d9a2a2a02f2cb2b062452ea8d830/target/linux/ramips/dts/mt7621.dtsi#L560-L561) [第1次](https://github.com/coolsnowwolf/lede/blame/a28334d8b8dfa58dccd6fce369f5ee87e5b5a703/target/linux/ramips/dts/mt7621.dtsi#L566-L567) [新建](https://github.com/coolsnowwolf/lede/blame/14e109d0b91f61f910a5a919a0440468b3e15161/target/linux/ramips/dts/mt7621.dtsi#L566-L567)，若是像他设置的走hnat就会导致ssrplus对wifi的代理超时#10026，可能是有冲突，最好还是保证能正常工作，实在要wifi的hnat可以给一个选择权，不要挖坑，排查都排查了一天
> ramips: let wifi proxying work with ssrplus

- package/boot/uboot-envtools/files/ramips
- target/linux/ramips/dts/mt7621_c-life_xg1.dts
- target/linux/ramips/image/mt7621.mk
- target/linux/ramips/mt7621/base-files/etc/board.d/02_network
- target/linux/ramips/mt7621/base-files/etc/hotplug.d/ieee80211/10_fix_wifi_mac
- target/linux/ramips/mt7621/base-files/lib/upgrade/platform.sh
CPU: MediaTek MT7621AT
Flash: Micron MT29F2G08ABAGAWP 128M
RAM: 256 M
WiFi: MT7915 2.4/5 GHz 2T2R
Ethernet: 10/100/1000 Mbps x3
LED: Status (red / blue / white / green / purple / cyan)
USB: 2.0 x 1
ZigBee/BlueTooth
USB Audio: iec958 x 1
Button: Reset
Power: DC 12V,1.5A
开启ssh方法:
打开网页:192.168.10.1,用户路由器底面标注的用户名密码完成登陆。
然后打开网页:http://192.168.10.1/cgi-bin/luci/admin/mtk/console，在命令行中输入以下命令:
echo -en "root\nroot\n" | passwd
然后打开网页:http://192.168.10.1/cgi-bin/luci/pti/ssh_open
即可ssh登陆192.168.10.1,用户名root,密码root
刷入openwrt:
开启ssh后，上传breed-mt7621-xiaomi-r3g.bin到路由器/tmp目录。
然后使用下面命令刷入breed:
mtd -r write /tmp/breed-mt7621-xiaomi-r3g.bin Bootloader
等待机器重启，等1分钟断开电源。
按住C-Life XG1机身正面的圆形IoT按钮(gpio 18),通电就能进入breed刷机.
> ramips: add support for C-Life XG1 [WIFI6]

- package/firmware/ath11k-firmware/Makefile
Before:
`/lib/firmware/ath11k/WCN6855/hw2.1` links to an abselute path on compiling machine.
After:
It should always link to `./hw2.0`.
> firmware: fix WCN6855 firmware hw2.1 link

- package/firmware/ath11k-firmware/Makefile
board-2.bin is mandatory for ath11k to work with QCA6390.
> ath11k-firmware: Add missing board-2.bin for QCA6390

- package/boot/uboot-rockchip/patches/305-rockchip-rk3399-Add-support-for-FriendlyARM-NanoPi-R.patch
- target/linux/rockchip/files/arch/arm64/boot/dts/rockchip/rk3399-nanopi-r4se.dts
this will cause uboot to fail to load the sd card 
at startup, and uboot can recognize emmc...
```log
=> mmc list
mmc@fe320000: 1
mmc@fe330000: 0 (eMMC)
=> mmc info
Device: mmc@fe330000
Manufacturer ID: 15
OEM: 0
Name: BJTD4R
Bus Speed: 52000000
Mode: MMC High Speed (52MHz)
Rd Block Len: 512
MMC version 5.1
High Capacity: Yes
Capacity: 29.1 GiB
Bus Width: 8-bit
Erase Group Size: 512 KiB
HC WP Group Size: 8 MiB
User Capacity: 29.1 GiB WRREL
Boot Capacity: 4 MiB ENH
RPMB Capacity: 4 MiB ENH
Boot area 0 is not write protected
Boot area 1 is not write protected
=> mmc dev 0
switch to partitions #0, OK
mmc0(part 0) is current device
=> mmc dev 1
switch to partitions #0, OK
mmc1 is current device
=> mmc dev 2
MMC Device 2 not found
no mmc device at slot 2
=> …
```
> uboot-rockchip:fix r4se uboot sd card not bootable

- Makefile
- target/sdk/files/Makefile
Build system: Ubuntu 20.04.5 x86_64 with grep-3.8
Build-tested: ipq807x/QNAP_301w
> Makefile: fix stray \ warnings with grep-3.8

- config/Config-devel.in
- include/download.mk
- scripts/download.pl
> scripts/download.pl: Make the download tool configurable

- package/libs/libselinux/Makefile
- package/libs/libsepol/Makefile
> libselinux: bump to 3.3 and sync with upstream

- target/linux/generic/pending-5.10/476-mtd-spi-nor-add-eon-en25q128.patch
- target/linux/generic/pending-5.15/476-mtd-spi-nor-add-eon-en25q128.patch
Add DUAL_READ flag to EON EN25Q128 as from documentation it's supported. While at it also rework the patch and add a commit description.
Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>
> generic: add DUAL_READ flag to EON EN25Q128

- include/prereq-build.mk
python3.11 is out but fails to run the makefile currently this supports python versions from 3.6 to 3.99 with the python3 binary it also checks specifically for 3.11 as it is the latest version out
Signed-off-by: Oscar Molnar <oscar@tymscar.com>
> build: add support for python3.11 and higher

- package/libs/libusb/Makefile
The 'fxload' tool contained in the examples provided with libusb is actually useful and turns out to be the only way to load firmware into some rather ancient EZ-USB microcontrollers made by Cypress (formerly Anchor Chips).
The original 'fxload' tool from hotplug-linux has been abandonned long ago and requires usbfs to be mounted in /proc/bus/usb/ (like it was in Linux 2.4...).
Hence the best option is to package the modern 'fxload' from the libusb examples which (unsurprisingly) uses libusb and works on modern systems.
Signed-off-by: Daniel Golle <daniel@makrotopia.org>
> packages: libusb: add package 'fxload' (from libusb examples)

- tools/patch/Makefile
- tools/patch/patches/070-don-t-fail-hard-on-EACCES-when-copying-xattrs.patch
When compiling OpenWRT on a compressed btrfs volume the build fails in libtool.
The file `libltdl/config/ltmain.m4sh` from `libtool-2.4.2.tar.xz` is missing write permissions, therefore patch falls back to copying the file and patching that. During this patch tries to preserve all file attribute on the new copy.
However the attribute `btrfs.compression` is privileged and btrfs return EACCES.
While patch ignores multiple other error codes during the copy of xattr copy it is not prepared for EACCES and aborts.
EACCES should be ignored the same way as the other errors.
Build log:
```
...
Applying ./patches/000-relocatable.patch using plaintext:
patching file libltdl/config/general.m4sh
patching file libtoolize.in
patching file libtoolize.m4sh
patching file libltdl/m4/libtool.m4
Applying …
```
> tools/patch: apply patch for EACCES on xattr copy

- target/linux/ipq807x/base-files/etc/sysctl.d/99-bridge-nf-call.conf
qca-nss-ecm启动之后会开启网桥ipv4/ipv6的包过滤导致NAT loopback不可用。再次关闭网桥包过滤，以解决NAT loopback不可用的问题。
> ipq807x: disable br-nf after qca-nss-ecm start

- package/utils/fritz-tools/src/fritz_tffs_nand_read.c
> fritz-tools: sync with upstream

- tools/dosfstools/Makefile
Both mirrors provided in the Makefile only serve gzipped tarballs.
Fixes: #10871
Fixes: 9edfe7dd13d9 ("source: Switch to xz for packages and tools where possible")
Signed-off-by: Stijn Tintel <stijn@linux-ipv6.be>
> tools/dosfstools: fix PKG_SOURCE

- tools/sed/patches/001-sed-fix-handling-of-symlinks-pointing-to-path-with-1.patch
If the absolute path a symlink is pointing to is 128 bytes long sed failed with an error message like this: "<path>/sedstbU8O: Not a directory"
This fixes a problem building python seen in the build bot.
This patch is on its way into upstream sed.
Signed-off-by: Hauke Mehrtens <hauke@hauke-m.de>
Fixes: #10555, #10580
> tools/sed: Fix handling of symlinks of 128 chars

- package/network/utils/iwinfo/patches/001-ralink.patch
- package/network/utils/iwinfo/patches/002-devices-add-MT7986.patch
- package/network/utils/iwinfo/patches/003-devices-add-IPQ8074.patch
- package/network/utils/iwinfo/patches/004-devices-add-QCNxxxx.patch
> iwinfo: backport IPQ8074 and QCNxxxx devices support

- package/boot/arm-trusted-firmware-sunxi/Makefile
- package/boot/uboot-sunxi/Makefile
Make use of the definitions from trusted-firmware-a.mk to build the Trusted firmware arm. This fixes the build with binutils 2.39.
Signed-off-by: Hauke Mehrtens <hauke@hauke-m.de>
> arm-trusted-firmware-sunxi: Use common trusted-firmware-a.mk

- target/linux/generic/files/drivers/net/phy/rtl8367b.c
- target/linux/ramips/dts/mt7620a_hiwifi_r33.dts
- target/linux/ramips/image/mt7620.mk
- target/linux/ramips/mt7620/base-files/etc/board.d/01_leds
- target/linux/ramips/mt7620/base-files/etc/board.d/02_network
- target/linux/ramips/mt7620/base-files/etc/hotplug.d/ieee80211/10_fix_wifi_mac
- target/linux/ramips/mt7620/base-files/lib/upgrade/platform.sh
Manufacturer: HiWiFi
Model: R33
Traditional name: 3Pro C312B B52
CPU: MT7620
RAM: DDR2 128MB
ROM: NAND 128MB
Switch: RTL8367RB
WIFI 5G: MT7612EN
我们已经在openwrt-master openwrt-22.03 和lede中进行了测试，在近一年时间中，运行良好，请求进行合并
> ramips: MT7620 add Support HiWiFi R33(C312B B52)

- package/qca/qca-ssdk/patches/0001-SSDK-config-add-kernel-5.10-5.15.patch
- package/qca/qca-ssdk/patches/0002-SSDK-replace-ioremap_nocache-with-ioremap.patch
- package/qca/qca-ssdk/patches/0004-platform-use-of_mdio_find_bus-to-get-MDIO-bus.patch
- package/qca/qca-ssdk/patches/0005-add-kernel-5.4-support.patch
- package/qca/qca-ssdk/patches/0007-SSDK-dts-fix-of_get_mac_address.patch
- package/qca/qca-ssdk/patches/0009-qca8081-convert-to-5.11-IRQ-model.patch
- package/qca/qca-ssdk/patches/0010-QSDK-config-Avoid-Werror-heroics.patch
Fixed patch application failure.
Fixes: 89200af ("bump qca-ssdk nss-dp and ssdk-shell, Add tplink-tl-er2260t basic support (#10777)")
Fixes: #10844
> qca-ssdk: refresh patches

- target/linux/ipq807x/files-5.15/arch/arm64/boot/dts/qcom/ipq8070-tl-er2260t.dts
- target/linux/ipq807x/patches-5.15/0900-arm64-dts-add-OpenWrt-DTS-files.patch
Only solves other device builds, doesn't support tl-er2260t running.
> ipq807x: add tl-er2260t dts for other device builds in 5.15

- package/lean/ddns-scripts_aliyun/update_aliyun_com.sh
In Action "DescribeSubDomainRecords", define argument “Line” to the specific "defalut". This is for someone who have two or more same domain names but in different dns request source(ISP), but return more than 1 record will goto error "地址需要修改".  For document of  aliyun API, set a Line parament can solve this issue because most of users just have one ISP for each domain and its value was set as "default".
> Define domain request parameter "Line" as default

- target/linux/rockchip/patches-5.15/210-rockchip-rk356x-add-support-for-new-boards.patch
- target/linux/rockchip/patches-6.1/210-rockchip-rk356x-add-support-for-new-boards.patch
```
mkdir -p /home/superb/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/tmp/openwrt-rockchip-armv8-fastrhino_r68s-squashfs-sysupgrade.img.gz.boot
cp -fpR /home/superb/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-5.15.91/arch/arm64/boot/dts/rockchip/rk3568-r68s.dtb /home/superb/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/tmp/openwrt-rockchip-armv8-fastrhino_r68s-squashfs-sysupgrade.img.gz.boot/rockchip.dtb
cp: cannot stat '/home/superb/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-5.15.91/arch/arm64/boot/dts/rockchip/rk3568-r68s.dtb': No such file or directory
make[5]: *** [Makefile:84: /home/superb/lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/tmp/open …
```
> rockchip: fix cannot stat dtb file

- package/lean/mt/drivers/mt7612e/src/mt76x2/os/linux/rt_linux.c
注意到MT7621E驱动默认没有禁用get_fs set_fs 为了兼容新内核，暂时禁用，或者修改为5.10内核以下启用
> mtwifi: Mt7612E disable set_fs get_fs by default

- target/linux/generic/files/drivers/net/phy/swconfig_leds.c
修复[L大提交的:generic: fix swconfig_leds.c in 5.18](https://github.com/coolsnowwolf/lede/commit/ebfa1b93b76d5a2faacecbc8ed237ed44f5a7018) 导致的5.15内核编译失败，测试MT7620编译无法通过，报错指针不兼容，由KERNEL_VERSION(5, 15, 0)修改为>= KERNEL_VERSION(5, 18, 0)为5.15内核保留原有兼容性也保证5.18内核可以支持编译使用
>  generic: fix swconfig_leds.c in 5.15

- package/kernel/ksmbd/Makefile
最近的ksmbd更新编译出错，但是官方源的没问题。和官方源对比，makefile少2行内容，补上了
> ksmbd: sync with official source to fix build error.

- package/boot/uboot-rockchip/Makefile
- target/linux/rockchip/armv8/base-files/etc/board.d/02_network
- target/linux/rockchip/files/arch/arm64/boot/dts/rockchip/rk3568-mrkaio-m68s-plus.dts
- target/linux/rockchip/image/armv8.mk
- target/linux/rockchip/patches-5.15/210-rockchip-rk356x-add-support-for-new-boards.patch
- target/linux/rockchip/patches-6.1/210-rockchip-rk356x-add-support-for-new-boards.patch
rockchip: add support for EZPRO Mrkaio M68S PLUS
Specifications:
- SoC: RK3568B2
- CPU: Quad-core Cortex-A55 up to 2.0GHz
- NPU: 1TOPS NPU
- RAM: 4GB
- Storage: 32G EMMC
- Ethernet: 2x 2.5G/1000/100/10 ports
Signed-off-by: mleaf <mleaf90@gmail.com>
> rockchip: add support for EZPRO Mrkaio M68S PLUS

- package/lean/shortcut-fe/simulated-driver/Makefile
- package/qca/nss/qca-nss-cfi/Makefile
- package/qca/nss/qca-nss-clients-64/Makefile
- package/qca/nss/qca-nss-clients/Makefile
- package/qca/nss/qca-nss-crypto/Makefile
- package/qca/nss/qca-nss-drv-64/Makefile
- package/qca/nss/qca-nss-drv/Makefile
- package/qca/nss/qca-nss-ecm-64/Makefile
- package/qca/nss/qca-nss-ecm/Makefile
- package/qca/nss/qca-nss-gmac/Makefile
- package/qca/qca-mcs/Makefile
- package/qca/qca-rfs/Makefile
- package/qca/qca-ssdk-shell/Makefile
The original URL has been deprecated:
https://bye.codeaurora.org/
fixes: #11048
> qca: change the source repo URL of the qca package

- package/lean/mt/drivers/mt7615d/Makefile
- package/lean/mt/drivers/mt7615d/files/lib/netifd/wireless/mt_dbdc.sh
- package/lean/mt/luci-app-mtwifi/Makefile
主要用于支持K2P的Client模式。
前几年给K2P适配的 mt7615d_dbdc 脚本，一直没支持Client模式，最近又买了个K2P，想作为无线中继，所以这个PR就是加上Client模式的支持：
1. 支持Client模式
2. 支持Client和有线网口的桥接
3. 重启网络或WIFI会自动重连
“无线”页面，将Client模式的WIFI关联到WAN口，增加一个AP也关联到WAN口
“接口”页面，WAN口桥接了两个WIFI
> K2P支持WIFI客户端模式（无线中继/桥接）

- package/lean/mt/drivers/mt7615d/files/lib/netifd/wireless/mt_dbdc.sh
之前测试一直用默认频道，改成非默认频道以后发现并未生效，甚至重启系统都不会生效。由于客户端模式必须要使用正确的频道才能连接，所以修复下。
> 修复K2P的WIFI频道不生效问题

- target/linux/ramips/dts/mt7620a_bolt_bl201.dts
- target/linux/ramips/image/mt7620.mk
- target/linux/ramips/mt7620/base-files/etc/board.d/01_leds
- target/linux/ramips/mt7620/base-files/etc/board.d/02_network
Manufacturer: Bolt
Model: BL201
CPU: MT7620A
RAM: DDR2 64MB
ROM: NAND 16MB
Switch: MT7620
WIFI 5G: MT7612E
> ramips: MT7620 add support for Bolt BL201 board

- target/linux/rockchip/patches-5.15/203-rockchip-rk3328-Add-support-for-OrangePi-R1-Plus-LTS.patch
- target/linux/rockchip/patches-5.15/204-rockchip-rk3328-Add-support-for-FriendlyARM-NanoPi-R.patch
- target/linux/rockchip/patches-6.1/203-rockchip-rk3328-Add-support-for-OrangePi-R1-Plus-LTS.patch
- target/linux/rockchip/patches-6.1/204-rockchip-rk3328-Add-support-for-FriendlyARM-NanoPi-R.patch
修复 NanoPi R2C 和 OrangePi R1 Plus LTS 裕太微网口无法使用问题
#11074
#10980
> Rockchip: fix motorcomm unavailability

- package/firmware/intel-microcode/Makefile
- target/linux/x86/patches-5.15/992-enable-intel-guc.patch
- target/linux/x86/patches-5.15/998-add-a-sysctl-to-enable-disable-tcp_collapse-logic.patch
- target/linux/x86/patches-5.15/999-Add-xtsproxy-Crypto-API-module.patch
- target/linux/x86/patches-6.1/992-enable-intel-guc.patch
- target/linux/x86/patches-6.1/998-add-a-sysctl-to-enable-disable-tcp_collapse-logic.patch
- target/linux/x86/patches-6.1/999-Add-xtsproxy-Crypto-API-module.patch
* [ * ] 我知道
1. fix: [drm] Incompatible option enable_guc=3 - GuC submission is N/A
2. tcp patch add net.ipv4.tcp_collapse_max_bytes option, from Cloudflare's TCP collapse processing for high throughput and low latency patch:
https://blog.cloudflare.com/optimizing-tcp-for-high-throughput-and-low-latency/
> Patch for i915 and tcp

- package/boot/uboot-rockchip/Makefile
- package/boot/uboot-rockchip/patches/310-rockchip-rk3399-Add-support-for-xiaobao-nas-v1.patch
- target/linux/rockchip/armv8/base-files/etc/board.d/02_network
- target/linux/rockchip/files/arch/arm64/boot/dts/rockchip/rk3399-xiaobao-nas-v1.dts
- target/linux/rockchip/image/armv8.mk
- target/linux/rockchip/patches-5.10/206-rockchip-rk3399-add-support-more-devices.patch
- target/linux/rockchip/patches-5.15/211-rockchip-rk3399-add-support-more-devices.patch
- target/linux/rockchip/patches-5.4/206-rockchip-rk3399-add-support-more-devices.patch
- target/linux/rockchip/patches-6.1/211-rockchip-rk3399-add-support-more-devices.patch
Specifications:
SoC: RockChip RK3399
RAM: 4GB LPDDR3
Storage: 8MB SPI Flash + Reserved EMMC land + TF Card slot
Ethernet: 1x 1000M/100M/10M ports
USB:1xUSB2.0 1xUSB3.0 1xType-C
Video Output:1x HDMI
SATA: 5x SATA ports (Transferred by JMB585)
> rockchip: Add support for Codinge Xiaobao NAS-I

- README.md
在 `README.md` 的  `如果你使用 WSL/WSL2 进行编译` 小节中，添加了对一个高概率出现的错误的解决方法。
由于默认情况下，装载到 WSL 发行版的 NTFS 格式的驱动器将不区分大小写，因此在 WSL/WSL2 中进行首次编译检查的时候，几乎必然会发生以下报错：
```
Build dependency: OpenWrt can only be built on a case-sensitive filesystem 
```
关于这一点，在  Windows 的[官方文档](https://learn.microsoft.com/zh-cn/windows/wsl/case-sensitivity#changing-the-case-sensitivity-on-a-drive-mounted-to-a-wsl-distribution)中提供了描述：
> 默认情况下，装载到 WSL 发行版的 NTFS 格式的驱动器将不区分大小写。 若要更改装载到 WSL 分发版的驱动器上的目录的区分大小写， (ie。Ubuntu) ，请遵循上面针对 Windows 文件系统列出的相同步骤。 （默认情况下，EXT4 驱动器区分大小写）。
以及对应的解决方案：
- 若要在目录上启用区分大小写 (FOO ≠ foo)，请使用以下命令：
```bash
fsutil.exe file setCaseSensitiveInfo <path> enable
```
- 若要在目录上禁用区分大小写并返回到默认设置不区分大小写 (FOO = foo)，请使用以下命令：
```bash
fsutil.exe file setCaseSensitiveInfo <path> disable
``` …
> doc: added a workaround for WSL/WSL2 non-sensitive FS errors

- package/network/services/dropbear/Makefile
- package/network/services/dropbear/files/dropbear.init
* [X ] 我知道
* release note：https://github.com/mkj/dropbear/releases/tag/DROPBEAR_2022.83
* solve problem ：
Add '-z' flag to disable setting QoS traffic class. This may be necessary
to work with broken networks or network drivers, exposed after changes to use
AF21 in 2022.82
descrip:
when openwrt route  8.X in Network A ,Network B through ipsecvpn to Network B ,  Network B is 10.X, when we use dropbear whitch version is 2022.82  , 10.X client  ssh to 8.X 's  openwrt must be  failed ! 
issue like :
https://github.com/coolsnowwolf/lede/issues/10569
> update dropbear version

- package/base-files/files/etc/sysctl.conf
Fixed the problem that even if br-netfilter is disabled in package/kernel/linux/files/sysctl-br-netfilter.conf, NAT loopback will still fail. This applies to OpenWrt with Docker
* [ x] 我知道
> Fix OpenWrt with Docker will cause NAT loopback

- package/lean/autocore/files/x86/index.htm
之前提过 issues #11603 
经过不断尝试，发现在 `package/lean/autocore/files/x86/index.htm` 文件中匹配 CPU 使用率所在行的命令 `top -n 1 | grep 'CPU:'` 会获取到两行数据，而另一行是 `grep CPU:` 进程自身，最终导致 CPU 使用率计算报错，如下所示
```
root@OpenWrt:~# top -n 1 | grep 'CPU:' 
CPU:   0% usr   9% sys   0% nic  90% idle   0% io   0% irq   0% sirq
2813  6672 root     S     1124   0%   0% grep CPU:
```
由于 x86 平台和 arm 平台使用的是不同的 index.htm 文件，获取 CPU 使用率的命令也不一样，再结合其他人的反馈，所以这个问题应该是只出现在 x86 平台上
虽然我也还是不知道为啥在编译时取消 autosamba 就会出现这个问题，但是修改匹配条件使用 `grep -E '^CPU:'`  匹配 CPU 使用率所在行可修复此问题
> Fixed the issue where CPU usage only shows a %

- package/wwan/driver/fibocom_QMI_WWAN/src/qmi_wwan_f.c
qmi_wwan_f.c:2100:5: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
2100 |     int status = qmi_wwan_bind(dev, intf);
|     ^~~
* [ x] 我知道
> fibocom_qmi: fixes build error

- target/linux/x86/image/Makefile
Fix bios boot partition is under 1 MiB.
> Fix bios boot partition is under 1 MiB

- target/linux/mediatek/dts/mt7986a-ruijie-rg-x60-pro.dts
- target/linux/mediatek/filogic/base-files/etc/board.d/02_network
- target/linux/mediatek/filogic/base-files/etc/hotplug.d/ieee80211/11_fix_wifi_mac
- target/linux/mediatek/image/filogic.mk
Informations:
- SoC       : MediaTek MT7986A Quad-core ARM® Cortex-A53 2.0GHz
- RAM       : DDR3 512MiB (W634GU6QB)
- Flash     : SPI-NAND 128 MiB (W25N01GVZEIG)
- WLAN      : MediaTek MT7986A integration dual-band WiFi 6
- 2.4 GHz : b/g/n/ax, MIMO 4x4
- 5 GHz   : a/n/ac/ax, MIMO 4x4
- Ethernet  : 10/100/1000 Mbps x4 (MediaTek MT7531AE)
2500Mbps x 1 （Realtek RTL8221B-VB-CG）
- UART      : through-hole on PCB
- [J500] GND, TX, RX, 3.3V (115200n1)
- Buttons   : Mesh, Reset
- LEDs      : 1x Power (Blue)
1x Turbo (Purple)
- Power     : 12 VDC, 3 A
About MAC Address:
+---------+-------------------+-----------+
|         | MAC               | Algorithm |
+---------+-------------------+-----------+
| WAN     | 10:82:3D:XX:XX:9E | label     |
| LAN     | 10:82:3D:XX:XX:9F | label+1   |
| WLAN 2g | …
> mediatek: add support for Ruijie RG-X60 Pro

- package/devel/strace/Makefile
This bump will fix the following build failure with kernel >= 6.6 raised In file included from btrfs.c:51 #12011 :
xlat/btrfs_key_types.h:167:37: error: 'BTRFS_EXTENT_REF_V0_KEY' undeclared here (not in a function); did you mean 'BTRFS_EXTENT_DATA_KEY'?
167 | static_assert((unsigned long long) (BTRFS_EXTENT_REF_V0_KEY)
|                                     ^~~~~~~~~~~~~~~~~~~~~~~
|                                     BTRFS_EXTENT_DATA_KEY
- 禁止有关 "GitHub Actions" 的提交
- 禁止使用 users.noreply.github.com 提交
> strace: bump to version 6.6

- package/boot/uboot-rockchip/Makefile
- package/boot/uboot-rockchip/patches/318-rockchip-rk3568-Add-support-for-advantech-rsb4810.patch
- target/linux/rockchip/armv8/base-files/etc/board.d/02_network
- target/linux/rockchip/files/arch/arm64/boot/dts/rockchip/rk3568-rsb4810.dts
- target/linux/rockchip/image/armv8.mk
- target/linux/rockchip/patches-5.15/210-rockchip-rk356x-add-support-for-new-boards.patch
- target/linux/rockchip/patches-6.1/210-rockchip-rk356x-add-support-for-new-boards.patch
- target/linux/rockchip/patches-6.6/210-rockchip-rk356x-add-support-for-new-boards.patch
Advantech RSB-4810 Hardware Specifications:
Rockchip Arm Cortex-A55 RK3568 3.5" SBC
Rockchip RK3568 Arm Quad Cortex-A55, up to 2.0GHz
Built-in NPU with processing performance of up to 1.0 TOPS
Onboard 2/4GB LPDDR4 memory and 16/32GB eMMC
Supports 1 x HDMI 2.0 4K, 1 x LVDS/MIPI-DSI, and 1 x eDP
Supports 4K H.264/H.265 video decoder
Provides 2 x GbE, 1 x SATA 3.0, 6 x UART, 2 x USB 3.0, 2 x USB 2.0, 1 x USB OTG, and 2 x CAN
Provides a M.2 E Key with PCIE 3.0/USB 2.0/SDIO/UART signal for Wi-Fi 5/6 Modules, and a MINI-PCIE with PCIE 3.0/USB 2.0 signal for LTE/5G Modules
[Official Details](https://www.advantech.com/en/products/b6edc1fb-ade2-4760-986c-451b7b3d6dd5/rsb-4810/mod_244fc43f-9c10-43c8-bf08-79cda2e5a8bd)
[Official Software Resource](http://ess-wiki.advantech.com.tw/view/AIM-Linux/RSB-4 …
> rockchip: Add support for Advantech RSB4810

- tools/autoconf-archive/patches/001-fix_ax_c_float_words_bigendian.patch
See https://github.com/autoconf-archive/autoconf-archive/commit/23be7ccd7f306fbc73b3f33e2f5ead716d120eef
I noticed some packages/tools are old, should I create another PR to update them instead of submitting a patch?
> Fix: ax_c_float_words_bigendian fails when lto enabled

- README.md
- README_EN.md
- README_JA.md
Update the documentation about the default path for the environment when using the Apple silicon version of the Mac
use `/opt/homebrew/opt` instead of `/usr/local/opt`
> doc: Update the mac section of the document

- package/lean/autocore/files/arm/sbin/cpuinfo
1. fix missing CPU frequency info for rockchip
2. adjust indent
> autocore: fix missing CPU frequency info for rockchip

- target/linux/ramips/dts/mt7620a_bolt_bl201.dts
- target/linux/ramips/image/mt7620.mk
- target/linux/ramips/mt7620/base-files/etc/board.d/01_leds
- target/linux/ramips/mt7620/base-files/etc/board.d/02_network
This update eliminates the need to change the bootloader using breedweb, though breedweb remains an option.
Changes:
1. Update device baud rate.
2. Modify LED and button GPIO values and names.
3. Adjust partition layout to match the stock configuration.
4. Add missing package dependencies for USB.
5. Include device UIMAGE Magic value.
6. Revise switch layout.
7. Assign different MAC addresses to eth0.1 and eth0.2, consistent with the stock firmware.
Tested: OK
> ramips: update Bolt BL201 to match stock bootloader

- package/lean/leigod-acc/files/leigod-helper.sh
- package/lean/luci-app-leigod-acc/luasrc/controller/acc.lua
- package/lean/luci-app-leigod-acc/luasrc/model/cbi/leigod/service.lua
- package/lean/luci-app-leigod-acc/root/etc/config/accelerator
**其他人别合**
- 新增计划任务暂停时长
暂停时长是雷神特色，调用 API 接口实现并且使用 jq ，所以需要 Makefile 添加一个依赖 jq
BUG:
- crontabs 这里不能提交到计划任务，并且关闭了该选项会错误（一个或多个必选项值为空！）
- tunnel 这里我没搞，貌似是一个虚空选项
会的人来弄好了 Debug 一下
tunnel 这里 ${args} 就是默认的 Tproxy，把 ${args} 整掉改成 --mode tun 就是 TUN 模式了
> Leigod-Acc: Add Scheduled Pause

- target/linux/rockchip/image/Makefile
> rockchip: fix failure in copying some device dtbs

- target/linux/rockchip/patches-6.1/203-rockchip-rk3328-Add-support-for-OrangePi-R1-Plus-LTS.patch
The default strength is not enough to provide stable connection under 3.3v LDO voltage.
> rockchip: configure pad driver strength for orangepi r1 plus lts

- package/boot/uboot-envtools/files/mediatek_filogic
- package/kernel/linux/modules/crypto.mk
- target/linux/generic/backport-5.15/750-v6.5-20-net-ethernet-mtk_eth_soc-fix-uninitialized-variable.patch
- target/linux/generic/hack-5.15/767-net-phy-realtek-add-led-link-select-for-RTL8221.patch
- target/linux/generic/hack-6.1/767-net-phy-realtek-add-led-link-select-for-RTL8221.patch
- target/linux/generic/hack-6.6/767-net-phy-realtek-add-led-link-select-for-RTL8221.patch
- target/linux/generic/pending-5.15/700-net-ethernet-mtk_eth_soc-avoid-creating-duplicate-of.patch
- target/linux/generic/pending-5.15/702-net-ethernet-mtk_eth_soc-enable-threaded-NAPI.patch
- target/linux/generic/pending-5.15/732-03-net-ethernet-mtk_eth_soc-fix-remaining-throughput-re.patch
- target/linux/generic/pending-5.15/736-01-net-ethernet-mtk_eth_soc-add-code-for-offloading-flo.patch
- target/linux/generic/pending-5.15/736-04-net-ethernet-mediatek-fix-ppe-flow-accounting-for-L2.patch
- target/linux/generic/pending-5.15/737-net-ethernet-mtk_eth_soc-add-paths-and-SerDes-modes-.patch
- target/linux/mediatek/dts/mt7981b-openembed-som7981.dts
- target/linux/mediatek/filogic/base-files/etc/board.d/01_leds
- target/linux/mediatek/filogic/base-files/etc/board.d/02_network
- target/linux/mediatek/filogic/base-files/etc/hotplug.d/ieee80211/11_fix_wifi_mac
- target/linux/mediatek/image/filogic.mk
```
Hardware specification:
SoC: MediaTek MT7981B 2x A53
Flash: 256 MiB SPI-NAND
RAM: 0.5/1 GB DDR4
Ethernet: 1x 1GbE, 1x 2.5GbE (RTL8221B)
WiFi: MediaTek MT7976C
USB: 1x M.2 B-Key
GPIO: 26-Pin header
UART: 6 GND, 8 TX, 10 RX (in Pin header)
Button: Reset
Installation:
The board comes with a third-party custom OpenWrt image, you can upload
sysupgrade image via LuCI directly WITHOUT keeping configurations.
Or power on the board with pressing reset button for 5 second, then visit
http://192.168.1.1/ and upload -factory.bin firmware.
```
> mediatek: add support for OpenEmbed SOM7981

- package/lean/mt/drivers/mt7615d/src/mt_wifi/embedded/security/bn_lib.c
This PR fixes a security vulnerability in BN_mod_sqrt() that was cloned from OpenSSL but did not receive the security patch applied in OpenSSL. The original issue was reported and fixed under CVE-2022-0778.
The function BN_mod_sqrt() in this repository is nearly identical to BN_mod_sqrt() from OpenSSL.
The original function was patched due to a vulnerability identified in CVE-2022-0778.
The same issue exists in this repository's function but remains unpatched.
This PR applies the same patch as the one in OpenSSL to eliminate the vulnerability.
CVE: [CVE-2022-0778](https://nvd.nist.gov/vuln/detail/CVE-2022-0778)
Original Fix: [Original Fix](https://github.com/openssl/openssl/commit/3118eb64934499d93db3230748a452351d1d9a65)
> Fix: Addressing Vulnerability in Cloned Function

- package/lean/mt/drivers/mt7603e/src/mt7603_wifi/common/bn_lib.c
**Description**
This PR fixes a security vulnerability in BN_mod_sqrt() that was cloned from openssl but did not receive the security patch. The original issue was reported and fixed under https://github.com/openssl/openssl/commit/3118eb64934499d93db3230748a452351d1d9a65.
This PR applies the same patch to eliminate the vulnerability.
**References**
https://nvd.nist.gov/vuln/detail/CVE-2022-0778
https://github.com/openssl/openssl/commit/3118eb64934499d93db3230748a452351d1d9a65
> Fix: Potential Vulnerability in Cloned Function

- target/linux/ipq40xx/base-files/etc/hotplug.d/firmware/11-ath10k-caldata
- target/linux/ipq40xx/files/arch/arm/boot/dts/qcom-ipq4018-ap4220-128m.dts
- target/linux/ipq40xx/files/arch/arm/boot/dts/qcom-ipq4018-ap4220-48m.dts
- target/linux/ipq40xx/files/arch/arm/boot/dts/qcom-ipq4018-ap4220.dtsi
1. Add "ubi.mtd=rootfs" to dts for better compatibility with stock uboot and uboot_mod.
2. Remove wifi related nvmem nodes in dts to improve 2g and 5g mac addresses randomization issue.
3. Fixed wrong device name in "11-ath10k-caldata".
Tested-by: Willem Lee <1980490718@qq.com>
> ipq40xx: improve support for Alibaba AP4220

- toolchain/glibc/common.mk
The glibc build was failing with this error message:
aclocal.m4:6: error: Exactly version 2.69 of Autoconf is required but you have 2.71
aclocal.m4:6: the top level
The autoconf run on glibc is not needed, just remove it.
Fixes: #13308
> toolchain: glibc: Fix build with autoconf 2.71

- package/boot/uboot-armsr/Makefile
add support for `QEMU` `armv7`/`armv8` from upstream
dc780ad837c7ce5278c10eed1efa186908f7e770
> uboot-armsr: add support for QEMU armv7/armv8

- include/u-boot.mk
disable mkeficapsule for armsr due to a host-side GnuTLS dependency (fix #13566)
- [package/boot/uboot-armsr/Makefile](/coolsnowwolf/lede/blob/master/package/boot/uboot-armsr/Makefile)
```
UBOOT_CUSTOMIZE_CONFIG := \
--enable CMD_EFIDEBUG \
--disable TOOLS_MKEFICAPSULE
$(eval $(call BuildPackage/U-Boot))
```
> **UBOOT_CUSTOMIZE_CONFIG** 没生效，u-boot.mk 很久没更新了 🤪🤪🤪
> u-boot.mk: add support for config customization

- tools/elfutils/Makefile
Fedora 42 updated to GCC15 which now defaults to GNU23 as the default instead of GNU17[1], and this breaks m4 compilation.
This looks like a gnulib issue, so until that is updated/fixed lets simply set C language version back to GNU17.
[1] https://gcc.gnu.org/gcc-15/porting_to.html#c23
Link: https://github.com/openwrt/openwrt/pull/18506
> tools: elfutils: set -std=gnu17

- scripts/download.pl
ftp.kddilabs.jp has been shutdown and
now returns 404.
上游：https://github.com/openwrt/openwrt/commit/ce81918d4be62c9c7254068b3cdeb94569aa685f
> scripts/download.pl: drop ftp.kddilabs.jp

- package/libs/mpfr/Makefile
- package/libs/mpfr/patches/001-only-src.patch
Import mpfr from the packages feed to the main OpenWrt repo, as gdb 14 requires mpfr.
上游：https://github.com/openwrt/openwrt/commit/309c2cd4fbd2876a144bb4423428363f36c67a3f
> mpfr: import from packages feed
